### PR TITLE
Delete unscheduled modules that are not consumed by any scheduled module

### LINKED ISSUE #26438: Prune non-consumed EDProducers that are only in Tasks
If a configuration contains an EDProducer in a `Task` (and only in `Task`s) that is not consumed by the chain of consumes starting from the output modules, the `produce()` of such an EDProducer is not run, but all other transition functions are. This behavior may be confusing.

The behavior becomes even more confusing with `SwitchProducer` that intentionally injects all the case-producers into the configuration (like they would be in an anonymous task), but only one of them intended to be run. This means that all non-event transitions will be called for all the case-producers, which may be a bit surprising.

It follows that e.g. if CUDA producers (either as a case of `SwitchProducer`, or being consumed by a case -producer) want to call CUDA API from non-`produce()`/`acquire()` functions, the availability of CUDA devices would have to be explicitly checked.

If we would prune non-consumed EDProducers, they would be ignored for all transitions, and no explicit checks for CUDA (or anything else similar) would have to be done. The exceptions would be the constructor and destructor, that would still be always called for all EDProducers.

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR makes the framework to delete unscheduled EDModules whose output products are not consumed by any scheduled EDModule. For motivation see https://github.com/cms-sw/cmssw/issues/26438 (which this PR mostly resolves).

Here "unscheduled" means that such EDModules are only in `Task`s, i.e. not directly in any `Path` or `EndPath`, and "scheduled" means an EDModule in a `Path` or `EndPath`. If the module data dependence graph has a subgraph of unscheduled modules whose output products are not consumed by any scheduled module, those unscheduled modules are deleted.

A possible data dependence from a scheduled module from a SubProcess is also enough to keep an otherwise non-consumed EDModule alive. For example, if the Process and its SubProcess both have a module `foo`, and only the SubProcess has a consumer with an `InputTag("foo")`, the module `foo` in the Process is kept as well for the case that the SubProcess's `foo` would not produce a product for some events (assuming the product types and instance names also match).

The data dependencies are checked also for Lumi and Run products in addition of Event products, for which the `EDConsumerBase::modulesWhoseProductsAreConsumed()` and `PathsAndConsumesOfModules` were extended. They were extended also to carry the dependencies from the SubProcesses (it turned out that passing pairs of module label and process name are sufficient, the product type and instance name get handled automatically).

The non-consumed modules are deleted after `preallocate` signal and before `beginJob()` signal. Two new signals, `preModuleDestruction` and `postModuleDestruction` are added for those deletions (the "normal" module deletion at the end of the `cmsRun` process do not emit these signals). I took a look of all modules watching either `preModuleConstruction` or `postModuleConstruction` signals, and added watch for the destruction signals if it seemed to make sense.

Note that even if the modules are deleted, the corresponding Workers are kept alive. The Workers are removed from the containers of unscheduled and accumulator modules, so they won't get any further framework transitions after the deletion.

Resolves https://github.com/cms-sw/cmssw/issues/26438.

#### PR validation:

Framework unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones @wddgit Please review

File: FWCore/Framework/src/EventProcessor.cc [hunk 1]
```diff
@@ -536,9 +536,30 @@ namespace edm {
...
+        not unusedModules.empty()) {
+      pathsAndConsumesOfModules_.removeModules(unusedModules);
+
+      edm::LogWarning("DeleteModules").log([&unusedModules](auto& l) {
+        l << "Following modules are not in any Path or EndPath, nor is their output consumed by any other module, and "
+             "therefore they are deleted before beginJob transition.";
+        for (auto const& description : unusedModules) {
+          l << "\n " << description->moduleLabel();
+        }
+      });
```
Comment (makortel) [inline FWCore/Framework/src/EventProcessor.cc:557]: I was thinking to keep this printout (and the corresponding one in the `SubProcess.cc`) enabled for a couple of IBs (to ease debugging in case problems occur), and then demote them to `LogInfo`.

File: FWCore/Framework/interface/EDConsumerBase.h [hunk 2]
```diff
@@ -97,7 +99,9 @@ namespace edm {
     typedef ProductLabels Labels;
     void labelsForToken(EDGetToken iToken, Labels& oLabels) const;
 
-    void modulesWhoseProductsAreConsumed(std::vector<ModuleDescription const*>& modules,
+    void modulesWhoseProductsAreConsumed(std::vector<ModuleDescription const*>& modulesEvent,
+                                         std::vector<ModuleDescription const*>& modulesLumiRun,
```
Comment (makortel) [inline FWCore/Framework/interface/EDConsumerBase.h:103]: In light of `ProcessBlock` I'm thinking this parameter (and the corresponding storage in `PathsAndConsumesOfModules`) be either renamed to `modulesNonEvent`, or separate the `Lumi`, `Run`, and (eventually) `Process`.

**Comment by makortel** [comment]
@wddgit 
> The data dependencies are checked also for Lumi and Run products in addition of Event products, for which the `EDConsumerBase::modulesWhoseProductsAreConsumed()` and `PathsAndConsumesOfModules` were extended.

These checks need to be extended for `ProcessBlock` when we get there, but I'd expect it to be straightforward.

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by wddgit** [comment]
@makortel Hi Matti, I am reviewing the PR. I was just starting to carefully go through EDConsumerBase for the ProcessBlock PR I am working on, so the timing is good. It may take a while as this is big.

**Comment by wddgit** [comment]
This PR looks good to me. I read through it and didn't notice any problems. I see lots of tests, which is great.

I was trying to think of corner cases where this might cause some problem. The only thing I came up with was that I was wondering what might happen if the looper changed a module in some way that changed the dependencies from one loop to the next. This probably never happens. I don't really understand what loopers do from one loop to the next very well.

**Comment by makortel** [comment]
Thanks @wddgit 

> I was trying to think of corner cases where this might cause some problem. The only thing I came up with was that I was wondering what might happen if the looper changed a module in some way that changed the dependencies from one loop to the next. This probably never happens. I don't really understand what loopers do from one loop to the next very well.

I had not thought about looper at all. @Dr15Jones, could you comment if loopers can change data dependencies or sets of modules between loops? (I would find such behavior a bit weird, but that doesn't prove anything)

**Comment by wddgit** [comment]
It looks here like one can just completely replace modules with
new modules with new configurations. I did not carefully trace this
through completely, so maybe I am somehow wrong. But this is what
I was worried about.

https://cmssdt.cern.ch/lxr/source/FWCore/Framework/src/Schedule.cc#1266

I am happy if we just say the problem is sufficiently unlikely to happen
in the next 20 years that we just ignore it. And if it happens, then we deal
with it then. The likely failure mode is a ProductNotFound exception,
so we would probably notice.

Another easy approach would be to disable the module deletion when
there is a looper.

Fireworks/FWInterface/interface/FWFFLooper.h seems to be the only thing
using this looper feature other than tests. I don't know if that is actually
used or not.

**Comment by makortel** [comment]
@cmsbuild, please test

Let's see if the fixes so far are sufficient

File: FWCore/Framework/interface/EDConsumerBase.h [hunk 3]
```diff
@@ -97,7 +99,9 @@ namespace edm {
...
+                                         std::set<ModuleProcessName>& modulesInPreviousProcesses,
```
Comment (Dr15Jones) [inline FWCore/Framework/interface/EDConsumerBase.h:104]: Does this gather info from both parent Processes (assuming the module itself is in a SubProcess) as well as dependencies on data in the Source? Or is this only parents?

File: FWCore/Framework/interface/ModuleProcessName.h [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+#include <string_view>
+
+namespace edm {
+  /**
+   * Helper class to hold a module label and a process name
+   *
+   * Note: does NOT own the string storage, be careful to use.
+   */
+  class ModuleProcessName {
```
Comment (Dr15Jones) [inline FWCore/Framework/interface/ModuleProcessName.h:12]: As ModuleDescription already holds both these pieces of information, why have this data structure as well?

File: FWCore/Framework/interface/PathsAndConsumesOfModules.h [hunk 5]
```diff
@@ -62,12 +72,17 @@ namespace edm {
     // following data member
     std::vector<std::pair<unsigned int, unsigned int> > moduleIDToIndex_;
 
-    std::vector<std::vector<ModuleDescription const*> > modulesWhoseProductsAreConsumedBy_;
+    std::vector<std::vector<ModuleDescription const*> > modulesWhoseProductsAreConsumedByEvent_;
+    std::vector<std::vector<ModuleDescription const*> > modulesWhoseProductsAreConsumedByLumiRun_;
+    std::vector<std::set<ModuleProcessName> > modulesInPreviousProcessesWhoseProductsAreConsumedBy_;
```
Comment (Dr15Jones) [inline FWCore/Framework/interface/PathsAndConsumesOfModules.h:77]: Does this really need to be a `set` instead of a sorted `vector`? What are the different entries in the `vector`?

File: FWCore/Framework/interface/EDConsumerBase.h (hunk 2 above)
Comment (Dr15Jones) [reply FWCore/Framework/interface/EDConsumerBase.h:103]: Would it be better to do `std::array<std::vector<ModuleDescription const*>, Transition::NumberOfTransitions>` which would allow us to add transitions without changing the interface again?

File: FWCore/Framework/src/EventProcessor.cc [hunk 6]
```diff
@@ -536,9 +536,30 @@ namespace edm {
     actReg_->preallocateSignal_(bounds);
     schedule_->convertCurrentProcessAlias(processConfiguration_->processName());
     pathsAndConsumesOfModules_.initialize(schedule_.get(), preg());
+    std::set<ModuleProcessName> consumedBySubProcesses;
```
Comment (Dr15Jones) [inline FWCore/Framework/src/EventProcessor.cc:539]: Is this variable named incorrectly? I assume `subProcess.deleteNonConsumedUnscheduledModules()` would return what was deleted, not what was kept.

File: FWCore/Framework/src/EventProcessor.cc (hunk 1 above)
Comment (Dr15Jones) [reply FWCore/Framework/src/EventProcessor.cc:557]: Sounds reasonable. In the future probably would want an easy way to make this list easily visible. Maybe via the Tracer?

File: FWCore/Framework/src/SubProcess.cc [hunk 7]
```diff
@@ -210,6 +210,49 @@ namespace edm {
...
+    }
+
+    // Products possibly consumed from the parent (Sub)Process
+    for (auto const& description : pathsAndConsumesOfModules_.allModules()) {
+      for (auto const& dep :
+           pathsAndConsumesOfModules_.modulesInPreviousProcessesWhoseProductsAreConsumedBy(description->id())) {
+        consumedByChildren.emplace(dep.moduleLabel(), dep.processName());
+      }
+    }
+    return consumedByChildren;
```
Comment (Dr15Jones) [inline FWCore/Framework/src/SubProcess.cc:253]: So I see it says what was consumed. Given the name of the function the returned info seems at odds.

File: FWCore/Framework/src/Worker.h [hunk 8]
```diff
@@ -118,6 +119,11 @@ namespace edm {
     Worker(Worker const&) = delete;             // Disallow copying and moving
     Worker& operator=(Worker const&) = delete;  // Disallow copying and moving
 
+    void clearModule() {
```
Comment (Dr15Jones) [inline FWCore/Framework/src/Worker.h:122]: When will we have a Worker around when its module is gone?

File: FWCore/Framework/test/stubs/TestStreamProducers.cc [hunk 9]
```diff
@@ -664,14 +664,20 @@ namespace edmtest {
       //Using mutable since we want to update the value.
       mutable std::atomic<unsigned int> m_value;
       mutable std::atomic<unsigned int> m_expectedValue;
+      // Set only in constructor, framework runs constructors serially
+      CMS_THREAD_SAFE mutable edm::EDPutTokenT<unsigned int> m_putToken;
```
Comment (Dr15Jones) [inline FWCore/Framework/test/stubs/TestStreamProducers.cc:668]: Interesting problem where stream module wants to do a global put. Hmm.

File: FWCore/Framework/test/stubs/ToyAnalyzers.cc [hunk 10]
```diff
@@ -95,6 +96,75 @@ namespace edmtest {
     std::vector<edm::EDGetTokenT<IntProduct>> m_tokens;
   };
 
+  //--------------------------------------------------------------------
+  //
+  template <typename T>
+  class GenericIntsAnalyzerT : public edm::global::EDAnalyzer<> {
```
Comment (Dr15Jones) [inline FWCore/Framework/test/stubs/ToyAnalyzers.cc:102]: Does this really apply to only Ints?

File: FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py [hunk 11]
```diff
@@ -14,4 +14,5 @@
                            consumesBeginLuminosityBlock = cms.InputTag("a", "beginLumi"),
                            expectBeginLuminosityBlock = cms.untracked.int32(1))
 
-process.schedule = cms.Schedule(tasks=cms.Task(process.a,process.b,process.c))
```
Comment (Dr15Jones) [inline FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:17]: Why require the process to be named?

File: FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py [hunk 12]
```diff
@@ -14,4 +14,5 @@
...
+process.t = cms.Task(process.a, process.c)
+process.p = cms.Path(process.b, process.t)
```
Comment (Dr15Jones) [inline FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: Why force the task on the Path rather than just the Schedule?

**Review by Dr15Jones — COMMENTED** [review]
Made it through all of FWCore/Framework

File: FWCore/Framework/interface/EDConsumerBase.h (hunk 2 above)
Comment (makortel) [reply FWCore/Framework/interface/EDConsumerBase.h:103]: It would, thanks for the suggestion.

File: FWCore/Framework/interface/EDConsumerBase.h (hunk 3 above)
Comment (makortel) [reply FWCore/Framework/interface/EDConsumerBase.h:104]: It contains also dependencies on data in the Source, basically the (module label, process name) pairs for all consumed products that either can not be satisfied by the producers in the SubProcess (no such module label or process name is different), or may be satisfied by the producers in "earlier processes" (process name is empty or instructed to skip the current process).

File: FWCore/Framework/interface/ModuleProcessName.h (hunk 4 above)
Comment (makortel) [reply FWCore/Framework/interface/ModuleProcessName.h:12]: Good question. In this class the process name may be empty. On the other hand I could  move the process matching logic now in
https://github.com/cms-sw/cmssw/blob/feca570fcc574c514926e7ef758a4a0b52477334/FWCore/Framework/src/PathsAndConsumesOfModules.cc#L198-L201
to be done in `EDConsumerBase::modulesWhoseProductsAreConsumed()` and return `ModuleDescription` instead. But to use `ModuleDescription` I would need to get a hold of one of a parent (Sub)Process in an `EDConsumerBase::modulesWhoseProductsAreConsumed()` of a SubProcess. I'm not sure what would be the best way to do that.

File: FWCore/Framework/interface/PathsAndConsumesOfModules.h (hunk 5 above)
Comment (makortel) [reply FWCore/Framework/interface/PathsAndConsumesOfModules.h:77]: > Does this really need to be a `set` instead of a sorted `vector`? 

It can be a sorted `vector`.

> What are the different entries in the `vector`?

The (outermost) `vector` has an entry for each module in the (Sub)Process.

File: FWCore/Framework/src/EventProcessor.cc (hunk 6 above)
Comment (makortel) [reply FWCore/Framework/src/EventProcessor.cc:539]: > Is this variable named incorrectly? 

The name is correct.

> I assume `subProcess.deleteNonConsumedUnscheduledModules()` would return what was deleted, not what was kept.

That function returns the set of (module label, process name) pairs that are consumed by that `subProcess` but may need to be produced by the Process.

I agree the function name could be better, I'm open for suggestions.

In principle the function could be split into two, one for fetching the consumes information from parent (Sub)Process and one for deleting the modules. On the first thought that does not feel easy because for a SubProcess having to first get the consumes information from a child SubProcess, then delete the nonconsumed modules in the current SubProcess, and then update the consumes information based on which products the current SubProcess consumes.

File: FWCore/Framework/src/EventProcessor.cc (hunk 1 above)
Comment (makortel) [reply FWCore/Framework/src/EventProcessor.cc:557]: Tracer already prints out the deleted modules (between "ModuleConstruction" and "BeginJob"). Also with `LogInfo` the "DeleteModules" messages can be enabled purely in the configuration.

File: FWCore/Framework/src/Worker.h (hunk 8 above)
Comment (makortel) [reply FWCore/Framework/src/Worker.h:122]: I agree it would be cleaner to remove also the Worker. I suppose that cleanup should extend in all places holding a pointer to a Worker, e.g. ProductResolvers.

Maybe such a cleanup could be done in a follow-up PR?

File: FWCore/Framework/test/stubs/TestStreamProducers.cc (hunk 9 above)
Comment (makortel) [reply FWCore/Framework/test/stubs/TestStreamProducers.cc:668]: I copied the pattern from
https://github.com/cms-sw/cmssw/blob/6d0e276c82e1a460a634b92f141252d534adc1c2/DQMServices/Core/interface/DQMEDAnalyzer.h#L28-L34

File: FWCore/Framework/test/stubs/ToyAnalyzers.cc (hunk 10 above)
Comment (makortel) [reply FWCore/Framework/test/stubs/ToyAnalyzers.cc:102]: Good catch, it could be just `GenericAnalyzerT`.

File: FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py (hunk 11 above)
Comment (makortel) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:17]: I don't understand your question, could you elaborate?

File: FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py (hunk 12 above)
Comment (makortel) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: Didn't come to my mind. Combined with the previous question, are you perhaps thinking 
```python
process.p = cms.Path(process.b)
process.schedule = cms.Schedule(process.p, tasks=cms.Task(process.a, process.c))
```
?

Comment (Dr15Jones) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: My question is why did you bother to change what was already there?

File: FWCore/Framework/interface/EDConsumerBase.h (hunk 2 above)
Comment (wddgit) [reply FWCore/Framework/interface/EDConsumerBase.h:103]: Would the transition be the transition in which the product is consumed or the transition in which the product is produced? Are we adding the transition to the interface of the consumes function or where does this information come from?

File: FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py (hunk 12 above)
Comment (makortel) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: If all the modules are in Tasks they will all be deleted. I need the last one of the consumer chain to be scheduled to keep the rest alive.

Comment (Dr15Jones) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: I had missed the fact that you had moved one of the modules to a Path.

File: FWCore/Framework/interface/EDConsumerBase.h (hunk 2 above)
Comment (makortel) [reply FWCore/Framework/interface/EDConsumerBase.h:103]: Thanks @wddgit. It is actually the branch type where the product exists, so the parameter should be `std::array<std::vector<ModuleDescription const*>, NumBranchTypes>`.

**Comment by silviodonato** [comment]
@Dr15Jones please find inline @makortel's replies

File: FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py (hunk 11 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:17]: The question should have been "Why require the task to be named?" 
The answer was already given that you had to create a Path to avoid having the modules be removed.

**Review by Dr15Jones — COMMENTED** [review]
I finished looking at all the remaining files and have no additional comments.

**Comment by silviodonato** [comment]
@makortel what is the plan about this PR?

File: FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py (hunk 12 above)
Comment (wddgit) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: I noticed this empirically while doing my ProcessBlock testing. It is not at all obvious looking at it, but this change just coincidentally happens to give the execution order 'a' then 'c' then 'b'. Since the purpose of the test is to demonstrate the Framework is forcing that execution order we should probably perturb this in some way so it isn't just doing it by accident. Renaming 'a' to 'd' seems to do the trick. Without looking at the internals of code, it appears to be running the Tasks alphabetically first (I'm just guessing).

Comment (makortel) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: Good catch David, thanks. Is the test good-enough for ProcessBlock purposes? I.e. would it be sufficient to rename `a` to `d` in this PR?

Comment (wddgit) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: Yes. At the moment in my branch, I added two new cfg.py's that do the analogous tests for beginProcessBlock and endProcessBlock with 'a' renamed to 'd'.

File: FWCore/Framework/src/EventProcessor.cc (hunk 6 above)
Comment (makortel) [reply FWCore/Framework/src/EventProcessor.cc:539]: Renamed the function to `keepOnlyConsumedUnscheduledModules()` (thanks to @Dr15Jones for the suggestion).

File: FWCore/Framework/test/stubs/ToyAnalyzers.cc (hunk 10 above)
Comment (makortel) [reply FWCore/Framework/test/stubs/ToyAnalyzers.cc:102]: Renamed to `GenericAnalyzerT`.

File: FWCore/Framework/interface/EDConsumerBase.h (hunk 2 above)
Comment (makortel) [reply FWCore/Framework/interface/EDConsumerBase.h:103]: Changed to `std::array<std::vector<ModuleDescription const*>* , NumBranchTypes>` (need an array of pointers because they are stored as `std::vector<std::vector<ModuleDescription>>` and arrays of references are not allowed).

File: FWCore/Framework/interface/ModuleProcessName.h (hunk 4 above)
Comment (makortel) [reply FWCore/Framework/interface/ModuleProcessName.h:12]: We agreed to keep `ModuleProcessName` for now.

File: FWCore/Framework/interface/PathsAndConsumesOfModules.h (hunk 5 above)
Comment (makortel) [reply FWCore/Framework/interface/PathsAndConsumesOfModules.h:77]: Changed the `set` to sorted `vector`.

File: FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py (hunk 12 above)
Comment (makortel) [reply FWCore/Framework/test/test_non_event_ordering_beginLumi_cfg.py:18]: Renamed `a` to `d` in all four non-event transition tests.

**Comment by makortel** [comment]
> Another easy approach would be to disable the module deletion when
> there is a looper.

I decided to go with this route.

**Comment by makortel** [comment]
* rebased to `11_1_0_pre8` to fix conflict
* addressed all review comments
  * except the cleanup of Workers, which I'll start look into next, but I'll likely leave it to a subsequent PR
* protected `DependencyGraph` Service for module ID larger than the number of modules (similar to #29584)

Framework unit tests run.

File: FWCore/Services/plugins/DependencyGraph.cc [hunk 13]
```diff
@@ -222,7 +222,7 @@ void DependencyGraph::preBeginJob(PathsAndConsumesOfModulesBase const &pathsAndC
     boost::get_property(m_graph, boost::graph_graph_attribute)["labelloc"] = "top";
 
     // create graph vertices associated to all modules in the process
-    auto size = pathsAndConsumes.allModules().size();
+    auto size = pathsAndConsumes.largestModuleID() - boost::num_vertices(m_graph) + 1;
```
Comment (makortel) [inline FWCore/Services/plugins/DependencyGraph.cc:225]: @fwyzard Subtracting the number of already existing vertices from the largest module ID is kind of closest to earlier "number of modules", and is needed make the SubProcesses to have proper boundaries in the graph. Should the `ProcessCallGraph` be updated accordingly?

Here is an example how the deleted modules get treated
image
i.e. they are presented as ellipses with a number

**Comment by makortel** [comment]
@cmsbuild, please test

File: FWCore/Framework/src/WorkerRegistry.cc [hunk 14]
```diff
@@ -44,4 +44,23 @@ namespace edm {
...
+  }
+
+  void WorkerRegistry::deleteModule(std::string const& moduleLabel) {
+    WorkerMap::iterator workerIt = m_workerMap.find(moduleLabel);
+    if (workerIt == m_workerMap.end()) {
+      throw cms::Exception("LogicError")
+          << "WorkerRegistry::deleteModule() Trying to delete the module of a Worker with label " << moduleLabel
+          << " but no such Worker exists in the WorkerRegistry. Please contact framework developers.";
+    }
+    workerIt->second->clearModule();
```
Comment (makortel) [inline FWCore/Framework/src/WorkerRegistry.cc:63]: @Dr15Jones Actually in a quick test with
```suggestion
    m_workerMap.erase(workerIt);
```
the (relevant) test configurations run. That would leave stale pointers to the `Worker` though e.g. in all ProductResolvers corresponding the products of the deleted producers. Would it be good to try to clean up all those as well?

**Comment by makortel** [comment]
Unit test failure could be https://github.com/cms-sw/cmssw/issues/30049 (for which fix was just merged).

File: FWCore/Framework/src/WorkerRegistry.cc (hunk 14 above)
Comment (Dr15Jones) [reply FWCore/Framework/src/WorkerRegistry.cc:63]: I really hate leaving stale pointers anywhere.

Comment (makortel) [reply FWCore/Framework/src/WorkerRegistry.cc:63]: Thanks (my thoughts exactly), so I will not commit the change above and look into cleaning up the objects that would end up having stale pointers instead.

File: FWCore/Framework/src/EDConsumerBase.cc [hunk 15]
```diff
@@ -455,51 +456,80 @@ namespace {
...
        ++itInfo, ++itKind, ++itLabels) {
-    if (itInfo->m_branchType == InEvent and (not itInfo->m_index.skipCurrentProcess())) {
-      const unsigned int labelStart = itLabels->m_startOfModuleLabel;
-      const char* consumedModuleLabel = &(m_tokenLabels[labelStart]);
-      const char* consumedProcessName = consumedModuleLabel + itLabels->m_deltaToProcessName;
+    ProductResolverIndexHelper const& helper = *preg.productLookup(itInfo->m_branchType);
+    std::vector<ModuleDescription const*>& modules = *modulesAll[itInfo->m_branchType];
+
+    const unsigned int labelStart = itLabels->m_startOfModuleLabel;
+    const char* consumedModuleLabel = &(m_tokenLabels[labelStart]);
```
Comment (Dr15Jones) [inline FWCore/Framework/src/EDConsumerBase.cc:482]: These could probably be `const char* const`

File: FWCore/Framework/src/SubProcess.cc [hunk 16]
```diff
@@ -210,6 +210,62 @@ namespace edm {
 
   SubProcess::~SubProcess() {}
 
+  std::vector<ModuleProcessName> SubProcess::keepOnlyConsumedUnscheduledModules(bool deleteModules) {
+    ServiceRegistry::Operate operate(serviceToken_);
```
Comment (Dr15Jones) [inline FWCore/Framework/src/SubProcess.cc:214]: Why is the services turned on here?

File: FWCore/Framework/src/Worker.h (hunk 8 above)
Comment (Dr15Jones) [reply FWCore/Framework/src/Worker.h:122]: Doing the cleanup here or in a follow-up PR is up to you.

File: FWCore/Framework/src/EDConsumerBase.cc (hunk 15 above)
Comment (makortel) [reply FWCore/Framework/src/EDConsumerBase.cc:482]: > These could probably be `const char* const`

They can, done.

File: FWCore/Framework/src/SubProcess.cc (hunk 16 above)
Comment (makortel) [reply FWCore/Framework/src/SubProcess.cc:214]: I probably thought that it would be needed because in the current code the services are turned on before
```cpp
schedule_->convertCurrentProcessAlias(processConfiguration_->processName());
```
Removing it did not cause any framework unit test to fail, so I'll remove it. Thanks.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I'd prefer to have #30117 merged first (assuming it goes through the review smoothly) and then update this PR on top of that.

**Comment by makortel** [comment]
Rebased, fixed conflicts (and some typos in test configuration), and extended module deletion tests to cover ProcessBlock.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

To check if the issue in one addon test is indeed transient.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I'm confused by the addOn test error. [Earlier](https://github.com/cms-sw/cmssw/pull/29553#issuecomment-659227421) it was a file open error
```
----- Begin Fatal Exception 16-Jul-2020 07:51:01 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2017A/HLTPhysics4/RAW/v1/000/295/606/00000/36DE5E0A-3645-E711-8FA1-02163E01A43B.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2017A/HLTPhysics4/RAW/v1/000/295/606/00000/36DE5E0A-3645-E711-8FA1-02163E01A43B.root
      [b] Input file root://cms-xrd-global.cern.ch//store/data/Run2017A/HLTPhysics4/RAW/v1/000/295/606/00000/36DE5E0A-3645-E711-8FA1-02163E01A43B.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/data/Run2017A/HLTPhysics4/RAW/v1/000/295/606/00000/36DE5E0A-3645-E711-8FA1-02163E01A43B.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2017A/HLTPhysics4/RAW/v1/000/295/606/00000/36DE5E0A-3645-E711-8FA1-02163E01A43B.root?tried=
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```
but as far as I can tell the latest one actually succeeded
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d5d21d/8033/addOnTests/hlt_data_GRun/cmsDriver.py_RelVal_-s_L1REPACK:Full_--data_--scenario=pp_-n_10_--conditions_auto:run3_hlt_GRun_--relval_9000,50_--datatier_RAW_--eventcontent_RAW_-.log

I'm going to assume now that this error is unrelated.

**Comment by makortel** [comment]
@cmsbuild, please test

Let's try one more time.

File: FWCore/Framework/src/Worker.h (hunk 8 above)
Comment (makortel) [reply FWCore/Framework/src/Worker.h:124]: I created an issue to remind us https://github.com/cms-sw/cmssw/issues/30826.

**Comment by makortel** [comment]
@cmsbuild, please test

Once more.

**Comment by makortel** [comment]
> Preparing to run ['cmsDriver.py RelVal -s L1REPACK:Full --data --scenario=pp -n 10 --conditions auto:run3_hlt_GRun --relval 9000,50 --datatier "RAW" --eventcontent RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era Run3 --fileout file:RelVal_Raw_GRun_DATA.root --filein /store/data/Run2017A/HLTPhysics4/RAW/v1/000/295/606/00000/36DE5E0A-3645-E711-8FA1-02163AddOnTest might have timed out: FAILED - secs

@smuzaffar @mrodozov Could you comment if the claimed failure is indeed because of timeout? (it's suspiciously reproducible though) I'm unable to find anything in the HLT addon test logs.

**Comment by makortel** [comment]
> > Preparing to run ['cmsDriver.py RelVal -s L1REPACK:Full --data --scenario=pp -n 10 --conditions auto:run3_hlt_GRun --relval 9000,50 --datatier "RAW" --eventcontent RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era Run3 --fileout file:RelVal_Raw_GRun_DATA.root --filein /store/data/Run2017A/HLTPhysics4/RAW/v1/000/295/606/00000/36DE5E0A-3645-E711-8FA1-02163AddOnTest might have timed out: FAILED - secs
> 
> @smuzaffar @mrodozov Could you comment if the claimed failure is indeed because of timeout? (it's suspiciously reproducible though) I'm unable to find anything in the HLT addon test logs.

@smuzaffar @mrodozov Gentle ping

**Comment by smuzaffar** [comment]
please test
lets re-run the tests

**Comment by makortel** [comment]
@smuzaffar Still the same. Do you have any thoughts what could be going on?

**Comment by smuzaffar** [comment]
addOnTest timed out after 2 hours. I would suggest to re-run the addOnTest locally to see what is hanging

**Comment by smuzaffar** [comment]
one of these hanging one are [a]. This was running for two hours

[a]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d5d21d/8246/addOnTests/fastsim/cmsDriver.py_TTbar_8TeV_TuneCUETP8M1_cfi__--conditions_auto:run1_mc_--fast__-n_100_--eventcontent_AODSIM,DQM_--relval_100000,1000_-s_GEN,SIM,RECOBEFMI.log

**Comment by makortel** [comment]
Thanks @smuzaffar, I'll run the tests locally then.

(would there be any chance to improve the PR test reporting for which test took too long?)

**Comment by makortel** [comment]
I can reproduce locally. Essentially all the fastsim addOn tests lead to starvation after the first event of each stream. Debugging...

**Comment by makortel** [comment]
There appears to be a problem already in the base release https://github.com/cms-sw/cmssw/issues/30937, which then with this PR leads to modules that are actually consumed to be deleted, leading to a starvation in the TBB task scheduler. (probably if the Workers and ProductResolvers were cleaned here, the problem could have surfaced in a more clear crash)

In this case the `l1extraParticles` is in `L1Reco_step` and thus remains to be run. It consumes `gtDigis` (along other products), which in this configuration is an EDAlias
https://github.com/cms-sw/cmssw/blob/8d03f366426f05d38169387b6404ab070a7a3ad4/FastSimulation/Configuration/python/DigiAliases_cff.py#L170-L180
so in reality it is consuming `simGtDigis` and `simGmtDigis`. According to Tracer (i.e. from `PathsAndConsumesOfModules`) `l1ExtraParticles` consumes `simGmtDigis` of these two (because of logic explaind in https://github.com/cms-sw/cmssw/issues/30937#issuecomment-665023891). This leads to this PR think that `simGtDigis` would not be consumed, so it gets deleted, which leads to other modules (workers) wait for the `simGtDigis` to complete while it never will.

**Comment by makortel** [comment]
Rebased on top of CMSSW_11_2_X_2020-10-01-1100, and squashed some commits together where it made sense and was easy.

**Comment by makortel** [comment]
I'm thinking to add a possibility to disable the deletion via a configuration parameter, something along `process.options.deleteNonConsumedUnscheduledModules = False`.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@silviodonato @qliphy I'm thinking (again) that this PR could be too risky to for the last open pre-release.

**Comment by Dr15Jones** [comment]
> @silviodonato @qliphy I'm thinking (again) that this PR could be too risky to for the last open pre-release.

I concur.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1
