### PR TITLE
Release dependent modules only after the worker has finished for scheduled modules

### LINKED ISSUE #39064: Crashes in muon HLT reconstruction (`reco::TrackExtra` product not found)
Over the last few weeks, HLT suffered 3 online crashes coming the HLT-muon reconstruction; the first 2 errors are almost identical, while the 3rd one is rather similar to the first 2, but comes from a different producer. The error messages are given below [*].

So far, no one has been able to reproduce any of these errors locally with the relevant error-stream files.

I open an issue to keep track of this, and to ask experts if the error messages suggest to them anything about what might be going wrong.

[This config file](https://github.com/cms-sw/cmssw/blob/fbcaee015ff6ba43edc1ccd9002fab39125dee6c/HLTrigger/Configuration/test/OnLine_HLT_2022v13.py) should be representative of the HLT menu used online during the crashes (representative at least for what concerns the sequences that contain the problematic modules).

FYI: @JanFSchulte @khaosmos93 (Muon-HLT contacts), @silviodonato @Martin-Grunewald @fwyzard

[*]

1) Run-356433 (`CMSSW_12_4_3`, Jul 29th):
```
[2] Calling method for module TSGFromL2Muon/'hltL3TrajSeedOIStateNoVtx'
Exception Message:
RefCore: A request to resolve a reference to a product of type 'std::vector<reco::TrackExtra>' with ProductID '1:2802'
can not be satisfied because the product cannot be found.
Probably the branch containing the product is not stored in the input file.
Additional Info:
[a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```

2) Run-356530 (`CMSSW_12_4_3`, Aug 1st):
```
[2] Calling method for module TSGFromL2Muon/'hltL3TrajSeedOIStateNoVtx'
Exception Message:
RefCore: A request to resolve a reference to a product of type 'std::vector<reco::TrackExtra>' with ProductID '1:2804'
can not be satisfied because the product cannot be found.
Probably the branch containing the product is not stored in the input file.
Additional Info:
[a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```

3) Run-357442 (`CMSSW_12_4_6`, Aug 14th):
```
[2] Calling method for module TSGForOIFromL2/'hltIterL3OISeedsFromL2MuonsNoVtx'
Exception Message:
RefCore: A request to resolve a reference to a product of type 'std::vector<reco::TrackExtra>' with ProductID '1:2782'
can not be satisfied because the product cannot be found.
Probably the branch containing the product is not stored in the input file.
Additional Info:
[a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

In https://github.com/cms-sw/cmssw/issues/39064#issuecomment-1227671651 we found that the `PuttableProductResolver::putProduct()` releasing the task(s) for dependent modules can lead to rare problems if the producing module produces two (or more) products that refer to each other. Specifically, a consuming module may get run when only one of the products has been put in place, that can lead to deference of a Ref to fail on "missing product".

All consuming modules call the `prefetchAsync_()`, which for `PuttableProductResolver` already creates a task to release the dependent modules (`m_waitingTasks`), and inserts that into the Worker's `WaitingTaskList` (that is released after the Worker finishes). I think we could just rely on that ~~, and therefore this PR removes the override of `putProduct()` from `PuttableProductResolver`~~. This assumption turned out to be wrong, because there is also another use case for `PuttableProductResolver`: `PuttableSourceBase` sources (and `TestProcessor`, where it is also used like for sources).

As a simple way forward to fulfill the requirements of both use cases, this PR makes `PuttableProductResolver` to directly use the `Worker`'s `WaitingTaskList` in prefetching, if a `Worker` has been associated to the `PuttableProductResolver`. If no `Worker` has been associated, the `PuttableProductResolver` assumes it is from a Source (or similar), and the product is available for any consuming module without any further waiting in the prefetching. See also https://github.com/cms-sw/cmssw/pull/39245#issuecomment-1253916692 for some further discussion.

Resolves #39064 .

#### PR validation:

The reproducer I mentioned in https://github.com/cms-sw/cmssw/issues/39064#issuecomment-1228755900 succeeds with this change. Framework unit tests pass.

### CODE REVIEW

**Comment by makortel** [comment]
enable threading

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones Would you agree?

**Comment by Dr15Jones** [comment]
I'm not sure that works for the mixing module which doesn't (I think) do any prefetching.

File: FWCore/Framework/src/ProductResolvers.cc [hunk 1]
```diff
@@ -430,14 +430,6 @@ namespace edm {
     }
   }
 
-  void PuttableProductResolver::putProduct(std::unique_ptr<WrapperBase> edp) const {
-    ProducedProductResolver::putProduct(std::move(edp));
-    bool expected = false;
-    if (prefetchRequested_.compare_exchange_strong(expected, true)) {
-      m_waitingTasks.doneWaiting(std::exception_ptr());
```
Comment (Dr15Jones) [inline FWCore/Framework/src/ProductResolvers.cc:437]: The other `m_waitingTasks.doneWaiting` call requires that `worker_` not be `nullptr`. Is there any condition under which we do have it as `nullptr`?

**Comment by makortel** [comment]
Do you mean the `SecondaryEventProvider` that is being used by `PileUp`
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/Mixing/Base/src/PileUp.cc#L106-L109 that is being used by `BMixingModule`
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/Mixing/Base/interface/BMixingModule.h#L108-L109
?

On a first look `SecondaryEventProvider` sets up the workers as unscheduled
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/Mixing/Base/src/SecondaryEventProvider.cc#L51-L67

But maybe there is some hidden detail that deserves deeper look. Unfortunately this won't be caught by any tests as the functionality has been unused for some years (and `Mixing/Base` has no tests).

File: FWCore/Framework/src/ProductResolvers.cc (hunk 1 above)
Comment (makortel) [reply FWCore/Framework/src/ProductResolvers.cc:437]: The `worker_` is initially uninitialized (already which sort of defeats the purpose of the check...) and is set later by
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/FWCore/Framework/src/ProductResolvers.cc#L449-L451

The `setupUnscheduled()` is called by `Principal::setupUnscheduled()`
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/FWCore/Framework/src/Principal.cc#L398-L400
that is called by
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/FWCore/Framework/src/WorkerManager.cc#L141-L148

That in turn is called from `GlobalSchedule::processOneGlobalAsync()`
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/FWCore/Framework/interface/GlobalSchedule.h#L220-L222
, from `StreamSchedule::processOneEventAsync()`
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/FWCore/Framework/src/StreamSchedule.cc#L915
and from
https://github.com/cms-sw/cmssw/blob/3cac6aaba83c4b00b452f8fee244e5bccafc809b/Mixing/Base/src/SecondaryEventProvider.cc#L121-L127
(the `SecondaryEventProvider::setupPileUpEvent()` ends up being called from `PreMixingModule` and `DataMixingModule` once for each pileup event)

To me it seems the workers are being set for the ProductResolvers before anything gets run (although I wonder why the setup gets repeated), and I can't see why anything would call `putProduct()` without `worker_` being set (but I could be missing some corner case).

**Comment by makortel** [comment]
In addition, specifically HARVESTING step seems to get stuck (because of starvation of tasks in TBB)

**Comment by Dr15Jones** [comment]
@makortel maybe the code that transitions from one module on a path to the next module on a path is adding to the module proxy's WaitingTaskList and since it is not a 'consumes' relation your change will fail? That it, it requires the release of the WaitingTaskList on the `put` if no module 'consumes' that data and it only runs because it is on a Path?

**Comment by makortel** [comment]
This push changes completely to the approach to one I discussed with @Dr15Jones yesterday. There are two use cases for `PuttableProductResolver`
- `Worker` corresponding a module in Path: the tasks for consuming modules should be released only after the worker has finished
- `PuttableSourceBase` and `TestProcessor`: products are put in advance (like by a module that is implicitly the first one in every Path), and therefore consuming modules do not need to wait

Using the `Worker`'s `WaitingTaskList` (if available) was the simplest solution to fulfill both behaviors, and allowed to also simplify the code. 

I tried also creating a separate ProductResolver tupe for the Source-like use case, and that would have worked as well, but would have required to add a way to communicate in the `BranchDescription` whether this new ProductResolver should be used. Making this approach nice would have required improving the current logic of identifying `PuttableSourceBase` sources (currently "if module label is `source`"), which would need quite some effort.

**Comment by makortel** [comment]
@cmsbuild, please test

File: FWCore/Framework/src/ProductResolvers.h [hunk 2]
```diff
@@ -218,12 +218,12 @@ namespace edm {
                         ModuleCallingContext const* mcc) const override;
     bool unscheduledWasNotRun_() const override { return false; }
 
-    void putProduct(std::unique_ptr<WrapperBase> edp) const override;
-    void resetProductData_(bool deleteEarly) override;
-
-    CMS_THREAD_SAFE mutable WaitingTaskList m_waitingTasks;
-    Worker* worker_;
-    mutable std::atomic<bool> prefetchRequested_;
+    // The WaitingTaskList below is the one of the worker, if one
```
Comment (Dr15Jones) [inline FWCore/Framework/src/ProductResolvers.h:221]:
```suggestion
    // The WaitingTaskList below is the one from the worker, if one
```

File: FWCore/Framework/interface/maker/Worker.h [hunk 3]
```diff
@@ -241,6 +241,9 @@ namespace edm {
 
     virtual bool hasAccumulator() const = 0;
 
+    // Used in PuttableProductResolver
+    edm::WaitingTaskList* waitingTaskList() { return &waitingTasks_; }
```
Comment (Dr15Jones) [inline FWCore/Framework/interface/maker/Worker.h:245]: Given this can never return a null, maybe it would be better to return `edm::WaitingTaskList&`

File: FWCore/Framework/src/ProductResolvers.h (hunk 2 above)
Comment (makortel) [reply FWCore/Framework/src/ProductResolvers.h]: Thanks, done

File: FWCore/Framework/interface/maker/Worker.h (hunk 3 above)
Comment (makortel) [reply FWCore/Framework/interface/maker/Worker.h]: Thanks, done

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
type bug-fix

**Comment by perrotta** [comment]
+1
- Fully trusting the gurus who contributed to this PR
- PR tests pass successfully
