### PR TITLE
Use std::string_view for MessageLogger category

### LINKED ISSUE #31475: MessageLogger constructors should accept string_view
Currently, passing `std::string_view` when constructing e.g. `edm::LogInfo` produces the following errors:
```
error: no matching function for call to 'edm::LogInfo::LogInfo(std::string_view&)'

note: candidate: 'edm::LogInfo::LogInfo(const string&)'
     explicit LogInfo(std::string const& id)
```

This is because `std::string_view` can't be implicitly converted to `std::string`.

It would be useful to provide constructors for MessageLogger instances that accept `std::string_view`. In some cases, this would avoid extra string constructions.

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/31475. Should avoid one `std::string` construction when the category is passed in as `char const*`.

#### PR validation:

Framework unit tests pass.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

File: FWCore/MessageLogger/interface/ErrorObj.h [hunk 1]
```diff
@@ -45,7 +45,7 @@ namespace edm {
   public:
     // --- birth/death:
     //
-    ErrorObj(const ELseverityLevel& sev, const ELstring& id, bool verbatim = false);
+    ErrorObj(const ELseverityLevel& sev, std::string_view id, bool verbatim = false);
```
Comment (makortel) [inline FWCore/MessageLogger/interface/ErrorObj.h:48]: @Dr15Jones Given that `ELseverityLevel` is essentially an `int`, I wonder if we should pass it around by value instead of by reference?

Comment (Dr15Jones) [reply FWCore/MessageLogger/interface/ErrorObj.h:48]: Passing by value makes sense to me. (Much of the internals of MessageLogger are C++98 era of code)

**Comment by Dr15Jones** [comment]
Could you also go the extra mile and get rid of all references to `ELstring`? It is completely unnecessary as we already directly depend upon `std::string` in our interfaces.

**Comment by makortel** [comment]
> Could you also go the extra mile and get rid of all references to `ELstring`?

Happy to.

**Comment by kpedro88** [comment]
thanks @makortel!

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1
