### PR TITLE
check for empty collection in SiStripApproximateClusterCollection

### LINKED ISSUE #42746: Segmentation violation in SiStripApprox2Clusters
This issue was observed in Tier0 jobs for CommissioningRawPrime with the new release 13_2_3.

I reran with debug symbols to get a better stack trace:
```
#0  SiStripApproximateClusterCollection::DetSet::DetSet (detIndex=0, coll=0x7ffe96679ba8, this=<optimized out>)
    at /cvmfs/cms.cern.ch/el8_amd64_gcc11/external/gcc/11.4.1-30ebdc301ebd200f2ae0e3d880258e65/include/c++/11.4.1/bits/stl_vector.h:1061
#1  SiStripApproximateClusterCollection::const_iterator::operator* (this=<synthetic pointer>)
    at /cvmfs/cms.cern.ch/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_3/src/DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h:58
#2  SiStripApprox2Clusters::produce (this=<optimized out>, id=..., event=..., iSetup=...)
    at /uscms_data/d3/pedrok/phase2/orm/CMSSW_13_2_3/src/RecoLocalTracker/SiStripClusterizer/plugins/SiStripApprox2Clusters.cc:45
#3  0x00007ffff7ccf2db in edm::global::EDProducerBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) ()
   from /cvmfs/cms.cern.ch/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_3/lib/el8_amd64_gcc11/libFWCoreFramework.so
```

These code locations are:
https://github.com/cms-sw/cmssw/blob/CMSSW_13_2_3/RecoLocalTracker/SiStripClusterizer/plugins/SiStripApprox2Clusters.cc#L45
https://github.com/cms-sw/cmssw/blob/CMSSW_13_2_3/DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h#L58

Based on frame 0, this appears to be some problem with the content of the collection (the module is correctly configured and the collection is present in the input file contents).

The parameter set for one of the failing jobs can be found here: `/afs/cern.ch/user/c/cmst0/public/PausedJobs/HI2023/TestRun/job_488309/job/WMTaskSpace/cmsRun1`

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Attempts to resolve #42746.

#### PR validation:

Tested on the failing dataset and segmentation violations related to `SiStripApproximateClusterCollection` no longer occur. (Subsequent exceptions occur because this is a weird run with no tracker, but those are expected.)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

A backport branch for 13_2_X is prepared at https://github.com/kpedro88/cmssw/tree/HandleEmptyColl_132X, but a PR is not submitted yet, pending verification of the implemented solution by the experts.

attn: @jeongeun, @mmusich, @mandrenguyen

### CODE REVIEW

File: DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h [hunk 1]
```diff
@@ -43,9 +43,10 @@ class SiStripApproximateClusterCollection {
     DetSet(SiStripApproximateClusterCollection const* coll, unsigned int detIndex)
         : coll_(coll),
           detIndex_(detIndex),
-          clusBegin_(coll_->beginIndices_[detIndex]),
-          clusEnd_(detIndex == coll_->beginIndices_.size() - 1 ? coll->clusters_.size()
-                                                               : coll_->beginIndices_[detIndex + 1]) {}
+          clusBegin_(coll_->beginIndices_.empty() ? 0 : coll_->beginIndices_[detIndex]),
+          clusEnd_(coll_->beginIndices_.empty()                  ? 0
```
Comment (makortel) [inline DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h:47]: Using `coll->clusters_.size()` as the special index instead of `0` would give behavior that is closer to an empty `std::vector` (i.e. de-referencing the `DetSet::begin()` iterator is truly undefined behavior)

File: DQM/SiStripMonitorApproximateCluster/plugins/SiStripMonitorApproximateCluster.cc [hunk 2]
```diff
@@ -168,6 +168,10 @@ void SiStripMonitorApproximateCluster::analyze(const edm::Event& iEvent, const e
   const SiStripApproximateClusterCollection* clusterCollection = approx_cluster_detsetvector.product();
 
   for (const auto& detClusters : *clusterCollection) {
+    //check for empty set
+    if (detClusters.begin() == detClusters.end())
```
Comment (makortel) [inline DQM/SiStripMonitorApproximateCluster/plugins/SiStripMonitorApproximateCluster.cc:172]: I'd suggest to add `empty()` member function to make these checks more concise.

File: DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h (hunk 1 above)
Comment (kpedro88) [reply DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h:47]: I'm not sure I understand this comment; if `beginIndices_` is empty, then `clusters_.size()` is 0, so what's the difference?

Comment (makortel) [reply DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h:47]: Ah right, the case here is that the whole collection is empty? How does one get a valid `DetSet` proxy object then? Perhaps it would be better to change `SiStripApproximateClusterCollection::begin()` to return `end()` when the collection is empty?

Comment (kpedro88) [reply DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h]: That is indeed simpler and better. Updated the branch accordingly.

**Comment by mandrenguyen** [comment]
please test workflow 140.58, 140.6, 160.2

File: DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h [hunk 3]
```diff
@@ -90,7 +90,7 @@ class SiStripApproximateClusterCollection {
   void reserve(std::size_t dets, std::size_t clusters);
   Filler beginDet(unsigned int detId);
 
-  const_iterator begin() const { return const_iterator(this); }
+  const_iterator begin() const { return const_iterator(clusters_.empty() ? nullptr : this); }
```
Comment (makortel) [inline DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h:93]: To me
```suggestion
  const_iterator begin() const { return clusters_.empty() ? end() : const_iterator(this); }
```
would be clearer as then the reader would not need to check the behavior of the non-default `const_iterator` constructor to understand that in this special case `begin() == end()`.

**Comment by mandrenguyen** [comment]
+reconstruction
No change rawprime workflows. 
Diffs in comparisons must be spurious.

**Comment by kpedro88** [comment]
I think the spurious comparison differences are related to #39803 (mkfit).

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
urgent 
   * backport https://github.com/cms-sw/cmssw/pull/42776 needed for data-taking

**Comment by antoniovilela** [comment]
+1
