### PR TITLE
Modify L1TGlobal menu code and CondFormats to remove reinterpret_cast to and from utm firmware "es" types

### LINKED ISSUE #30819: Undefined behavior in TriggerMenuParser
The UBSAN IB is reporting the following problems in workflow 11834.24 (possibly also in others).

```
2300/src/L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:212:47: runtime error: member call on address 0x2b9a766a38c0 which does not point to an object of type 'esTriggerMenu'
0x2b9a766a38c0: note: object is of type 'L1TUtmTriggerMenu'
 00 00 00 00  b8 e2 92 21 9a 2b 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  e0 80 6b 76
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'L1TUtmTriggerMenu'
```

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/utm/utm_0.7.5-ghbfee2/include/tmEventSetup/esScale.hh:37:7: runtime error: member access within address 0x2b9a76688b00 which does not point to an object of type 'esScale'
0x2b9a76688b00: note: object is of type 'L1TUtmScale'
 00 00 00 00  98 e2 92 21 9a 2b 00 00  c0 3a 61 76 9a 2b 00 00  17 00 00 00 00 00 00 00  17 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'L1TUtmScale'
```

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/utm/utm_0.7.5-ghbfee2/include/tmEventSetup/esBin.hh:32:7: runtime error: member access within address 0x2b9a766cd800 which does not point to an object of type 'esBin'
0x2b9a766cd800: note: object is of type 'L1TUtmBin'
 00 00 00 00  18 e2 92 21 9a 2b 00 00  8d 00 00 00 00 00 00 00  00 00 00 00 00 00 14 c0  bc 74 93 18
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'L1TUtmBin'
```

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/utm/utm_0.7.5-ghbfee2/include/tmEventSetup/esAlgorithm.hh:33:7: runtime error: member access within address 0x2b9a7662b040 which does not point to an object of type 'esAlgorithm'
0x2b9a7662b040: note: object is of type 'L1TUtmAlgorithm'
 65 00 72 65  f8 e1 92 21 9a 2b 00 00  58 b0 62 76 9a 2b 00 00  0d 00 00 00 00 00 00 00  4c 31 5f 41
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'L1TUtmAlgorithm'
```

All these problems stem from here:
https://github.com/cms-sw/cmssw/blob/4c0913fabe8081975cee9b0683d6906338a7da3f/L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc#L157

https://github.com/cms-sw/cmssw/blob/4c0913fabe8081975cee9b0683d6906338a7da3f/L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc#L209

Such a cast is very much undefined behavior, doubly so since we are dealing with classes with virtual functions.

I see two possible ways of dealing with this

1. copy the contents in the L1TUtmTriggerMenu to a esTriggerMenu. This could be done in the module or in an ESProducer
1. modify all functions that take `tmeventsetup::` objects to be templated so they can work properly with `L1TUtm*` objects as well.

### PR DESCRIPTION
**Pull request by aloeliger**
### PR description:

This PR changes L1TGlobal code and CondFormats to remove three instances of `reinterpret_cast` (one in `L1TUtmTriggerMenuESProducer`, and two in `TriggerMenuParser`) that were attempting to reinterpret pointers of [utm Trigger Menu code/objects](https://gitlab.cern.ch/arnold/utm) to CMSSW `L1TUtm` objects (with undefined behavior). To achieve this, constructors were added to equivalent `L1TUtm` objects that can accept firmware `utm/es` objects and create exact (or at the least, more _defined_) copies by copying values. These `L1TUtm` objects should now be used with preference in CMSSW and across L1TGlobal code.

This code _**should not**_ produce any change in global trigger results. Any change in trigger results is incorrect and should not be merged.

These changes were requested in review of https://github.com/cms-sw/cmsdist/pull/8352 and may address an issue seen in the testing of that PR. Regardless of whether it fixes that issue, these changes were requested.

These changes should in theory close https://github.com/cms-sw/cmssw/issues/30819

@elfontan I figured you might like to be kept apprised of these changes.

### PR validation:

All code compiles, and passes all unit tests, with special attention paid to the `testL1TGlobalProducer`, which produces identical results. Run the matrix seems to produce reasonable output. I have also confirmed (using print statements) that the now copied-by-value `L1TUtmTriggerMenu` members should be entirely identical to the `L1TUtmTriggerMenu` produced previously by `reinterpret_cast`

### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport. This PR may need to be backported to 13_0 to match the corresponding utm firmware update backport, if this PR solves the issue seen in https://github.com/cms-sw/cmsdist/pull/8352. @epalencia may be able to clarify if that is necessary.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by arnobaer** [comment]
@aloeliger n.b. duplicating `tmeventsetup` functions `getPrecision` and `getLut` and `getDeltaVector` might create a lot of extra work as these functions are not only used by emulator but also for firmware genaration and for offlinerate studies outside the scope of CMSSW. It would argue taht it would be better to use the functions provided by tmEventSetup.hh (changes to utm require frequent changes in these functions too).

**Comment by aloeliger** [comment]
@arnobaer Yeah, that's the conclusion I came to unfortunately. Perhaps in the future we should discuss the addition of member setters in the respective `L1TUtm` and `es` objects (unless there is some code best practices as to why these things should be almost completely un-settable, they didn't even have constructor facing set options before I wrote them in...) that would allow a more seamless translation between the two, and allow some of the helping functions to remain synchronized and entirely in the `utm` code.

**Comment by arnobaer** [comment]
@aloeliger the duplicated functions are not up to date with the current utm_0.11.x release. This might result in differnt behaviour of the emulator. See https://gitlab.cern.ch/cms-l1t-utm/utm/-/blob/utm_0.11.1/tmEventSetup/tmEventSetup.cc

**Comment by aloeliger** [comment]
@arnobaer Okay. I'll take a look at it when I fix the compilation error. Strange that that's happening, it compiles when I try it.

**Comment by smuzaffar** [comment]
looks like https://github.com/cms-sw/cmssw/blob/master/DQM/CastorMonitor/interface/CastorMonitorModule.h#L17 ( `#include "L1Trigger/L1TGlobal/interface/L1TGlobalUtil.h"` ) is not needed. This include need `utm` dependency in `DQM/CastorMonitor` . So either cleanup the include statement or add `utm` dependency in `DQM/CastorMonitor/BuildFile.xml`

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/blob/master/DQM/CastorMonitor/interface/CastorMonitorModule.h#L101 can also go away

**Comment by aloeliger** [comment]
please test

**Comment by emanueleusai** [comment]
type l1t

**Comment by emanueleusai** [comment]
+1

- differences in EGammaV unrelated to this PR

File: CondFormats/L1TObjects/interface/L1TUtmAlgorithm.h [hunk 1]
```diff
@@ -29,6 +30,34 @@ class L1TUtmAlgorithm {
...
+  L1TUtmAlgorithm(tmeventsetup::esAlgorithm esAlg)
+      : L1TUtmAlgorithm(
+            esAlg.getName(),
+            esAlg.getExpression(),
+            esAlg.getExpressionInCondition(),
+            esAlg.getRpnVector(),
+            esAlg.getIndex(),
+            esAlg.getModuleId(),
+            esAlg.getModuleIndex(),
+            0  //There is no version retrieval in esAlgorithm. However, it seems pretty hard coded to 0 TODO: check this.
```
Comment (tvami) [inline CondFormats/L1TObjects/interface/L1TUtmAlgorithm.h:59]: is this still to be checked?

File: CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h [hunk 2]
```diff
@@ -38,6 +40,53 @@ class L1TUtmTriggerMenu {
         scale_set_name_(),
         n_modules_(),
         version(0){};
+  L1TUtmTriggerMenu(std::map<std::string, L1TUtmAlgorithm> algorithm_map,
+                    std::map<std::string, L1TUtmCondition> condition_map,
+                    std::map<std::string, L1TUtmScale> scale_map,
+                    //std::map<std::string, unsigned int> external_map,
+                    //std::map<std::string, std::string> token_to_condition,
```
Comment (tvami) [inline CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h:47]: Please remove commented out code

File: CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h [hunk 3]
```diff
@@ -38,6 +40,53 @@ class L1TUtmTriggerMenu {
...
+                    std::string comment,
+                    std::string datetime,
+                    std::string uuid_firmware,
+                    std::string scale_set_name,
+                    unsigned int n_modules,
+                    unsigned int ver_i)
+      : algorithm_map_(algorithm_map),
+        condition_map_(condition_map),
+        scale_map_(scale_map),
+        //external_map_(external_map),
```
Comment (tvami) [inline CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h:59]: please remove

File: CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h [hunk 4]
```diff
@@ -38,6 +40,53 @@ class L1TUtmTriggerMenu {
...
+        external_map_(),
+        //token_to_condition_(token_to_condition),
```
Comment (tvami) [inline CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h:61]: please remove

File: CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h [hunk 5]
```diff
@@ -38,6 +40,53 @@ class L1TUtmTriggerMenu {
...
+        token_to_condition_(),  //These are null to my best knowledge
+        name_(esMenu.getName()),
+        version_(esMenu.getVersion()),
+        comment_(esMenu.getComment()),
+        datetime_(esMenu.getDatetime()),
+        uuid_firmware_(esMenu.getFirmwareUuid()),
+        scale_set_name_(esMenu.getScaleSetName()),
+        n_modules_(esMenu.getNmodules()),
+        version(0) {
+    for (auto it = esMenu.getAlgorithmMap().begin(); it != esMenu.getAlgorithmMap().end(); ++it)
```
Comment (tvami) [inline CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h:83]: could these be range based loops?

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc [hunk 6]
```diff
@@ -44,13 +44,23 @@
...
 #include "tmEventSetup/tmEventSetup.hh"
+#include "tmEventSetup/esTypes.hh"
+/*
 #include "tmEventSetup/esTriggerMenu.hh"
 #include "tmEventSetup/esAlgorithm.hh"
 #include "tmEventSetup/esCondition.hh"
 #include "tmEventSetup/esObject.hh"
 #include "tmEventSetup/esCut.hh"
 #include "tmEventSetup/esScale.hh"
+ */
```
Comment (tvami) [inline L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:55]: Can this be removed?

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc [hunk 7]
```diff
@@ -172,7 +182,30 @@ void l1t::TriggerMenuParser::setGtAlgorithmAliasMap(const AlgorithmMap& algoMap)
 
 std::map<std::string, unsigned int> l1t::TriggerMenuParser::getExternalSignals(const L1TUtmTriggerMenu* utmMenu) {
   using namespace tmeventsetup;
-  const esTriggerMenu* menu = reinterpret_cast<const esTriggerMenu*>(utmMenu);
+  const std::map<std::string, L1TUtmCondition>& condMap = utmMenu->getConditionMap();
+
+  std::map<std::string, unsigned int> extBitMap;
+
+  //loop over the algorithms
+  for (std::map<std::string, L1TUtmCondition>::const_iterator cit = condMap.begin(); cit != condMap.end(); cit++) {
```
Comment (tvami) [inline L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:190]: please make this a range based loop

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc [hunk 8]
```diff
@@ -172,7 +182,30 @@ void l1t::TriggerMenuParser::setGtAlgorithmAliasMap(const AlgorithmMap& algoMap)
...
+    const L1TUtmCondition& condition = cit->second;
+    if (condition.getType() == esConditionType::Externals) {
+      // Get object for External conditions
+      const std::vector<L1TUtmObject>& objects = condition.getObjects();
+      for (size_t jj = 0; jj < objects.size(); jj++) {
```
Comment (tvami) [inline L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:195]: same comment about range based loop

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc [hunk 9]
```diff
@@ -172,7 +182,30 @@ void l1t::TriggerMenuParser::setGtAlgorithmAliasMap(const AlgorithmMap& algoMap)
...
+          std::string name = object.getExternalSignalName();
+
+          if (extBitMap.count(name) == 0)
+            extBitMap.insert(std::map<std::string, unsigned int>::value_type(name, channelID));
+        }
+      }
+    }
+  }
+
+  /*   const esTriggerMenu* menu = reinterpret_cast<const esTriggerMenu*>(utmMenu);
```
Comment (tvami) [inline L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:208]: please delete commented code, or give some explanation why it's still there

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc [hunk 10]
```diff
@@ -226,31 +259,31 @@ void l1t::TriggerMenuParser::parseCondFormats(const L1TUtmTriggerMenu* utmMenu)
   using namespace tmeventsetup;
   using namespace Algorithm;
 
-  const esTriggerMenu* menu = reinterpret_cast<const esTriggerMenu*>(utmMenu);
+  //const esTriggerMenu* menu = reinterpret_cast<const esTriggerMenu*>(utmMenu);
```
Comment (tvami) [inline L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:262]: remove commented code

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc [hunk 11]
```diff
@@ -226,31 +259,31 @@ void l1t::TriggerMenuParser::parseCondFormats(const L1TUtmTriggerMenu* utmMenu)
...
+  const std::map<std::string, L1TUtmScale>& scaleMap = utmMenu->getScaleMap();
 
   // parse the scales
-  m_gtScales.setScalesName(menu->getScaleSetName());
+  m_gtScales.setScalesName(utmMenu->getScaleSetName());
   parseScales(scaleMap);
 
   //loop over the algorithms
-  for (std::map<std::string, esAlgorithm>::const_iterator cit = algoMap.begin(); cit != algoMap.end(); cit++) {
+  for (std::map<std::string, L1TUtmAlgorithm>::const_iterator cit = algoMap.begin(); cit != algoMap.end(); cit++) {
```
Comment (tvami) [inline L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:281]: range based loop?

**Review by tvami — COMMENTED** [review]
I commented at some file directly, but please apply the comments to all files in the PR
 * commented out code should be deleted or explained why it's still included (in the code)
 * try to use range based for loops

**Comment by aloeliger** [comment]
Update: as of PR https://github.com/cms-sw/cmsdist/pull/8375 this _may_ not be necessary to integrate the new utm firmware, but it is likely still a good idea to clean the reinterpret casting.

File: CondFormats/L1TObjects/interface/L1TUtmAlgorithm.h (hunk 1 above)
Comment (aloeliger) [reply CondFormats/L1TObjects/interface/L1TUtmAlgorithm.h:59]: No, the utm firmware pretty universally does not use this value and just sets it to zero, there is really nothing to be checked, it doesn't seem to affect anything.

Comment (aloeliger) [reply CondFormats/L1TObjects/interface/L1TUtmAlgorithm.h:59]: The comment will be removed.

File: CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h (hunk 2 above)
Comment (aloeliger) [reply CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h:47]: This will be removed in the next update

File: CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h (hunk 3 above)
Comment (aloeliger) [reply CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h:59]: Removed

File: CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h (hunk 4 above)
Comment (aloeliger) [reply CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h:61]: Removed

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc (hunk 9 above)
Comment (aloeliger) [reply L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:208]: This has been removed in the next update

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc (hunk 10 above)
Comment (aloeliger) [reply L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:262]: Removed in the next update

File: CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h (hunk 5 above)
Comment (aloeliger) [reply CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h:83]: These have been adjusted to range based loops in the next updates

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc (hunk 7 above)
Comment (aloeliger) [reply L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:190]: This will be done in the next update

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc (hunk 8 above)
Comment (aloeliger) [reply L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:195]: This will be adjusted in the next update

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc (hunk 11 above)
Comment (aloeliger) [reply L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:281]: This will be applied in the next update

**Comment by aloeliger** [comment]
please test

**Comment by arnobaer** [comment]
@aloeliger to get rid of the duplicated functions (i.e. `getLut()`) I would propose the following. By adding an overloaded constructor to `tmeventsetup::esScale` it would be possible to implement conversion functions in `L1TUtmBin` and `L1TUtmScale` e.g.
```cpp
class L1TUtmBin {
    ...
    operator tmeventsetup::esBin() {
        return tmeventsetup::esBin(hw_index, minimum, maximum);
    }
};
class L1TUtmScale {
    ...
    operator tmeventsetup::esScale()
    {
        std::vector<tmeventsetup::esBin> bins;
        std::transform(std::begin(getBins()), std::end(getBins()), std::begin(bins), [](const L1TUtmBin& bin) { return bin; });
        return tmeventsetup::esScale(getName(), getObjectType(), getScaleType(), getMinimum(), getMaximum(), getStep(), bins);
    }
};
```
I assume this would require only minimal changes in the existing code. I can provide another utm patch tomorrow with the overloaded constructor for `tmeventsetup::esScale`.

**Comment by tvami** [comment]
+1
 * PR according to the description + follow-up review
 * tests pass (including relevant unit tests)

**Comment by emanueleusai** [comment]
+1

- differences in EGammaV unrelated to this PR

**Comment by aloeliger** [comment]
@arnobaer It would take relatively minimal changes to this CMSSW code, but it would require getting utm v0.12.0 (v0.11.2?) into the externals, then into an IB before I could test changes in CMSSW. I suppose we should get things done right rather than fast, so if you are willing to make this change, please notify me when it is available and I will update this PR.

**Comment by arnobaer** [comment]
@aloeliger I released patch 0.11.2 adding an overloaded constructor to `tmeventsetup::esScale`, see https://gitlab.cern.ch/cms-l1t-utm/utm/-/tree/utm_0.11.2

Taking into account the above proposed custom conversion functions for classes `L1TUtmScale` and `L1TUtmBin` it should require only to replace vector `scaleMap` to make use of the LUT functions provided by namespace `tmeventsetup`.
```cpp
// const std::map<std::string, L1TUtmScale>& scaleMap = menu->getScaleMap(); // replace by...
const std::map<std::string, tmeventsetup::esScale> scaleMap(std::begin(menu->getScaleMap()), std::end(menu->getScaleMap()));
```

**Comment by aloeliger** [comment]
Sorry for pinging you all again everyone. Should hopefully be the last update?

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
Well so much for that hope. Okay, let me test this.

**Comment by aloeliger** [comment]
:man_facepalming:

**Comment by aloeliger** [comment]
please test

**Comment by tvami** [comment]
hi @aloeliger would you please squash the commits (or at least some of them that made little changes)?

**Comment by tvami** [comment]
> hi @aloeliger would you please squash the commits (or at least some of them that made little changes)?

@aloeliger let me resurface my comment from above

**Comment by aloeliger** [comment]
Sure, just let me take a minute to get it correct.

**Comment by tvami** [comment]
+1
 * PR according to the description 
 * tests pass
 * last change is just a squashing

**Comment by aloeliger** [comment]
Unit tests failures seem unrelated to the changes here. And the squashing should not have changed whether unit tests pass or not. Failures are likely related to https://github.com/cms-sw/cmssw/pull/41075 and should hopefully be fixed by #41116

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/41116

**Comment by aloeliger** [comment]
Right, I always forget about that command. Thank you.

**Comment by aloeliger** [comment]
+l1

I don't know if I should be signing my own PRs, but it passes all menu unit tests, and no difference in trigger results is seen.

**Comment by emanueleusai** [comment]
+1

File: L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc [hunk 12]
```diff
@@ -44,13 +44,16 @@
 #include "FWCore/MessageLogger/interface/MessageDrop.h"
 
 #include "tmEventSetup/tmEventSetup.hh"
-#include "tmEventSetup/esTriggerMenu.hh"
-#include "tmEventSetup/esAlgorithm.hh"
-#include "tmEventSetup/esCondition.hh"
-#include "tmEventSetup/esObject.hh"
-#include "tmEventSetup/esCut.hh"
-#include "tmEventSetup/esScale.hh"
+#include "tmEventSetup/esTypes.hh"
```
[the remark this answers is not in the document]
Comment (aloeliger) [reply L1Trigger/L1TGlobal/plugins/TriggerMenuParser.cc:47]: @perrotta I believe so, there are a number of `enum` types used in the code that I didn't want to change: https://gitlab.cern.ch/cms-l1t-utm/utm/-/blob/master/tmEventSetup/include/utm/tmEventSetup/esTypes.hh

**Comment by perrotta** [comment]
+1

**Comment by elfontan** [comment]
Hello @aloeliger,
I just realized for some merging conflicts in the TriggerMenuParser when trying to cherry-pick some other uGT emulator changes to 130X that at the end this PR was not backported to 13_0_X. Could you (and @epalencia) clarify if this is not needed at all for the 130X CMSSW release that will be used for the data-taking with the new utm?
Thank you in advance!

Cheers,
--Elisa

**Comment by aloeliger** [comment]
@elfontan nothing in here should be necessary for data-taking and back-porting, this is just a fix going forward. If, for whatever reason, the undefined utm behavior breaks in production, we could back-port this. It shouldn't be necessary though. It can work on all utm versions v0.11.2 and forward.
