### PR TITLE
Avoid releasing WaitingTask too early in case of exception in WaitingThreadPool

### LINKED ISSUE #945: Avoid releasing WaitingTask too early in case of exception in WaitingThreadPool

### LINKED ISSUE #45194: testFWCoreConcurrencyCatch2 failing in MULTIARCH_X, ROOT632_X, ROOT6_X
In CMSSW_14_1_{MULTIARCH_X, ROOT632_X, ROOT6_X}, test testFWCoreConcurrencyCatch2 [is failing](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ROOT632_X_2024-06-10-2300/unitTestLogs/FWCore/Concurrency#/1300-1300):

```
src/FWCore/Concurrency/test/test_catch2_WaitingThreadPool.cc:118: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal
```

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/45194 . See https://github.com/cms-sw/cmssw/issues/45194#issuecomment-2214418256 for longer description.

Resolves https://github.com/cms-sw/framework-team/issues/945

#### PR validation:

Unit tests run.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 14_0_X (because https://github.com/cms-sw/cmssw/pull/44901 was).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones Could you cross check?

File: FWCore/Concurrency/interface/WaitingTaskWithArenaHolder.h [hunk 1]
```diff
@@ -60,6 +60,12 @@ namespace edm {
     // the task. doneWaiting can be called from a non-TBB thread.
     void doneWaiting(std::exception_ptr iExcept);
 
+    // Use in the case where you need to inform the parent task of a
+    // failure before some other child task which may be run later
+    // reports a different, but related failure. You must later call
+    // doneWaiting in the same thread passing the same exceptoin.
```
Comment (Dr15Jones) [inline FWCore/Concurrency/interface/WaitingTaskWithArenaHolder.h:66]:
```suggestion
    // doneWaiting in the same thread passing the same exception.
```

**Review by Dr15Jones — CHANGES_REQUESTED** [review]

**Comment by makortel** [comment]
@cmsbuild, please abort

File: FWCore/Concurrency/interface/WaitingTaskWithArenaHolder.h (hunk 1 above)
Comment (makortel) [reply FWCore/Concurrency/interface/WaitingTaskWithArenaHolder.h]: Thanks, fixed (also the original where I copied the comment from)

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Unit test failure occurs in IBs and is reported in https://github.com/cms-sw/cmssw/pull/44603#issuecomment-2211054260

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1
