### PR TITLE
XrdAdaptor: Use inactive sources first before trying to open a new source when handling a failed request

### LINKED ISSUE #1306: Use inactive sources first before trying to open a new source when handling a failed request
### Description

Following https://github.com/cms-sw/cmssw/issues/46086#issuecomment-2683002208

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

In the context of https://github.com/cms-sw/cmssw/issues/43162 and https://github.com/cms-sw/cmssw/issues/46086#issuecomment-2683002208, this PR changes the XrdAdaptor behavior for request failures. Previously, after disabling the source that resulted the request failure, it passed on the request to another active source, and if there were no active sources, it tried to open a new source. This PR changes to logic to
* Pass request to another active source
* If there are no active sources, pass the request to the best inactive source
* If there are no active or inactive sources, try to open a new source

The first commit generalizes the code where the failed source is removed from the active sources container. I found it confusing that the code checked only the first 2 active sources (even if there would only ever be at most 2 active sources). Admittedly, if there would be more than 2 active sources, the commit would change the behavior, but I would argue for the better.

Resolves https://github.com/cms-sw/framework-team/issues/1306

#### PR validation:

Code compiles.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Possibly to be backported to 15_0_X.

### CODE REVIEW

File: Utilities/XrdAdaptor/src/XrdRequestManager.cc [hunk 1]
```diff
@@ -839,17 +839,38 @@ void RequestManager::requestFailure(std::shared_ptr<XrdAdaptor::ClientRequest> c
...
+  //   new connection for a new source
   std::shared_ptr<Source> new_source;
-  if (m_activeSources.empty()) {
+  if (not m_activeSources.empty()) {
+    new_source = m_activeSources[0];
+  } else if (not m_inactiveSources.empty()) {
+    // similar logic as in checkSourcesImpl()
+    // assume the "sort open delay" doesn't matter in case of a request failure
+    auto bestInactiveSource =
+        std::min_element(m_inactiveSources.begin(),
```
Comment (ArturAkh) [inline Utilities/XrdAdaptor/src/XrdRequestManager.cc:863]: Is the best quality really the lowest number?

**Comment by makortel** [comment]
FYI @osschar

File: Utilities/XrdAdaptor/src/XrdRequestManager.cc (hunk 1 above)
Comment (makortel) [reply Utilities/XrdAdaptor/src/XrdRequestManager.cc:863]: As far as I can tell, yes. See e.g. existing code
https://github.com/cms-sw/cmssw/blob/eb45085aa953e72e9b379bb0b543a2897998809e/Utilities/XrdAdaptor/src/XrdRequestManager.cc#L455-L460

There is some discussion about the quality metric in https://github.com/cms-sw/cmssw/blob/master/Utilities/XrdAdaptor/doc/multisource_algorithm_design.txt
and _maybe_ it is computed in https://github.com/cms-sw/cmssw/blob/master/Utilities/XrdAdaptor/src/QualityMetric.cc, but I haven't tried to understand what is done there.

Comment (ArturAkh) [reply Utilities/XrdAdaptor/src/XrdRequestManager.cc:863]: OK, thanks, sounds good! :+1:

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
With @bockjoo's test https://github.com/cms-sw/cmssw/issues/43162#issuecomment-2724627647 the present state of this PR results in the following actions with sources (with increased verbosity of XrdAdaptor printouts with
```py
process.MessageLogger.cerr.threshold = "INFO"
process.MessageLogger.cerr.XrdAdaptorInternal = dict()
process.MessageLogger.cerr.XrdAdaptorLvl1 = dict()
process.MessageLogger.cerr.XrdAdaptorLvl3 = dict()
```
)
```
%MSG-i XrdAdaptorInternal:  file_open 14-Mar-2025 15:28:27 CET pre-events
Reading from new server ceph-gw10.gridpp.rl.ac.uk:1094 at site T1_UK_RAL
%MSG
%MSG-i XrdAdaptorLvl1:  file_open 14-Mar-2025 15:28:27 CET pre-events
Serving data from:    [1] ceph-gw10.gridpp.rl.ac.uk
%MSG

%MSG-i XrdAdaptorLvl3:  AfterFile 14-Mar-2025 15:28:46 CET pre-events
Looking for an additional source because the number of active sources is smaller than 2
%MSG
Trying to open URL: root://xrootd-cms.infn.it//store/data/Run2024D/ParkingDoubleMuonLowMass3/RAW/v1/000/380/564/00000/d2acc894-3939-4155-93e6-403117e74b6c.root?tried=ceph-gw10.gridpp.rl.ac.uk&triedrc=resel

%MSG-i XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 15:28:47 CET pre-events
Reading from new server ceph-svc20.gridpp.rl.ac.uk:1094 at site T1_UK_RAL
%MSG
Successfully opened new source: ceph-svc20.gridpp.rl.ac.uk:1094 (site T1_UK_RAL)
%MSG-i XrdAdaptorLvl1:  (NoModuleName) 14-Mar-2025 15:28:47 CET pre-events
Serving data from:    [1] ceph-gw10.gridpp.rl.ac.uk   [2] ceph-svc20.gridpp.rl.ac.uk
%MSG

%MSG-w XrdAdaptorLvl3:  AfterFile 14-Mar-2025 15:28:48 CET pre-events
Deactivating ceph-gw10.gridpp.rl.ac.uk from active sources because its quality (1869) is higher than 260 and 4 times larger than the other active server ceph-svc20.gridpp.rl.ac.uk (260)
%MSG
Removing ceph-gw10.gridpp.rl.ac.uk from active sources due to poor quality (1869 vs 260)
%MSG-i XrdAdaptorLvl1:  AfterFile 14-Mar-2025 15:28:48 CET pre-events
Serving data from:    [1] ceph-svc20.gridpp.rl.ac.uk
%MSG

%MSG-i XrdAdaptorLvl3:  AfterFile 14-Mar-2025 15:30:28 CET pre-events
Looking for an additional source because the number of active sources is smaller than 2
%MSG
Trying to open URL: root://xrootd-cms.infn.it//store/data/Run2024D/ParkingDoubleMuonLowMass3/RAW/v1/000/380/564/00000/d2acc894-3939-4155-93e6-403117e74b6c.root?tried=ceph-svc20.gridpp.rl.ac.uk,ceph-gw10.gridpp.rl.ac.uk&triedrc=resel

%MSG-i XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 15:30:30 CET pre-events
Reading from new server ceph-gw11.gridpp.rl.ac.uk:1094 at site T1_UK_RAL
%MSG
Successfully opened new source: ceph-gw11.gridpp.rl.ac.uk:1094 (site T1_UK_RAL)
%MSG-i XrdAdaptorLvl1:  (NoModuleName) 14-Mar-2025 15:30:30 CET pre-events
Serving data from:    [1] ceph-svc20.gridpp.rl.ac.uk   [2] ceph-gw11.gridpp.rl.ac.uk
%MSG

%MSG-w XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 15:33:43 CET pre-events
XrdRequestManager::handle(name='root://xrootd-cms.infn.it//store/data/Run2024D/ParkingDoubleMuonLowMass3/RAW/v1/000/380/564/00000/d2acc894-3939-4155-93e6-403117e74b6c.root) failure when reading from ceph-svc20.gridpp.rl.ac.uk:1094 (site T1_UK_RAL); failed with error '[ERROR] Operation expired' (errno=0, code=206).
%MSG
%MSG-w XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 15:33:43 CET pre-events
Request failure when reading from ceph-svc20.gridpp.rl.ac.uk:1094 (site T1_UK_RAL)
%MSG
%MSG-i XrdAdaptorLvl1:  (NoModuleName) 14-Mar-2025 15:33:43 CET pre-events
Serving data from:    [1] ceph-gw11.gridpp.rl.ac.uk
%MSG

%MSG-w XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 15:57:58 CET pre-events
XrdRequestManager::handle(name='root://xrootd-cms.infn.it//store/data/Run2024D/ParkingDoubleMuonLowMass3/RAW/v1/000/380/564/00000/d2acc894-3939-4155-93e6-403117e74b6c.root) failure when reading from ceph-gw11.gridpp.rl.ac.uk:1094 (site T1_UK_RAL); failed with error '[ERROR] Operation expired' (errno=0, code=206).
%MSG
%MSG-w XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 15:57:58 CET pre-events
Request failure when reading from ceph-gw11.gridpp.rl.ac.uk:1094 (site T1_UK_RAL)
%MSG
%MSG-i XrdAdaptorLvl1:  (NoModuleName) 14-Mar-2025 15:57:58 CET pre-events
Serving data from:
%MSG

%MSG-i XrdAdaptorLvl1:  (NoModuleName) 14-Mar-2025 15:57:58 CET pre-events
Serving data from:    [1] ceph-gw10.gridpp.rl.ac.uk
%MSG

%MSG-w XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 16:06:40 CET pre-events
XrdRequestManager::handle(name='root://xrootd-cms.infn.it//store/data/Run2024D/ParkingDoubleMuonLowMass3/RAW/v1/000/380/564/00000/d2acc894-3939-4155-93e6-403117e74b6c.root) failure when reading from ceph-gw10.gridpp.rl.ac.uk:1094 (site T1_UK_RAL); failed with error '[ERROR] Operation expired' (errno=0, code=206).
%MSG
%MSG-w XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 16:06:40 CET pre-events
Request failure when reading from ceph-gw10.gridpp.rl.ac.uk:1094 (site T1_UK_RAL)
%MSG
%MSG-i XrdAdaptorLvl1:  (NoModuleName) 14-Mar-2025 16:06:40 CET pre-events
Serving data from:
%MSG

Trying to open URL: root://xrootd-cms.infn.it//store/data/Run2024D/ParkingDoubleMuonLowMass3/RAW/v1/000/380/564/00000/d2acc894-3939-4155-93e6-403117e74b6c.root?tried=ceph-svc20.gridpp.rl.ac.uk,ceph-gw11.gridpp.rl.ac.uk,ceph-gw10.gridpp.rl.ac.uk
[2025-03-14 16:09:36.079737 +0100][Error  ][XRootD            ] [cms-xrd-global.cern.ch:1094] Unable to get the response to request kXR_open (file: /store/data/Run2024D/ParkingDoubleMuonLowMass3/RAW/v1/000/380/564/00000/d2acc894-3939-4155-93e6-403117e74b6c.root?tried=+1213llrxrd-redir.in2p3.fr,+1213xrootd-redic.pi.infn.it,+1213xrootd011213xrootd-cms-uk.gridpp.r>
Got failure when trying to open a new source
%MSG-w XrdAdaptorInternal:  (NoModuleName) 14-Mar-2025 16:09:36 CET pre-events
Caught a CMSSW exception when running connection recovery.
%MSG
----- Begin Fatal Exception 14-Mar-2025 16:09:36 CET-----------------------
An exception of category 'FileReadError' occurred while
   [0] Calling InputSource::getNextItemType
   [1] Reading branch EventAuxiliary
   [2] Calling XrdFile::readv()
   [3] XrdAdaptor::ClientRequest::HandleResponse() failure while running connection recovery
   [4] Handling XrdAdaptor::RequestManager::requestFailure()
   [5] In XrdAdaptor::RequestManager::OpenHandler::HandleResponseWithHosts()
Exception Message:
XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/data/Run2024D/ParkingDoubleMuonLowMass3/RAW/v1/000/380/564/00000/d2acc894-3939-4155-93e6-403117e74b6c.root', flags=0x10, permissions=0660) => error '[ERROR] Operation expired' (errno=0, code=206)
   Additional Info:
      [a] Original error: '[ERROR] Operation expired' (errno=0, code=206, source=ceph-gw10.gridpp.rl.ac.uk:1094 (site T1_UK_RAL)).
      [b] Original failed source is ceph-gw10.gridpp.rl.ac.uk:1094 (site T1_UK_RAL)
      [c] Disabled source: ceph-gw10.gridpp.rl.ac.uk:1094
      [d] Disabled source: ceph-gw11.gridpp.rl.ac.uk:1094
      [e] Disabled source: ceph-svc20.gridpp.rl.ac.uk:1094
----- End Fatal Exception -------------------------------------------------
```

**Comment by makortel** [comment]
To summarize https://github.com/cms-sw/cmssw/pull/47593#issuecomment-2725107965
* Open initial source `ceph-gw10.gridpp.rl.ac.uk`
* Multi-source scanning opens a second source `ceph-svc20.gridpp.rl.ac.uk`
* `ceph-gw10.gridpp.rl.ac.uk` is deactivated because of its quality
* Multi-source scanning opens a third source `ceph-gw11.gridpp.rl.ac.uk`
* Read request from `ceph-svc20.gridpp.rl.ac.uk` fails, and the source is disabled
* Read request from `ceph-gw11.gridpp.rl.ac.uk` fails, and the source is disabled
* Inactive source `ceph-gw10.gridpp.rl.ac.uk` is "promoted" to active (the `Serving data from` printout at `15:57:58`)
* Read request from `ceph-gw10.gridpp.rl.ac.uk` fails, and the source is disabled
* Attempt to open a new source fails, and the job is terminated

At least this private test demonstrates the code in this PR has an impact.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Hi @bbockelm @dynamic-entropy @osschar, could you please take a look?

**Review by bbockelm — APPROVED** [review]
@makortel -

Rahul and I took a look over this during a Zoom call.  I'd consider this a quite good bugfix -- it was never the intent to ignore inactive sources on retry.  Logic looks correct and I'm happy with it considering the tests are all passing.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1
