### PR TITLE
btvNano: add abort condition for genParticle mother search

### LINKED ISSUE #49703: Major failure for UL v15 BTVNano remini-ReNano from mini v2 MC production
Recently we have to witnessed a big bunch of MC production workflow failed entirely. Those workflows are UL v15 BTVNano produced via remini-ReNano from mini.

The failures, from the production condor log, are related to https://github.com/cms-sw/cmssw/blob/CMSSW_15_0_17/PhysicsTools/NanoAOD/plugins/GenCandMotherTableProducer.cc

Requests from https://gitlab.cern.ch/cms-gen/mccm/-/issues/1009 will be aborted.

Detailed errors could be retrieved from Unified Logs from relevant workflows, for example

- https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BTV-RunIISummer20UL16NanoAODv15-00032
- https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_SUS-RunIISummer20UL16NanoAODv15-00060

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

- Fixes https://github.com/cms-sw/cmssw/issues/49703 by adding abort condition when no mothers are found anymore (this was not the case for the ttbar samples that I tested with)
- Added unit test for one of the problematic samples (DY)

#### PR validation:

```
Pass    6s ... PhysicsTools/NanoAOD/testPhysicsToolsNanoAODTP
Pass   76s ... PhysicsTools/NanoAOD/test-btvNano-run
Pass    5s ... PhysicsTools/NanoAOD/test-btvNano-check
Pass  106s ... PhysicsTools/NanoAOD/test-btvNano-runDY
>> Test sequence completed for CMSSW CMSSW_16_0_0_pre4
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

- Need backport to 15_0 for Nano v15 production (and 15_1 in case there is a Nano v16)

### CODE REVIEW

**Comment by ftorrresd** [comment]
enable nano

**Comment by ftorrresd** [comment]
please test

File: PhysicsTools/NanoAOD/plugins/GenCandMotherTableProducer.cc [hunk 1]
```diff
@@ -48,6 +48,8 @@ class GenCandMotherTableProducer : public edm::global::EDProducer<> {
         key[i] = -1;
         // try to find the closest mother which is in the map
         while (match.isNull() && motherRef.isNonnull()) {
+          if (motherRef->numberOfMothers() == 0)
+            break;
```
Comment (battibass) [inline PhysicsTools/NanoAOD/plugins/GenCandMotherTableProducer.cc]: Am I missing something obvious or this is equivalent to
```c++
  while (match.isNull() && motherRef.isNonnull() && motherRef->numberOfMothers() != 0) {
```
?

Comment (mseidel42) [reply PhysicsTools/NanoAOD/plugins/GenCandMotherTableProducer.cc]: Hi Carlo, yes, that is equivalent. Do you prefer that I put everything in the `while` condition?

Comment (battibass) [reply PhysicsTools/NanoAOD/plugins/GenCandMotherTableProducer.cc]: Hi @mseidel42, it would be great, thanks

**Comment by battibass** [comment]
please test

**Comment by DickyChant** [comment]
hi all, given that we are seeing this issue in [some Summer24 BTVNano v15 production](https://gitlab.cern.ch/cms-ppd/dataset-management/simulation-production/-/issues/67#note_10692806) as well, I'd think we need this to be merged and back ported with a priority. The fix looks good to me btw.

**Comment by battibass** [comment]
+1

**Comment by ftenchini** [comment]
+1
