### PR TITLE
Replace reference to ParameterSet with a struct of parameter values in (Global)EvFOutputModule

### LINKED ISSUE #684: Fix BUFU_TEST
Reported in https://github.com/cms-sw/cmssw/issues/42910

Fixed in https://github.com/cms-sw/cmssw/pull/42915

### LINKED ISSUE #42910: Test BUFU_TEST fails with SIGSEGV in edm::ParameterSet::retrieveUntracked
Unit test [EventFilter/Utilities/BUFU_TEST](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_X_2023-09-28-2300/unitTestLogs/EventFilter/Utilities#/115-115) failed for several architectures in CMSSW_13_3_X_2023-09-28-2300 IB:

```
Thread 3 (Thread 0x1518e516f700 (LWP 3266014) "cmsRun"):
#0  0x000015190a3b9f41 in poll () from /lib64/libc.so.6
#1  0x0000151905ef2d0f in full_read.constprop () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#2  0x0000151905eba8ec in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  0x0000151905ebb34b in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x000015190a35e5da in __memcmp_avx2_movbe () from /lib64/libc.so.6
#6  0x000015190cf65940 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, edm::Entry>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, edm::Entry> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, edm::Entry> > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#7  0x000015190cf5d28e in edm::ParameterSet::retrieveUntracked(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#8  0x000015190cf5d2d5 in edm::ParameterSet::getEntryPointerOrThrow_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#9  0x000015190cf5d339 in edm::ParameterSet::getEntryPointerOrThrow_(char const*) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#10 0x000015190cf67379 in bool edm::ParameterSet::getUntrackedParameter<bool>(char const*) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#11 0x000015190534de1d in edm::StreamerOutputModuleCommon::StreamerOutputModuleCommon(edm::ParameterSet const&, std::vector<std::pair<edm::BranchDescription const*, edm::EDGetToken>, std::allocator<std::pair<edm::BranchDescription const*, edm::EDGetToken> > > const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libIOPoolStreamer.so
#12 0x000015190563c76c in evf::GlobalEvFOutputModule::globalBeginRun(edm::RunForOutput const&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginEventFilterUtilitiesPlugins.so
#13 0x0000151905634392 in virtual thunk to edm::global::outputmodule::RunCacheHolder<edm::global::OutputModuleBase, evf::GlobalEvFOutputJSONDef>::doBeginRun_(edm::RunForOutput const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginEventFilterUtilitiesPlugins.so
#14 0x000015190cd1d4b0 in edm::core::OutputModuleCore::doBeginRun(edm::RunTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#15 0x000015190cd8e4a0 in edm::WorkerT<edm::global::OutputModuleBase>::implDoBegin(edm::RunTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#16 0x000015190cce246f in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#17 0x000015190cccdddd in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#18 0x000015190cc8d9cf in tbb::detail::d1::function_task<edm::WaitingTaskHolder::doneWaiting(std::__exception_ptr::exception_ptr)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#19 0x000015190b50c96f in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter> (t=0x151908ba3500, waiter=..., this=0x151908bbbe80) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/task_dispatcher.h:322
#20 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter> (t=0x0, waiter=..., this=0x151908bbbe80) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/task_dispatcher.h:458
#21 tbb::detail::r1::arena::process (tls=..., this=<optimized out>) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/arena.cpp:137
#22 tbb::detail::r1::market::process (this=<optimized out>, j=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/market.cpp:599
#23 0x000015190b50ebb5 in tbb::detail::r1::rml::private_worker::run (this=0x151906be2100) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/private_server.cpp:271
#24 tbb::detail::r1::rml::private_worker::thread_routine (arg=0x151906be2100) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/private_server.cpp:221
#25 0x000015190a6631ca in start_thread () from /lib64/libpthread.so.0
```

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR replaces the references to `ParameterSet` with a struct of parameter values in GlobalEvFOutputModule and EvFOutputModule.

Fixes https://github.com/cms-sw/cmssw/issues/42910
Resolves https://github.com/makortel/framework/issues/684

#### PR validation:
 
Unit tests pass

### CODE REVIEW

**Comment by iarspider** [comment]
@makortel thanks!

**Comment by iarspider** [comment]
please test

File: EventFilter/Utilities/plugins/GlobalEvFOutputModule.cc [hunk 1]
```diff
@@ -342,14 +342,15 @@ namespace evf {
 
   std::unique_ptr<edm::StreamerOutputModuleCommon> GlobalEvFOutputModule::beginStream(edm::StreamID) const {
     return std::make_unique<edm::StreamerOutputModuleCommon>(
-        ps_, &keptProducts()[edm::InEvent], description().moduleLabel());
+        commonParameters_, &keptProducts()[edm::InEvent], description().moduleLabel());
```
Comment (Dr15Jones) [inline EventFilter/Utilities/plugins/GlobalEvFOutputModule.cc:345]: Should this be `&commonParameters_` since now it is value type?

**Comment by smorovic** [comment]
+daq
Thanks!

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1
