### PR TITLE
Fix and modernize Skeleton template scripts

### LINKED ISSUE #29306: Missing mkTemplates folder
It looks like a recent change in the build rules ended up dropping the mkTemplates folder used for some utilities:
https://github.com/cms-sw/cmssw-config/blob/8ccbb93b0e24f7f4cd6b147f2b3a2fb739f95fbf/ChangeLog#L11-L12

See https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3554.html for the original report.

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR enables the `mk*` skeleton generation scripts to run again by moving the `mkTemplates` directory (of the templates) from `FWCore/Skeletons/scripts/mkTemplates` to `FWCore/Skeletons/mkTemplates`. Resolves #29306 .

Furthermore, this PR modernizes the skeleton templates by accounting the code formatting as much as feasible (some empty lines turned out to be difficult to avoid without touching the generation code itself), and by modernizing the code overall (range-for, consumes, `=delete`) following suggestions in #26618.

The EventHypothesis template and `mkevhyp` script are removed as obsolete as agreed in https://github.com/cms-sw/cmssw/issues/29834.

#### PR validation:

The scripts run (except for `mktmpl`, which appears to be broken already in 10_2_X).

### CODE REVIEW

**Comment by makortel** [comment]
@wddgit @Dr15Jones Could you take a quick look, please?

**Comment by makortel** [comment]
@smuzaffar The files under `FWCore/Skeletons/mkTemplates` should not be touched by `clang-format` or `clang-tidy`. Is there an easy way avoid that? https://github.com/cms-sw/cmssw/issues/26618 suggests to rename the files to have a suffix different from `.cc` and `.h`, so I guess that's it if nothing else can be done easily.

**Comment by wddgit** [comment]
I read through the PR quickly and did not notice any problems. It looks nice, definitely an improvement over the current situation.

File: FWCore/Skeletons/mkTemplates/ESProducer/ESProducer.cc [hunk 1]
```diff
@@ -72,53 +73,46 @@ class __class__ : public edm::ESProducer {
...
 //
-__class__::__class__(const edm::ParameterSet& iConfig)
-{
-   //the following line is needed to tell the framework what
-   // data is being produced
-   setWhatProduced(this);
+__class__::__class__(const edm::ParameterSet& iConfig) {
+  //the following line is needed to tell the framework what
+  // data is being produced
+  setWhatProduced(this);
```
Comment (Dr15Jones) [inline FWCore/Skeletons/mkTemplates/ESProducer/ESProducer.cc:79]: Should we add an example of how to use consumes?

File: FWCore/Skeletons/python/utils.py [hunk 2]
```diff
@@ -20,6 +20,20 @@
...
+def template_directory():
+    "Return location of template directory"
+    mkTemplates = "src/FWCore/Skeletons/mkTemplates"
+    # Check developer area first
+    if "CMSSW_BASE" in os.environ:
+        ret = os.path.join(os.environ["CMSSW_BASE"], mkTemplates)
+        if os.path.exists(ret):
+            return ret
+    # Then release area
+    ret = os.path.join(os.environ["CMSSW_RELEASE_BASE"], mkTemplates)
```
Comment (Dr15Jones) [inline FWCore/Skeletons/python/utils.py:32]: Does this work with patch releases?

**Comment by Dr15Jones** [comment]
I've looked it over and gave my few comments.

File: FWCore/Skeletons/mkTemplates/ESProducer/ESProducer.cc (hunk 1 above)
Comment (makortel) [reply FWCore/Skeletons/mkTemplates/ESProducer/ESProducer.cc:79]: Probably, thanks.

File: FWCore/Skeletons/python/utils.py (hunk 2 above)
Comment (makortel) [reply FWCore/Skeletons/python/utils.py:32]: Yes, https://github.com/cms-sw/cmssw/issues/29306#issuecomment-624120098
> Patch release contians symlinks for missing packages.

File: FWCore/Skeletons/mkTemplates/ESProducer/ESProducer.cc (hunk 1 above)
Comment (makortel) [reply FWCore/Skeletons/mkTemplates/ESProducer/ESProducer.cc:79]: Let me add that if we manage to get this PR in quickly (i.e. past code checks), I'll leave the ESProducer consumes to a subsequent PR.

**Comment by smuzaffar** [comment]
@makortel , clang-tidy only process those files which are directly compiled with scram, so clang-tidy is not going to touch files under `FWCore/Skeletons/mkTemplates.

In order to avoid clang-format to process files under FWCore/Skeletons/mkTemplates , I would suggest to create `FWCore/Skeletons/mkTemplates/.clang-format` files with following contents

```
DisableFormat: true
SortIncludes: false
```

**Comment by davidlange6** [comment]
do the resulting examples made with these skeletons pass clang-tidy?

**Comment by davidlange6** [comment]
I really mean clang-format in my question above.

**Comment by makortel** [comment]
@davidlange6 Mostly yes. There are some places where that appeared to be difficult without touching the generation code, like here
https://github.com/cms-sw/cmssw/blob/01ecbedd9cf1019f032bbb3540918926aa94c1e1/FWCore/Skeletons/mkTemplates/EDProducer/EDProducer.cc#L79-L83
and I wanted to get what I have to 11_1_0, and leave further tuning later. I'm thinking to set up tests for running the scripts, it would be nice to include clang-format and clang-tidy checks there as well.

**Comment by makortel** [comment]
@smuzaffar Thanks! It did the trick.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1
