### PR TITLE
Fix UBSAN error in FWCore/Framework unit tests

### LINKED ISSUE #1657: Fix UBSAN error from nullptr in FWCore/Framework unit tests
### Description

See https://github.com/cms-sw/cmssw/issues/49367

### LINKED ISSUE #1658: Update some tests in FWCore/Framework to use catch2
### Description

_No response_

### LINKED ISSUE #49367: UBSAN assigning nullptr to edm::EventSetupImpl in global_filter_t
Although the argument begin passed isn't being used by the test, it still should be properly defined.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- No longer dereference a nullptr
- Convert tests to catch2

#### PR validation:

resolves https://github.com/cms-sw/framework-team/issues/1657
resolves https://github.com/cms-sw/framework-team/issues/1658
resolves https://github.com/cms-sw/cmssw/issues/49367

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

File: FWCore/Framework/test/global_producer_catch2.cc [hunk 1]
```diff
@@ -0,0 +1,609 @@
...
+    IDUnion() : m_shadow() {}
+    ShadowStreamID m_shadow;
+    edm::StreamID m_id;
+  };
+}  // namespace
+static edm::StreamID makeID() {
+  IDUnion u;
+  assert(u.m_id.value() == 0);
+  return u.m_id;
+}
```
Comment (Dr15Jones) [inline FWCore/Framework/test/global_producer_catch2.cc]: Should consolidate anonymous namespace

File: FWCore/Framework/test/global_producer_catch2.cc [hunk 2]
```diff
@@ -0,0 +1,609 @@
...
+    edm::PreallocationConfiguration m_preallocConfig;
+    std::shared_ptr<edm::ProductRegistry> m_prodReg;
+    std::shared_ptr<edm::BranchIDListHelper> m_idHelper;
+    std::shared_ptr<edm::ThinnedAssociationsHelper> m_associationsHelper;
+    std::unique_ptr<edm::EventPrincipal> m_ep;
+    edm::HistoryAppender historyAppender_;
+    std::shared_ptr<edm::LuminosityBlockPrincipal> m_lbp;
+    std::shared_ptr<edm::RunPrincipal> m_rp;
+    std::shared_ptr<edm::ActivityRegistry> m_actReg;
+    edm::EventSetupImpl* m_es = nullptr;
```
Comment (Dr15Jones) [inline FWCore/Framework/test/global_producer_catch2.cc]: This should be set

File: FWCore/Framework/test/global_outputmodule_catch2.cc [hunk 3]
```diff
@@ -0,0 +1,337 @@
...
+    edm::PreallocationConfiguration m_preallocConfig;
+    std::shared_ptr<edm::ProductRegistry> m_prodReg;
+    std::shared_ptr<edm::BranchIDListHelper> m_idHelper;
+    std::shared_ptr<edm::ThinnedAssociationsHelper> m_associationsHelper;
+    std::unique_ptr<edm::EventPrincipal> m_ep;
+    edm::HistoryAppender historyAppender_;
+    std::shared_ptr<edm::LuminosityBlockPrincipal> m_lbp;
+    std::shared_ptr<edm::RunPrincipal> m_rp;
+    std::shared_ptr<edm::ActivityRegistry> m_actReg;
+    edm::EventSetupImpl* m_es = nullptr;
```
Comment (Dr15Jones) [inline FWCore/Framework/test/global_outputmodule_catch2.cc]: This should be set

File: FWCore/Framework/test/limited_filter_catch2.cc [hunk 4]
```diff
@@ -0,0 +1,647 @@
...
+namespace {
+  edm::ParameterSet makePSet() {
+    edm::ParameterSet pset;
+    const unsigned int kLimit = 1;
+    pset.addUntrackedParameter("concurrencyLimit", kLimit);
+    return pset;
+  }
+
+  const edm::ParameterSet s_pset = makePSet();
+}  // namespace
```
Comment (Dr15Jones) [inline FWCore/Framework/test/limited_filter_catch2.cc]: consolidate namespace

File: FWCore/Framework/test/limited_filter_catch2.cc [hunk 5]
```diff
@@ -0,0 +1,647 @@
...
+  };
+}  // namespace
+static edm::StreamID makeID() {
+  IDUnion u;
+  assert(u.m_id.value() == 0);
+  return u.m_id;
+}
+static const edm::StreamID s_streamID0 = makeID();
+
+namespace {
```
Comment (Dr15Jones) [inline FWCore/Framework/test/limited_filter_catch2.cc]: consolidate

File: FWCore/Framework/test/limited_filter_catch2.cc [hunk 6]
```diff
@@ -0,0 +1,647 @@
...
+    edm::ProcessConfiguration m_procConfig;
+    std::shared_ptr<edm::ProductRegistry> m_prodReg;
+    std::shared_ptr<edm::BranchIDListHelper> m_idHelper;
+    std::shared_ptr<edm::ThinnedAssociationsHelper> m_associationsHelper;
+    std::unique_ptr<edm::EventPrincipal> m_ep;
+    edm::HistoryAppender historyAppender_;
+    std::shared_ptr<edm::LuminosityBlockPrincipal> m_lbp;
+    std::shared_ptr<edm::RunPrincipal> m_rp;
+    std::shared_ptr<edm::ActivityRegistry> m_actReg;
+    edm::EventSetupImpl* m_es = nullptr;
```
Comment (Dr15Jones) [inline FWCore/Framework/test/limited_filter_catch2.cc]: Should be set

File: FWCore/Framework/test/limited_outputmodule_catch2.cc [hunk 7]
```diff
@@ -0,0 +1,338 @@
...
+    std::shared_ptr<edm::ProductRegistry> m_prodReg;
+    std::shared_ptr<edm::BranchIDListHelper> m_idHelper;
+    std::shared_ptr<edm::ThinnedAssociationsHelper> m_associationsHelper;
+    std::unique_ptr<edm::EventPrincipal> m_ep;
+    edm::HistoryAppender historyAppender_;
+    std::shared_ptr<edm::LuminosityBlockPrincipal> m_lbp;
+    std::shared_ptr<edm::RunPrincipal> m_rp;
+    std::shared_ptr<edm::ActivityRegistry>
+        m_actReg;  // We do not use propagate_const because the registry itself is mutable.
+    edm::EventSetupImpl* m_es = nullptr;
```
Comment (Dr15Jones) [inline FWCore/Framework/test/limited_outputmodule_catch2.cc]: Should be set

File: FWCore/Framework/test/makeEmptyEventSetupImplForTest.h [hunk 8]
```diff
@@ -0,0 +1,8 @@
+#ifndef FWCore_Framework_makeEmptyEventSetupImplForTest_h
+#define FWCore_Framework_makeEmptyEventSetupImplForTest_h
+#include "FWCore/Framework/interface/EventSetupImpl.h"
+
+namespace edm {
+  inline edm::EventSetupImpl makeEmptyEventSetupImplForTest() { return edm::EventSetupImpl(); }
+}  // namespace edm
+#endif  // FWCore_Framework_makeEmptyEventSetupImplForTest_h
```
Comment (Dr15Jones) [inline FWCore/Framework/test/makeEmptyEventSetupImplForTest.h]: add new line

File: FWCore/Framework/test/one_outputmodule_catch2.cc [hunk 9]
```diff
@@ -0,0 +1,496 @@
...
+    std::shared_ptr<edm::ProductRegistry> m_prodReg;
+    std::shared_ptr<edm::BranchIDListHelper> m_idHelper;
+    std::shared_ptr<edm::ThinnedAssociationsHelper> m_associationsHelper;
+    std::unique_ptr<edm::EventPrincipal> m_ep;
+    edm::HistoryAppender historyAppender_;
+    std::shared_ptr<edm::LuminosityBlockPrincipal> m_lbp;
+    std::shared_ptr<edm::RunPrincipal> m_rp;
+    std::shared_ptr<edm::ActivityRegistry>
+        m_actReg;  // We do not use propagate_const because the registry itself is mutable.
+    edm::EventSetupImpl* m_es = nullptr;
```
Comment (Dr15Jones) [inline FWCore/Framework/test/one_outputmodule_catch2.cc]: should be set

File: FWCore/Framework/test/stream_filter_catch2.cc [hunk 10]
```diff
@@ -0,0 +1,648 @@
...
+    std::shared_ptr<edm::ProductRegistry> m_prodReg;
+    std::shared_ptr<edm::BranchIDListHelper> m_idHelper;
+    std::shared_ptr<edm::ThinnedAssociationsHelper> m_associationsHelper;
+    std::unique_ptr<edm::EventPrincipal> m_ep;
+    edm::HistoryAppender historyAppender_;
+    std::shared_ptr<edm::LuminosityBlockPrincipal> m_lbp;
+    std::shared_ptr<edm::RunPrincipal> m_rp;
+    std::shared_ptr<edm::ActivityRegistry>
+        m_actReg;  // We do not use propagate_const because the registry itself is mutable.
+    edm::EventSetupImpl* m_es = nullptr;
```
Comment (Dr15Jones) [inline FWCore/Framework/test/stream_filter_catch2.cc]: should be set

File: FWCore/Framework/test/stream_producer_catch2.cc [hunk 11]
```diff
@@ -0,0 +1,650 @@
...
+    constexpr ShadowStreamID() : value(0) {}
+    unsigned int value;
+  };
+
+  union IDUnion {
+    IDUnion() : m_shadow() {}
+    ShadowStreamID m_shadow;
+    edm::StreamID m_id;
+  };
+}  // namespace
```
Comment (Dr15Jones) [inline FWCore/Framework/test/stream_producer_catch2.cc]: consolidate

File: FWCore/Framework/test/stream_producer_catch2.cc [hunk 12]
```diff
@@ -0,0 +1,650 @@
...
+    std::shared_ptr<edm::ProductRegistry> m_prodReg;
+    std::shared_ptr<edm::BranchIDListHelper> m_idHelper;
+    std::shared_ptr<edm::ThinnedAssociationsHelper> m_associationsHelper;
+    std::unique_ptr<edm::EventPrincipal> m_ep;
+    edm::HistoryAppender historyAppender_;
+    std::shared_ptr<edm::LuminosityBlockPrincipal> m_lbp;
+    std::shared_ptr<edm::RunPrincipal> m_rp;
+    std::shared_ptr<edm::ActivityRegistry>
+        m_actReg;  // We do not use propagate_const because the registry itself is mutable.
+    edm::EventSetupImpl* m_es = nullptr;
```
Comment (Dr15Jones) [inline FWCore/Framework/test/stream_producer_catch2.cc]: should be set

**Review by Dr15Jones — COMMENTED** [review]
These need to be fixed

File: FWCore/Framework/test/global_producer_catch2.cc (hunk 1 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/global_producer_catch2.cc]: done

File: FWCore/Framework/test/global_producer_catch2.cc (hunk 2 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/global_producer_catch2.cc]: done

File: FWCore/Framework/test/global_outputmodule_catch2.cc (hunk 3 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/global_outputmodule_catch2.cc]: done

File: FWCore/Framework/test/limited_filter_catch2.cc (hunk 4 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/limited_filter_catch2.cc]: done

File: FWCore/Framework/test/makeEmptyEventSetupImplForTest.h (hunk 8 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/makeEmptyEventSetupImplForTest.h]: done

File: FWCore/Framework/test/one_outputmodule_catch2.cc (hunk 9 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/one_outputmodule_catch2.cc]: done

File: FWCore/Framework/test/stream_filter_catch2.cc (hunk 10 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/stream_filter_catch2.cc]: done

File: FWCore/Framework/test/stream_producer_catch2.cc (hunk 11 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/stream_producer_catch2.cc]: done

File: FWCore/Framework/test/stream_producer_catch2.cc (hunk 12 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/stream_producer_catch2.cc]: done

File: FWCore/Framework/test/limited_filter_catch2.cc (hunk 5 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/limited_filter_catch2.cc]: done

File: FWCore/Framework/test/limited_filter_catch2.cc (hunk 6 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/limited_filter_catch2.cc]: done

File: FWCore/Framework/test/limited_outputmodule_catch2.cc (hunk 7 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/limited_outputmodule_catch2.cc]: done

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Latest change removed anonymous namespaces within anonymous namespaces which were added by Claude.

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/47071

**Comment by makortel** [comment]
+core

**Comment by ftenchini** [comment]
+1
