### PR TITLE
Fix SiStripQuality merging with FED errors from a DQM file

### LINKED ISSUE #33960: SiStripGainsPCL MRH ASAN error, EventSetup product in dqmEndJob
@mmusich noticed a failure in the address sanitizer IBs for the SiStripGainsPCLHarvester [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_ASAN_X_2021-05-31-2300/unitTestLogs/CalibTracker/SiStripChannelGain#/458).
The only pointer around in [`APVGain::subdetectorPlane`](https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/src/APVGainHelpers.cc#L119-L131) is one to the `TrackerTopology`, which is retrieved by the SiStripGainsPCLHarvester at the `BeginRun` transition ([L52](https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/src/SiStripGainsPCLHarvester.cc#L52) and [L619-623](https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/src/SiStripGainsPCLHarvester.cc)).
I didn't fully think this through when migrating the harvester to esConsumes in https://github.com/cms-sw/cmssw/pull/31826 , but based on the ASAN information my hypothesis is that the `TrackerTopology` is deleted before `dqmEndJob` is called (from `endProcessBlockProduce`) - the bad address from ASAN is inside `[tTopo_, tTopo_+sizeof(TrackerTopology)[`.
Is that correct? How should we get the `TrackerTopology` such that it can be used from `dqmEndJob`?
Thanks in advance!

### PR DESCRIPTION
**Pull request by pieterdavid**
#### PR description:

This PR fixes https://github.com/cms-sw/cmssw/issues/33960 for SiStripQualityStatistics and SiStripBadComponentInfo, and makes reading the bad components from FED errors from a legacy DQM file work again (this stopped working at some point, and https://github.com/cms-sw/cmssw/pull/27565 did not cover this case - the common case, which is used in the DQM sequence and covered by matrix tests, is reading from the DQM store, that has always been working correctly). Reading from a file is only used locally from time to time to produce a payload.

#### PR validation:

The produced bad component payload, with the FED errors source included from a file, is identical to the one produced with a 10_1_X release, and that is added as a new unit test. This tests uses a DQM file from EOS, I added a check to skip the tests in case that is not found, is that a reasonable solution? Matrix tests run without errors, no changes in the comparisons are expected.

CC: @kmondal @mmusich @robervalwalsh

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

File: CalibTracker/SiStripQuality/test/test_makeMergedBadComponentsWithFedErr.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
+#!/bin/bash
+function die { echo $1: status $2 ;  exit $2; }
+run="319176"
+dqmFile="/eos/cms/store/group/comm_dqm/DQMGUI_data/Run2018/ZeroBias/R0003191xx/DQM_V0001_R000319176__ZeroBias__Run2018B-PromptReco-v2__DQMIO.root"
```
Comment (mmusich) [inline CalibTracker/SiStripQuality/test/test_makeMergedBadComponentsWithFedErr.sh:4]: @jfernan2 how long do you reckon will these legacy files be stored on the DQM group eos area?

Comment (jfernan2) [reply CalibTracker/SiStripQuality/test/test_makeMergedBadComponentsWithFedErr.sh:4]: In principle there is no deadline, so that address is fine for the long term, and since we are moving to the new DQM GUI which will use eos as backend (with that same address if quota gets increased, or a new address), I believe it is safe to use it.
Thanks for asking!

**Comment by mmusich** [comment]
given the build error message at https://github.com/cms-sw/cmssw/pull/34082#issuecomment-858636059 I think this needs to be rebased on some recent IB that contains https://github.com/cms-sw/cmssw/pull/33888 (?)

**Comment by pieterdavid** [comment]
> given the build error message at [#34082 (comment)](https://github.com/cms-sw/cmssw/pull/34082#issuecomment-858636059) I think this needs to be rebased on some recent IB that contains #33888 (?)

I rebased on yesterday's 11am IB, but forgot to rebuild with `git cms-checkdeps -a` after the changes (some to buildfiles), I'm checking the errors

**Comment by smuzaffar** [comment]
code-checks

**Comment by mmusich** [comment]
@smuzaffar can you adjust the code-check also here? Thank you

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by pieterdavid** [comment]
> I was a bit optimistic in assuming no differences in the comparisons, apparently: a few of the bad components summary plots have differences. I will investigate and update the PR if needed.

I overlooked something, which made that an option was not being passed on correctly, the comparisons pass locally now.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by yuanchao** [comment]
+1

**Comment by qliphy** [comment]
ping @cms-sw/db-l2

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@ggovi can you please review and sign? 
Thank you

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1
