### PR TITLE
TrackDistanceValueMapProducer: check the size of the reference vector before copying

### LINKED ISSUE #33533: [PPC] Segfault in TrackDistanceValueMapProducer
Workflow 11634.24 step 5 failed in slc7_ppc64le_gcc9 CMSSW_12_0_X_2021-04-25-0000
```
Thread 5 (Thread 0x10025aa08390 (LWP 12659)):
#2  0x000010000ac2088c in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x0000100002a5e92c in pthread_cond_wait@@GLIBC_2.17 () from /lib64/libpthread.so.0
#5  0x00001000027881dc in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /scratch/cmsbuild/gcc9/boot/BUILD/slc7_ppc64le_gcc9/external/gcc/9.3.0/gcc-9.3.0/obj/powerpc64le-unknown-linux-gnu/libstdc++-v3/include/powerpc64le-unknown-linux-gnu/bits/gthr-default.h:865
#6  std::condition_variable::wait (this=<optimized out>, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:53
#7  0x0000100000f303f4 in ROOT::TReentrantRWLock<std::mutex, ROOT::Internal::RecurseCounts>::WriteLock() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libThread.so
#8  0x0000100000f33bcc in ROOT::TRWMutexImp<std::mutex, ROOT::Internal::RecurseCounts>::WriteLock() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libThread.so
#9  0x0000100000c64c58 in ROOT::TVirtualRWMutex::Lock() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libTree.so
#10 0x000010020dc84b7c in TCling::GetFunctionWithPrototype(ClassInfo_t*, char const*, char const*, bool, ROOT::EFunctionMatchMode) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#11 0x0000100001b74338 in TClass::GetMethodWithPrototype(char const*, char const*, bool, ROOT::EFunctionMatchMode) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCore.so
#12 0x0000100000ac1548 in edm::TypeWithDict::functionMemberByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreReflection.so
#13 0x0000100228702dfc in reco::findMethod(edm::TypeWithDict const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::vector<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, char const*, int&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#14 0x00001002286d920c in reco::parser::MethodSetter::push(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, char const*, bool) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#15 0x00001002286d26e4 in reco::parser::SingleInvoker::SingleInvoker(edm::TypeWithDict const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#16 0x00001002286d4424 in reco::parser::LazyInvoker::invoker(edm::TypeWithDict const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#17 0x00001002286d6fe0 in reco::parser::LazyInvoker::invokeLast(edm::ObjectWithDict const&, std::vector<edm::ObjectWithDict, std::allocator<edm::ObjectWithDict> >&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#18 0x00001002286aceec in reco::parser::ExpressionLazyVar::value(edm::ObjectWithDict const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#19 0x00001002286e93d4 in reco::parser::BinarySelector::operator()(edm::ObjectWithDict const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#20 0x00001002286d1760 in reco::parser::LogicalBinaryOperator<std::logical_and<bool> >::operator()(edm::ObjectWithDict const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#21 0x0000100269f29300 in TrackingMonitor::analyze(edm::Event const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginDQMTrackingMonitor.so
#22 0x0000100269e94b7c in edm::stream::impl::Accumulator::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginDQMTrackingMonitor.so
#23 0x0000100000429178 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#24 0x00001000003f09b4 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#25 0x00001000003009f8 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#26 0x0000100000300c80 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#27 0x00001000003010f8 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#28 0x0000100000303910 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so

Thread 4 (Thread 0x100256608390 (LWP 12658)):
#1  0x0000100002b6e8bc in sleep () from /lib64/libc.so.6
#2  0x000010000ac2088c in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x000010000248dd58 in inflate () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libz.so.1
#5  0x0000100242845b10 in fn_gunzip_update () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#6  0x000010024285ad14 in frontierMemData_append () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#7  0x000010024285b160 in frontierMemData_b64append () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#8  0x000010024285bb00 in frontierPayload_append () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#9  0x000010024285c260 in xml_cdata () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#10 0x000010024289c548 in doContent (parser=parser@entry=0x100273baec00, startTagLevel=startTagLevel@entry=0, enc=0x1002428cf570 <ascii_encoding>, s=<optimized out>, end=0x100273f26400 "hltIterL3FromL1MuonTrimmedPixelVertices", nextPtr=<optimized out>, haveMore=<optimized out>) at lib/xmlparse.c:2653
#11 0x000010024289d220 in contentProcessor (parser=0x100273baec00, start=<optimized out>, end=<optimized out>, endPtr=<optimized out>) at lib/xmlparse.c:2105
#12 0x000010024289fb90 in XML_ParseBuffer (isFinal=0, len=<optimized out>, parser=0x100273baec00) at lib/xmlparse.c:1651
#13 XML_ParseBuffer (parser=0x100273baec00, len=<optimized out>, isFinal=<optimized out>) at lib/xmlparse.c:1623
#14 0x00001002428a00e4 in XML_Parse (parser=0x100273baec00, s=0x1002566045d8 "H91xOOUP7kRyPv+Zeym6k3DKH9yp5Hz+M/didMtwyh9cfP421Jfz35XWhlejOwOn/MGdTc7n\nP3OvRLcCp/zBnUvO5z9zb0R3Hk75g7uQnM9/5l6PbhVO+YO7mFw1f4V7P7pLcMof3OXkfP4z9150\nV+CUP7iryfn8Z+7D6K7BKX9w15Pz+c/cB9HdgFP+4G7WuHL+M/"..., len=<optimized out>, isFinal=<optimized out>) at lib/xmlparse.c:1617
#15 0x000010024285d074 in FrontierResponse_append () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#16 0x00001002428538f8 in write_data () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#17 0x0000100242854df8 in get_data () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#18 0x000010024285567c in frontier_postRawData () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#19 0x0000100242855258 in frontier_getRawData () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#20 0x00001002428475cc in frontier::Session::getData(std::vector<frontier::Request const*, std::allocator<frontier::Request const*> > const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libfrontier_client.so.2
#21 0x00001002427b3b8c in coral::FrontierAccess::Statement::execute(coral::AttributeList const&, int) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/liblcg_FrontierAccess.so
#22 0x000010024279ceac in coral::FrontierAccess::Query::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/liblcg_FrontierAccess.so
#23 0x000010022653d55c in cond::persistency::PAYLOAD::Table::select(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cond::Binary&, cond::Binary&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCondCoreCondDB.so
#24 0x000010022657aa44 in cond::persistency::Session::fetchPayloadData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cond::Binary&, cond::Binary&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCondCoreCondDB.so
#25 0x000010024531766c in std::unique_ptr<SiStripFedCabling, std::default_delete<SiStripFedCabling> > cond::persistency::Session::fetchPayload<SiStripFedCabling>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginCondCoreSiStripPluginsOthers.so
#26 0x0000100245317b44 in cond::persistency::PayloadProxy<SiStripFedCabling>::loadPayload() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginCondCoreSiStripPluginsOthers.so
#27 0x00001002452e3a3c in DataProxy<SiStripFedCablingRcd, SiStripFedCabling, cond::DefaultInitializer<SiStripFedCabling> >::prefetch(edm::eventsetup::DataKey const&, edm::EventSetupRecordDetails) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginCondCoreSiStripPluginsOthers.so
#28 0x0000100000208758 in edm::SerialTaskQueue::QueuedTask<edm::eventsetup::ESSourceDataProxyBase::prefetchAsyncImpl(edm::WaitingTaskHolder, edm::eventsetup::EventSetupRecordImpl const&, edm::eventsetup::DataKey const&, edm::EventSetupImpl const*, edm::ServiceToken const&, edm::ESParentContext const&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#29 0x0000100000a179e4 in tbb::internal::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreConcurrency.so

Thread 3 (Thread 0x10024cc18390 (LWP 12656)):
#3  0x000010000ac24550 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000100222e6b690 in void std::vector<float, std::allocator<float> >::_M_realloc_insert<float const&>(__gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >, float const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libDataFormatsTrackerRecHit2D.so
#6  0x000010026a8ddf0c in TrackDistanceValueMapProducer::produce(edm::StreamID, edm::Event&, edm::EventSetup const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginTrackDistanceValueMapProducer.so
#7  0x000010000040009c in edm::global::EDProducerBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#8  0x00001000003f01f4 in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#9  0x00001000003009f8 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#10 0x0000100000300c80 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#11 0x00001000003010f8 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#12 0x0000100000303910 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#13 0x00001000001e8484 in tbb::internal::function_task<edm::WaitingTaskHolder::doneWaiting(std::__exception_ptr::exception_ptr)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so

Thread 1 (Thread 0x1000034e0000 (LWP 12283)):
#2  0x000010000ac2088c in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x0000100210219180 in (anonymous namespace)::CXXNameMangler::manglePrefix(clang::DeclContext const*, bool) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#5  0x0000100210219b2c in (anonymous namespace)::CXXNameMangler::mangleTemplatePrefix(clang::TemplateDecl const*, bool) [clone .part.0] () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#6  0x000010021021a420 in (anonymous namespace)::CXXNameMangler::mangleNestedName(clang::NamedDecl const*, clang::DeclContext const*, llvm::SmallVector<llvm::StringRef, 4u> const*, bool) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#7  0x000010021020fb98 in (anonymous namespace)::CXXNameMangler::mangleName(clang::NamedDecl const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#8  0x0000100210213d00 in (anonymous namespace)::CXXNameMangler::mangleType(clang::QualType) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#9  0x000010021021800c in (anonymous namespace)::CXXNameMangler::mangleTemplateArg(clang::TemplateArgument) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#10 0x00001002102183c0 in (anonymous namespace)::CXXNameMangler::mangleTemplateArgs(clang::TemplateArgumentList const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#11 0x000010021021a42c in (anonymous namespace)::CXXNameMangler::mangleNestedName(clang::NamedDecl const*, clang::DeclContext const*, llvm::SmallVector<llvm::StringRef, 4u> const*, bool) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#12 0x000010021020fb98 in (anonymous namespace)::CXXNameMangler::mangleName(clang::NamedDecl const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#13 0x0000100210213d00 in (anonymous namespace)::CXXNameMangler::mangleType(clang::QualType) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#14 0x0000100210213c08 in (anonymous namespace)::CXXNameMangler::mangleType(clang::QualType) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#15 0x0000100210214290 in (anonymous namespace)::CXXNameMangler::mangleType(clang::QualType) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#16 0x000010021021b640 in (anonymous namespace)::CXXNameMangler::mangleFunctionEncoding(clang::FunctionDecl const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#17 0x000010021021de70 in (anonymous namespace)::ItaniumMangleContextImpl::mangleCXXName(clang::NamedDecl const*, llvm::raw_ostream&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#18 0x000010021021f9ac in clang::MangleContext::mangleName(clang::NamedDecl const*, llvm::raw_ostream&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#19 0x000010020de48bf4 in cling::utils::Analyze::maybeMangleDeclName(clang::GlobalDecl const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#20 0x000010020dccff14 in TClingMethodInfo::GetMangledName[abi:cxx11]() const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#21 0x000010020dc4fd8c in TCling::MethodInfo_GetMangledName(MethodInfo_t*) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCling.so
#22 0x0000100001ba6e6c in TFunction::TFunction(MethodInfo_t*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCore.so
#23 0x0000100001bbd860 in TMethod::TMethod(MethodInfo_t*, TClass*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCore.so
#24 0x0000100001bb8d54 in TListOfFunctions::Get(void const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCore.so
#25 0x0000100001bb9b3c in TListOfFunctions::Load() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCore.so
#26 0x0000100001b70708 in TClass::GetListOfMethods(bool) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/external/slc7_ppc64le_gcc9/lib/libCore.so
#27 0x0000100000ab7034 in edm::TypeFunctionMembers::begin() const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreReflection.so
#28 0x0000100228702f84 in reco::findMethod(edm::TypeWithDict const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::vector<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, char const*, int&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#29 0x00001002286d920c in reco::parser::MethodSetter::push(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, char const*, bool) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#30 0x00001002286d26e4 in reco::parser::SingleInvoker::SingleInvoker(edm::TypeWithDict const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::variant<signed char, unsigned char, short, unsigned short, int, unsigned int, long, unsigned long, double, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#31 0x00001002286d4424 in reco::parser::LazyInvoker::invoker(edm::TypeWithDict const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#32 0x00001002286d6fe0 in reco::parser::LazyInvoker::invokeLast(edm::ObjectWithDict const&, std::vector<edm::ObjectWithDict, std::allocator<edm::ObjectWithDict> >&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#33 0x00001002286aceec in reco::parser::ExpressionLazyVar::value(edm::ObjectWithDict const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#34 0x00001002286e93d4 in reco::parser::BinarySelector::operator()(edm::ObjectWithDict const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#35 0x00001002286d1760 in reco::parser::LogicalBinaryOperator<std::logical_and<bool> >::operator()(edm::ObjectWithDict const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libCommonToolsUtils.so
#36 0x0000100269f29300 in TrackingMonitor::analyze(edm::Event const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginDQMTrackingMonitor.so
#37 0x0000100269e94b7c in edm::stream::impl::Accumulator::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/pluginDQMTrackingMonitor.so
#38 0x0000100000429178 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#39 0x00001000003f09b4 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#40 0x00001000003009f8 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#41 0x0000100000300c80 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#42 0x00001000003010f8 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#43 0x0000100000303910 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#44 0x0000100000a1a7ec in tbb::internal::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_ppc64le_gcc9/libFWCoreConcurrency.so

Current Modules:
Module: TrackDistanceValueMapProducer:trackDistances (crashed)
Module: TrackingMonitor:ALCARECOTkAlMinBiasTrackingDQM
Module: TrackingMonitor:ALCARECOTkAlMuonIsolatedTrackingDQM
Module: none
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_ppc64le_gcc9/CMSSW_12_0_X_2021-04-25-0000/pyRelValMatrixLogs/run/11634.24_TTbar_14TeV+2021_0T+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA/step5_TTbar_14TeV+2021_0T+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA.log#/

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/33533 (?)

#### PR description:

See https://github.com/cms-sw/cmssw/issues/33533#issuecomment-833486429
Suggested by core framework group.

#### PR validation:

Compiles, not validated on the PPC architecture, as I don't know how to do that. I let the framework people deal with it.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
type bugfix

**Comment by mmusich** [comment]
@cmsbuild, please test

File: Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc [hunk 1]
```diff
@@ -120,7 +120,9 @@ void TrackDistanceValueMapProducer::produce(edm::StreamID streamID,
 
     // just copy the first nth
     std::vector<float> reduced_vdR2;
-    std::copy(v_dR2.begin(), v_dR2.begin() + nthClosestTrack_, std::back_inserter(reduced_vdR2));
+    if (!v_dR2.empty()) {
```
Comment (dan131riley) [inline Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc:123]: Sorry I was bit sloppy when I wrote that it should be checked for `> 0`.  This probably ought to be something like
```
    std::copy(v_dR2.begin(), std::min(v_dR2.size(), v_dR2.begin() + nthClosestTrack_), std::back_inserter(reduced_vdR2));
```

Comment (mmusich) [reply Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc:123]: given `nthClosestTrack_` is configured as 1, I still don't quite understand how it is possible to have an event with one perfectly reconstructed muon and no other tracks in it...

File: Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc [hunk 2]
```diff
@@ -120,7 +120,9 @@ void TrackDistanceValueMapProducer::produce(edm::StreamID streamID,
...
+      std::copy(v_dR2.begin(), v_dR2.begin() + nthClosestTrack_, std::back_inserter(reduced_vdR2));
+    }
```
Comment (mmusich) [inline Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc:125]:
```suggestion
    std::copy(v_dR2.begin(), std::min(v_dR2.size(), v_dR2.begin() + nthClosestTrack_), std::back_inserter(reduced_vdR2));
```

File: Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc (hunk 1 above)
Comment (dan131riley) [reply Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc]: It'd have to be an event where the v_dR2 vector ends up empty, and it's probably relevant that the wf where this happens, 11634.24, has `--magField 0T`

Comment (dan131riley) [reply Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc]: ugh, need more coffee...should be
```
    std::copy(v_dR2.begin(),  v_dR2.begin() + std::min(v_dR2.size(), nthClosestTrack_), std::back_inserter(reduced_vdR2));
```
and you'll probably have to change the type of `nthClosestTrack_` or static_cast or add a temporary so the types match.

Comment (mmusich) [reply Calibration/TkAlCaRecoProducers/plugins/TrackDistanceValueMapProducer.cc]: > It'd have to be an event where the v_dR2 vector ends up empty, 

that's what I don't understand how it can happen. It means there is a muon around which there is absolutely no track reconstructed. I'll have a look to this workflow to understand how exactly this happens. In the meanwhile I committed the changes you proposed.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
+alca
  - bugfix
  - tests passed (failure only related to the MessageLogger)
