### PR TITLE
Properly propate exception from DelayedReader

### LINKED ISSUE #36697: Failures in ROOT 6.26 IB RelVals
RelVals are seeing SIGABRT on around 50 workflows. 

```
cmsRun: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/997e45a2cab6f1aa8d23229a1e263b28/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_ROOT626_X_2022-01-11-0800/src/FWCore/Concurrency/src/WaitingTaskList.cc:57: void edm::WaitingTaskList::reset(): Assertion `m_head == nullptr' failed.
```

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Catch exception from DelayedReader and
   - convert it to cms::Exception
   - add calling context
- Add  unit test for exceptions thrown from DelayedReader

This problem was uncovered in the ROOT 6_26 IB.

fixes #36697

#### PR validation:

Code compiles. New unit test passes. Problem with cmsRun not properly shutting down in #36697 was also fixed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

File: FWCore/Framework/test/stubs/ToyModules.cc [hunk 1]
```diff
@@ -361,11 +362,47 @@ namespace edmtest {
...
+      desc.add<edm::InputTag>("label");
+      desc.add<int>("threshold", 0);
+      desc.add<bool>("shouldProduce", false);
+      descriptions.addDefault(desc);
+    }
+
+  private:
+    const edm::EDGetTokenT<edmtest::IntProduct> token_;
+    edm::EDPutTokenT<edmtest::IntProduct> putToken_;
+    int threshold_;
```
Comment (makortel) [inline FWCore/Framework/test/stubs/ToyModules.cc:396]: This could be `const` (since other members, that can be, are)?
```suggestion
    const int threshold_;
```

File: FWCore/Integration/test/DelayedReaderThrowingSource.cc [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+    historyID_ = ph.id();
+
+    BranchIDLists bilists(1);
+    for (auto const& branch : branches) {
+      bilists[0].emplace_back(branch.branchID().id());
+    }
+    branchIDListHelper()->updateFromInput(bilists);
+  }
+
+  DelayedReaderThrowingSource::~DelayedReaderThrowingSource() {}
```
Comment (makortel) [inline FWCore/Integration/test/DelayedReaderThrowingSource.cc:112]:
```suggestion
  DelayedReaderThrowingSource::~DelayedReaderThrowingSource() = default;
```
or remove?

File: FWCore/Framework/test/stubs/ToyModules.cc (hunk 1 above)
Comment (Dr15Jones) [reply FWCore/Framework/test/stubs/ToyModules.cc]: done

File: FWCore/Integration/test/DelayedReaderThrowingSource.cc (hunk 2 above)
Comment (Dr15Jones) [reply FWCore/Integration/test/DelayedReaderThrowingSource.cc]: done

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
The same workflow is failing in the IB.

**Comment by makortel** [comment]
+1

**Comment by Dr15Jones** [comment]
type bug-fix

**Comment by Dr15Jones** [comment]
ping @cms-sw/orp-l2

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge
