### PR TITLE
Fix configuration  for BPHMonitor

### LINKED ISSUE #39017: Consumes failure in `BPHMonitor`
Starting from `CMSSW_12_5_X_2022-08-09-1100`, some workflows are failing with: 

```
----- Begin Fatal Exception 09-Aug-2022 18:35:43 CEST-----------------------
An exception of category 'BadToken' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 9 stream: 0
   [1] Running path 'dqmoffline_1_step'
   [2] Calling method for module BPHMonitor/'Dimuon0_L3TnP_Upsilon'
Exception Message:
A get using a EDGetToken with the C++ type 'BXVector<GlobalAlgBlk>' was made using an uninitialized token.
 Please check that the variable is being initialized from a 'consumes' call.
----- End Fatal Exception -------------------------------------------------
```

e.g. 11634.911.
First spotted in https://github.com/cms-sw/cmssw/pull/38760#issuecomment-1209651811.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The recent change to BPHMonitor exposed a configuration problem with workflows in the integration builds. This change avoids having the code do an auto determination of data to get (which can fail when multiple 'preferred' data are available) and instead specifies which data to get via fillDescriptions.

#### PR validation:

The code compiles and workflow 11634.911 no longer complains about the configuration for BPHMonitor instances.

fixes #39017

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test workflow 11609.0, 11634.911, 11634.914

File: L1Trigger/L1TGlobal/interface/L1TGlobalUtil.h [hunk 1]
```diff
@@ -97,7 +97,12 @@ namespace l1t {
     /// check that the L1TGlobalUtil has been properly initialised
     bool valid() const;
 
-    static void fillDescription(edm::ParameterSetDescription& desc) { L1TGlobalUtilHelper::fillDescription(desc); }
+    static void fillDescription(edm::ParameterSetDescription& desc,
```
Comment (Dr15Jones) [inline L1Trigger/L1TGlobal/interface/L1TGlobalUtil.h:100]: This new version of `fillDescription` could also be used in `GenericTriggerEventFlag::fillPSetDescription`, where right now the configuration options for `L1TGlobalUtil` are explicitly declared.

File: L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h [hunk 2]
```diff
@@ -131,8 +135,16 @@ namespace l1t {
     // Register the callback function with the Framework
     // if any InputTags still need to be found.
     if (findL1TAlgBlk || findL1TExtBlk) {
-      module.callWhenNewProductsRegistered([this, findL1TAlgBlk, findL1TExtBlk, iC](auto iBranch) {
-        checkToUpdateTags(iBranch, iC, findL1TAlgBlk, findL1TExtBlk);
+      assert(false);
```
Comment (fwyzard) [inline L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h:138]: what's the point of the code after `assert(false)` ?

**Comment by fwyzard** [comment]
If I remember correctly the "ext" (external source) is only meaningful for Run 1 (and possible 2015) configurations.

File: L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h [hunk 3]
```diff
@@ -62,7 +62,10 @@ namespace l1t {
                         edm::InputTag const& l1tExtBlkInputTag);
 
     // A module defining its fillDescriptions function might want to use this
-    static void fillDescription(edm::ParameterSetDescription& desc);
+    static void fillDescription(edm::ParameterSetDescription& desc,
```
Comment (missirol) [inline L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h:65]: A trivial question: is there a naming convention/guideline for using `fillDescription` or `fillPSetDescription` in utilities used by plugins? (I just know that for plugins one must use `fillDescriptions`)

File: L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h (hunk 2 above)
Comment (Dr15Jones) [reply L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h:138]: oops. Left over from when I was running in the debugger. Thanks for the catch.

File: L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h (hunk 3 above)
Comment (Martin-Grunewald) [reply L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h:65]: Isn't fillDescription enforced by the base class, while fillPSetDescription is used to call embedded code to let them fill their parameters?

Comment (Dr15Jones) [reply L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h:65]: `fillDescriptions(edm::ConfigurationDescriptions&)` is required by the framework for modules to use if they want to validate their parameters. Code called from within `fillDescriptions` which deal with a single `edm::ParameterSetDescription` can be named however the developers like. 

For helper classes loaded via the `PluginManager` one can also have them validated via
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideConfigurationValidationAndHelp#A_Plugin_Module_Using_Another_He

which does depend on the name `fillPSetDescription` to be a static function of the plugin.

In this case, the code is not part of a plugin so the name isn't enforced by the framework. In fact, the Sources also have this sort of pattern for validation and uses `fillDescription` as the name (since it isn't a separate plugin).

https://github.com/cms-sw/cmssw/blob/master/FWCore/Sources/interface/RawInputSource.h#L21

**Comment by Dr15Jones** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
type bugfix

**Comment by Dr15Jones** [comment]
@hlt-l2 @dqm-l2 any further comments? It would be nice to get this into the IB to fix the problems seen.

File: L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h [hunk 4]
```diff
@@ -131,8 +135,15 @@ namespace l1t {
     // Register the callback function with the Framework
     // if any InputTags still need to be found.
     if (findL1TAlgBlk || findL1TExtBlk) {
-      module.callWhenNewProductsRegistered([this, findL1TAlgBlk, findL1TExtBlk, iC](auto iBranch) {
-        checkToUpdateTags(iBranch, iC, findL1TAlgBlk, findL1TExtBlk);
+      auto const* pModule = &module;
```
Comment (missirol) [inline L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h:138]: @Dr15Jones , thanks for this PR.

If I understand correctly, the best way forward would be to find all clients of `L1TGlobalUtilHelper` in CMSSW which initialise it incorrectly, fix them and then one could strip `L1TGlobalUtilHelper` of its current complexity (e.g. `existAs` calls, `checkToUpdateTags`, etc).

Would that be correct?

Comment (Dr15Jones) [reply L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h:138]: @missirol I think you are correct that once all clients of `L1TGlobalUtilHelper` do proper initialization the class could be simplified.

**Comment by missirol** [comment]
> @hlt-l2 @dqm-l2 any further comments?

Tagging @cms-sw/dqm-l2 for the review of this PR (I guess they weren't really tagged earlier).

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1
