### PR TITLE
Fix EDConsumerBase to look up consumed module label from EDAlias with product type and instance name as well

### LINKED ISSUE #30937: PathsAndConsumesOfModules can return wrong modules in conjunction with EDAlias
The following configuration
```python
import FWCore.ParameterSet.Config as cms

process = cms.Process("TEST")

process.maxEvents.input = 1
process.source = cms.Source("EmptySource")

intEventProducer = cms.EDProducer("IntProducer", ivalue = cms.int32(1))

intEventConsumer = cms.EDAnalyzer("IntTestAnalyzer",
    moduleLabel = cms.untracked.string(""),
    valueMustMatch = cms.untracked.int32(1)
)

process.intProducerFoo = intEventProducer.clone(ivalue = 1)
process.intProducerBar = intEventProducer.clone(ivalue = 2)
process.intConsumer = intEventConsumer.clone(moduleLabel = "intProducer")

process.intProducer = cms.EDAlias(
    intProducerFoo = cms.VPSet(
        cms.PSet(
            type = cms.string("edmtestIntProduct"),
        )
    ),
    intProducerBar = cms.VPSet(
        cms.PSet(
            type = cms.string("edmtestIntProduct"),
            fromProductInstance = cms.string(""),
            toProductInstance = cms.string("test"),
        )
    )
)

process.t = cms.Task(
    process.intProducerFoo,
    process.intProducerBar
)
process.p = cms.Path(
    process.intConsumer,
    process.t
)

process.Tracer = cms.Service("Tracer", dumpPathsAndConsumes = cms.untracked.bool(True))
``` 
leads to following printout from Tracer service
```
All modules and modules in the current process whose products they consume:
...
  IntTestAnalyzer/'intConsumer' consumes products from these modules:
    IntProducer/'intProducerBar'
```
while the `intProducer` is really consuming the product from `intProducerFoo`.

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR resolves https://github.com/cms-sw/cmssw/issues/30937 by making `EDConsumerBase` and `ProductRegistry` to use product type and instance name in addition to the module label when resolving alias-for module label for an EDAlias branch. 

#### PR validation:

Framework unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@wddgit @Dr15Jones Could you take a look?

**Comment by wddgit** [comment]
I read through it. It looks good to me. It should solve the problem.

**Comment by makortel** [comment]
@cmsbuild, please test

File: DataFormats/Provenance/src/ProductRegistry.cc [hunk 1]
```diff
@@ -558,6 +604,28 @@ namespace edm {
...
+    auto const target = std::tuple(kindOfType, type, moduleLabel, productInstanceName);
+    auto found =
+        std::lower_bound(transient_.aliasToOriginal_.begin(),
+                         transient_.aliasToOriginal_.end(),
+                         target,
+                         [aliasFields](auto const& item, auto const& target) { return aliasFields(item) < target; });
+    if (found == transient_.aliasToOriginal_.end() or aliasFields(*found) != target) {
+      return std::nullopt;
+    }
+    return std::get<Transients::kAliasForModuleLabel>(*found);
```
Comment (makortel) [inline DataFormats/Provenance/src/ProductRegistry.cc:626]: @Dr15Jones @wddgit 

This approach does not address with the ambiguity if an EDAlias provides e.g. `std::vector<Base>` and `std::vector<Derived>` for the same module label and product instance name, and a consumer consumes `edm::View<Base>`. I was planning to rely on the ambiguity check done also for regular products, but apparently that is done only at the time of `Event::get()` (`consumes()` alone is not sufficient).

The information on `PathsAndConsumesOfModules` will be used for module deletion (#29553; in addition to dependency graph, tracer, etc), I'm wondering if this code should actually report a dependence for each ambiguous case?

Alternatively I could think of changing already `consumes()` to trigger the ambiguity exception (but that may have other consequences).

Comment (makortel) [reply DataFormats/Provenance/src/ProductRegistry.cc:626]: In a quick chat with @Dr15Jones we concluded that it could be better to move the ambiguity exception to be thrown at "the `consumes()` time". I'm looking into that next (will be a separate PR).

Comment (makortel) [reply DataFormats/Provenance/src/ProductRegistry.cc:626]: The ambiguity exception can not generally be thrown at the beginJob based on consumes information, because the consumption of a product without an explicit process name can only be resolved at the `Event::get()` time.

Given that the ambiguity gets resolved based on products and indices (that are not touched by #29553) leaving this code as it is now could technically be safe for module deletion. However, I think it would be clearest for `PathsAndConsumesOfModules` to report dependencies on all producers of an ambiguous `get()` with `edm::View` of `EDAlias` products.

Comment (makortel) [reply DataFormats/Provenance/src/ProductRegistry.cc]: > However, I think it would be clearest for `PathsAndConsumesOfModules` to report dependencies on all producers of an ambiguous `get()` with `edm::View` of `EDAlias` products.

The just-added commit adds functionality.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones @wddgit Could you take a look again?

**Comment by wddgit** [comment]
I reviewed it and it looked good to me. +1.

It is probably not worth changing, but sometimes I wonder if the case where a module creates this View ambiguity has ever actually occurred even once in CMSSW. We have some complexity in a few places to deal with it and it might have been simpler to just check for it and make it illegal for a producer to declare it produces collections like that.

File: DataFormats/Provenance/src/ProductRegistry.cc [hunk 2]
```diff
@@ -457,6 +458,51 @@ namespace edm {
     }
     checkDictionariesOfConsumedTypes(
         productTypesConsumed, elementTypesConsumed, containedTypeMap, containedTypeToBaseTypesMap);
+
+    // Add contained types for all EDAliases
+    std::vector<decltype(transient_.aliasToOriginal_)::value_type> elementAliases;
```
[the remark this answers is not in the document]
Comment (makortel) [reply DataFormats/Provenance/src/ProductRegistry.cc:463]: The `decltype(...)` should indeed work, and I agree a type alias would more clear. Thanks for the suggestion.

**Comment by makortel** [comment]
@cmsbuild, please test

File: DataFormats/Provenance/src/ProductRegistry.cc [hunk 3]
```diff
@@ -457,6 +458,51 @@ namespace edm {
     }
     checkDictionariesOfConsumedTypes(
         productTypesConsumed, elementTypesConsumed, containedTypeMap, containedTypeToBaseTypesMap);
+
```
Comment (Dr15Jones) [inline DataFormats/Provenance/src/ProductRegistry.cc:461]: For clarity, would it be better to move all of this into a separate function?

File: FWCore/Integration/test/PathsAndConsumesOfModulesTestService.cc [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+
+    void preBeginJob(edm::PathsAndConsumesOfModulesBase const& pathsAndConsumes, edm::ProcessContext const&) const {
+      auto const& allModules = pathsAndConsumes.allModules();
+      for (auto const& moduleToCheck : modulesConsumes_) {
+        auto found =
+            std::find_if(allModules.begin(), allModules.end(), [&moduleToCheck](edm::ModuleDescription const* desc) {
+              return desc->moduleLabel() == moduleToCheck.first;
+            });
+        if (found == allModules.end()) {
+          cms::Exception ex("Assert");
```
Comment (Dr15Jones) [inline FWCore/Integration/test/PathsAndConsumesOfModulesTestService.cc:40]: These seems like a very generic exception name. How about 'TestFailure'?

**Review by Dr15Jones — COMMENTED** [review]
Reviewed all files.

**Comment by makortel** [comment]
@cmsbuild, please abort

File: DataFormats/Provenance/src/ProductRegistry.cc (hunk 3 above)
Comment (makortel) [reply DataFormats/Provenance/src/ProductRegistry.cc:461]: Thanks, will do.

File: FWCore/Integration/test/PathsAndConsumesOfModulesTestService.cc (hunk 4 above)
Comment (makortel) [reply FWCore/Integration/test/PathsAndConsumesOfModulesTestService.cc:40]: Thanks, will change.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1
