### PR TITLE
get rid of more undefined behaviour in `TrackListMerger`

### LINKED ISSUE #39229: UBSAN issue in TrackListMerger
As a follow up on https://github.com/cms-sw/cmssw/pull/37384 , the suggested change https://github.com/cms-sw/cmssw/pull/37384#issuecomment-1095361635 [a] by @mmusich works for me. Workflow `2323.4.0` did not fail [b] and ubsan issue about `RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc:451:45: runtime error: variable length array bound evaluates to non-positive value 0` is also fixed.  May be we can also move https://github.com/cms-sw/cmssw/blob/master/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc#L364 after the check [a]

@cms-sw/reconstruction-l2  what do you suggest?

[a]
``` 
+  if (ngood == 0) {
+    // output empty collections and early return
+    this->returnEmptyCollections(e);
+    return;
+  }
```

[b]
```
23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Mon Aug 29 12:01:40 2022-date Mon Aug 29 11:32:36 2022; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/39229

#### PR description:

Follow-up to https://github.com/cms-sw/cmssw/pull/37384#issuecomment-1095361635.

#### PR validation:

To be tested in this PR, according to https://github.com/cms-sw/cmssw/issues/39229#issue-1354045720 it passes integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

File: RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc [hunk 1]
```diff
@@ -446,12 +444,20 @@ void TrackListMerger::produce(edm::Event& e, const edm::EventSetup& es) {
...
+  }
+
+  statCount.begin(rSize);
   statCount.pre(ngood);
 
   //cache the id and rechits of valid hits
   typedef std::pair<unsigned int, const TrackingRecHit*> IHit;
   std::vector<std::vector<IHit>> rh1(ngood);  // "not an array" of vectors!
   //const TrackingRecHit*  fh1[ngood];  // first hit...
+
```
Comment (mandrenguyen) [inline RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc:460]: Sorry to be a pain, but you can please revert the added newline just to clean up the diff?  Thanks :-)

Comment (mmusich) [reply RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc:460]: you're welcome to do it later :)

Comment (mandrenguyen) [reply RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc:460]: It would be better if you take care of it now, after which I'll sign.

Comment (mmusich) [reply RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc:460]: as far as I am concerned this can stay open forever, not planning to push more unless there are physics relevant comments.

**Comment by mandrenguyen** [comment]
+reconstruction
It would have been preferable had the author agreed to remove the additional line break introduced by this PR, which creates a spurious diff.

**Comment by perrotta** [comment]
+1
