### PR TITLE
Fix ODR violation in L1Trigger/L1TCalorimeter

### LINKED ISSUE #1897: Fix ODR violation in L1Trigger/L1TCalorimeter
### Description

After moving code to versioned namespace, that code failed to compile which brought the problem to my attention.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Multiple different implementations for the same operator< were used in the package. The problematic templated code was changed to take the operator as one of the parameters.
- To avoid this problem in the future, all operators for a class should be declared in the package containing the class.

#### PR validation:

Code compiles. New unit tests pass.

resolves https://github.com/cms-sw/framework-team/issues/1897

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

File: L1Trigger/L1TCalorimeter/test/test_catch2_accumulatingsort.cc [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    const std::vector<int> answer = {7, 3, 9};
+    CHECK(answer == out);
+  }
+  SECTION("duplicates ascending") {
+    std::vector<int> v = {1, 2, 2, 2, 3, 4, 5, 6, 7, 8, 9};
+    std::vector<int> out;
+    const std::vector<int> answer = {1, 2, 3};
+    AccumulatingSort<int, std::greater<int>> s(3);
+    s.Merge(v, out);
+    CHECK(answer == answer);
```
Comment (BenjaminRS) [inline L1Trigger/L1TCalorimeter/test/test_catch2_accumulatingsort.cc]: should this not be `answer == out`?

File: L1Trigger/L1TCalorimeter/plugins/L1TStage2CaloLayer2Comp.cc [hunk 2]
```diff
@@ -37,11 +37,12 @@
 #include "L1Trigger/L1TCalorimeter/interface/BitonicSort.h"
 #include "DataFormats/Math/interface/LorentzVector.h"
 
-namespace l1t {
-  bool operator>(const l1t::Jet &a, l1t::Jet &b) { return a.hwPt() > b.hwPt(); }
-  bool operator>(const l1t::EGamma &a, l1t::EGamma &b) { return a.hwPt() > b.hwPt(); }
-  bool operator>(const l1t::Tau &a, l1t::Tau &b) { return a.hwPt() > b.hwPt(); }
-}  // namespace l1t
+namespace {
```
Comment (BenjaminRS) [inline L1Trigger/L1TCalorimeter/plugins/L1TStage2CaloLayer2Comp.cc:40]: Should we not keep this new `Greater` struct under the `l1t` namespace?

**Review by BenjaminRS — COMMENTED** [review]
Thank you for updating the code and fixing the ODR violations!

File: L1Trigger/L1TCalorimeter/test/test_catch2_accumulatingsort.cc (hunk 1 above)
Comment (Dr15Jones) [reply L1Trigger/L1TCalorimeter/test/test_catch2_accumulatingsort.cc]: good catch! has been fixed.

File: L1Trigger/L1TCalorimeter/plugins/L1TStage2CaloLayer2Comp.cc (hunk 2 above)
Comment (Dr15Jones) [reply L1Trigger/L1TCalorimeter/plugins/L1TStage2CaloLayer2Comp.cc:40]: The underlying cause of the _one definition rule_ violation was the symbols were globally visible. That is why I moved the functionality into an anonymous namespace (as those prevent usage outside of the file). Also, declaring globally accessible functions for a class in packages outside of the class is a good way to cause future ODRs.

**Comment by BenjaminRS** [comment]
+l1
