### PR TITLE
Fix thread safety issues in SwitchProducer ProductResolvers

### LINKED ISSUE #28680: Thread safety issue in SwitchBaseProductResolver::resolveProductImpl
The method SwitchBaseProductResolver::resolveProductImpl is called each time another module calls `edm::Event::get*` for the data product. Such can happen concurrently. However, the function is not thread safe as it calls `edm:::ProductData::unsafe_setWrapper` 

https://github.com/cms-sw/cmssw/blob/master/FWCore/Framework/src/ProductResolvers.cc#L621

The proper thing to do is to set the Wrapper during the data prefetching stage.

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR fixes three thread safety issues in SwitchProducer ProductResolvers that I realized while addressing #28680
- `SwitchBaseProductResolver::prefetchRequested_` is now re-set to `false` in `resetProductData_()`
   * Current behavior (without re-setting) could lead to starvation if there are many consumers (in Tasks) for the SwitchProducer products. This indeed happens with enhanced tests (multiple consumers, multiple threads)
- Call `ProductData::unsafe_setWrapper()` in the prefetching phase as suggested by @Dr15Jones in #28680 
   * The ordering of the tasks ensures that exactly one task is accessing the `ProductData` at the time of the call, after which the tasks for the product consumers are spawned.
- `SwitchBaseProductResolver::waitingTasks_` is reset in `resetProductData_()`
  * Current behavior (without reset) leads to product consumer tasks being spawned too early from 2nd event onwards

In addition this PR
- Moves `putProduct_()` from `SwitchBaseProductResolver` to `SwitchProducerProductResolver`
   * The `putProduct_()` should never be called from `SwitchAliasProductResolver` (and now throws an exception)
- Moves the call to `updateProvenance()` to a proper place in `SwitchProducerProductResolver`
   * The earlier placement looked suspicious (why update if got an exception), and the problem in the provenance tracking was confirmed by enhancing the tests to check the provenance information also for the test configuration where the SwitchProcucer is in a Path

Fixes #28680.

#### PR validation:

Code compiles, unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

File: FWCore/Framework/src/ProductResolvers.h [hunk 1]
```diff
@@ -40,6 +40,7 @@ namespace edm {
 
     // Give AliasProductResolver and SwitchBaseProductResolver access by moving this method to public
     void resetProductData_(bool deleteEarly) override = 0;
+    virtual ProductData const& getProductData() const = 0;
```
Comment (makortel) [inline FWCore/Framework/src/ProductResolvers.h]: I'm not very happy about exposing the `ProductData` this way. It is used here
https://github.com/cms-sw/cmssw/blob/9890e15de9fa531e391ffe4d0f5e6a3cfc6669c8/FWCore/Framework/src/ProductResolvers.cc#L659-L662
to set the Wrapper in the prefetching phase.

File: FWCore/Framework/src/ProductResolvers.h [hunk 2]
```diff
@@ -336,8 +331,17 @@ namespace edm {
...
     bool unscheduledWasNotRun_() const final { return false; }
     bool productUnavailable_() const final;
+    void resetProductData_(bool deleteEarly) final;
+
+    constexpr static const ProductStatus defaultStatus_ = ProductStatus::NotPut;
+
+    // for filter in a Path
+    // The variable is only modified or read at times where the
+    //  framework has guaranteed synchronization between write and read
+    CMS_THREAD_SAFE mutable ProductStatus status_;
```
Comment (makortel) [inline FWCore/Framework/src/ProductResolvers.h]: Contrary to my earlier thought (https://github.com/cms-sw/cmssw/pull/28667#discussion_r360576272), I believe now that this variable could stay non-atomic. The `status_` is read in `resolveProduct_()` and `putProduct_()`, and written in `putProduct_()` and `resetProductData_()`. It is not used to synchronize anything else (via memory fence). If we indeed guarantee that `resolveProduct_()` and `putProduct_()` may not be called concurrently, it should be fine as it is.

**Comment by makortel** [comment]
The failure is
```
Test provenance of merged output (Path)
...
Begin processing the 1st record. Run 1, Event 1, LumiSection 2 on stream 0 at 27-Dec-2019 21:35:13.975 CET
Begin processing the 2nd record. Run 1, Event 2, LumiSection 2 on stream 0 at 27-Dec-2019 21:35:13.977 CET
FWCore/Integration/test/SwitchProducerProvenanceAnalyzer.cc:57: void edmtest::SwitchProducerProvenanceAnalyzer::testProduct(const edm::Handle<edmtest::IntProduct>&, int, const edm::Event&) const: Assertion `productProvenance != nullptr' failed.
```
like the provenance would still not be set correctly. Somehow the failure is also in the second event (which could hint towards some other synchronization issue).

The test worked on my local tests, but after using even more threads I managed to reproduce the failure. Investigating...

**Comment by makortel** [comment]
Indeed one call to `updateProcenance()` was missing, reorganized the code such that the provenance is always updated together with setting the Wrapper.

**Comment by makortel** [comment]
@cmsbuild, please test

File: FWCore/Framework/src/ProductResolvers.cc [hunk 3]
```diff
@@ -665,21 +648,26 @@ namespace edm {
   void SwitchBaseProductResolver::resetProductData_(bool deleteEarly) {
     productData_.resetProductData();
     realProduct_.resetProductData_(deleteEarly);
-    if (not deleteEarly) {
-      status_ = defaultStatus_;
-    }
+    prefetchRequested_ = false;
+    waitingTasks_.reset();
```
Comment (Dr15Jones) [inline FWCore/Framework/src/ProductResolvers.cc]: If `deleteEarly == true` then neither of these items should be reset.

Comment (makortel) [reply FWCore/Framework/src/ProductResolvers.cc]: Other ProductResolvers seem to reset these variables unconditionally
https://github.com/cms-sw/cmssw/blob/4010528c5c1660debe651b9f69d474a7f8b5004b/FWCore/Framework/src/ProductResolvers.cc#L295-L297
https://github.com/cms-sw/cmssw/blob/4010528c5c1660debe651b9f69d474a7f8b5004b/FWCore/Framework/src/ProductResolvers.cc#L359-L362
https://github.com/cms-sw/cmssw/blob/4010528c5c1660debe651b9f69d474a7f8b5004b/FWCore/Framework/src/ProductResolvers.cc#L450-L452
https://github.com/cms-sw/cmssw/blob/4010528c5c1660debe651b9f69d474a7f8b5004b/FWCore/Framework/src/ProductResolvers.cc#L1026-L1032

Also, shouldn't the early deletion be done only after all consumers of the product have been run (i.e. no new prefetch requests are coming)? Ok, the current configuration-driven mechanism doesn't guarantee that, but at least in principle.

Comment (makortel) [reply FWCore/Framework/src/ProductResolvers.cc]: The last commit makes the resets only if `deleteEarly == false`, and also adds a unit test that fails if they would not be reset.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1
