### PR TITLE
Speed up RNTupleTempSource by caching more RNTupleViews

### LINKED ISSUE #1818: Investigate failure in 139.005
### Description

See https://github.com/cms-sw/cmssw/issues/48400

### LINKED ISSUE #48400: [RNTUPLE_X] RelVal 139.005: object of class vector<edm::StoredProductProvenance> read too few bytes
In CMSSW_15_1_RNTUPLE_X_2025-07-24-1100, RelVal 139.005 failed :

```
Begin processing the 29987th record. Run 346512, Event 5233680, LumiSection 6 on stream 0 at 24-Jun-2025 22:04:59.787 CEST
----- Begin Fatal Exception 24-Jun-2025 22:04:59 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Reading branch EventProductProvenance
   Additional Info:
      [a] Fatal Root Error: @SUB=TBufferFile::CheckByteCount
object of class vector<edm::StoredProductProvenance> read too few bytes: 8 instead of 288

----- End Fatal Exception -------------------------------------------------
```

[full log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_1_RNTUPLE_X_2025-07-24-1100/pyRelValMatrixLogs/run/139.005_AlCaPhiSym2021/step2_AlCaPhiSym2021.log#/)

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Following https://github.com/cms-sw/cmssw/pull/49902 this PR caches the RNTupleViews for the provenance and for the event history fields. The repetitive creation of these RNTupleViews was pointed by VTune profile in https://github.com/cms-sw/cmssw/issues/48400#issuecomment-3787359750.

Resolves https://github.com/cms-sw/cmssw/issues/48400
Resolves https://github.com/cms-sw/framework-team/issues/1818

#### PR validation:

Step3 of workflow 139.005 completes in ~5 minutes on 1 thread. VTune profile did not show further obvious RNTuple-related bottlenecks.

### CODE REVIEW

**Comment by makortel** [comment]
@Dr15Jones Please review carefully.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Ok, so working in one case didn't imply working everywhere.

File: FWCore/Framework/src/ProductProvenanceRetriever.cc [hunk 1]
```diff
@@ -79,6 +79,8 @@ namespace edm {
       nextRetriever_->reset();
     }
     parentProcessRetriever_ = nullptr;
+    // Allow reader to be destructed earlier than the destructor of EventPrincipal
+    provenanceReader_.reset();
```
Comment (makortel) [inline FWCore/Framework/src/ProductProvenanceRetriever.cc]: Unconditionally resetting the `provenanceReader_` is problematic. The reset is needed only when the `provenanceReader_` is set via the `deepCopy()` function
https://github.com/cms-sw/cmssw/blob/ff31a48a47d08c4fb44ae62fb198f208566e8b83/FWCore/Framework/src/ProductProvenanceRetriever.cc#L62
It is unclear to me though if resetting it to `nullptr` would be safe in that case, or if it would be better to reset it to the previous value.

Comment (makortel) [reply FWCore/Framework/src/ProductProvenanceRetriever.cc]: We changed the approach in caching the provenance view completely.

**Comment by makortel** [comment]
test parameters:
  - enable = rntuple
  - workflows_rntuple = 139.005

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
Seems good to me.

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/47071

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1
