### PR TITLE
Check for nans earlier in the template reco

### LINKED ISSUE #38869: Segmentation fault in the TrackProducer for EphemeralHLTPhysics
[as current shadow ORM]

A single job was paused while processing PromptReco for the EphemeralHLTPhysics PD due to segmentation fault in the `TrackProducer`:
```
%MSG-w BasicTrajectoryState:  TrackProducer:detachedTripletStepTracks  26-Jul-2022 20:59:11 CEST Run: 356077 Event: 94087667
BasicTrajectoryState: attempt to access errors when none available  accessing local error..
freestate pointer: parameters
x =       6.70089    -0.113416     -19.3376
p =          -nan         -nan         -nan
no error defined.

local error valid/values :0
[         -nan        -nan        -nan        -nan        -nan
          -nan        -nan        -nan        -nan        -nan
          -nan        -nan        -nan        -nan        -nan
          -nan        -nan        -nan        -nan        -nan
          -nan        -nan        -nan        -nan        -nan ]
%MSG
```
The error is locally reproducible and the job tarball (including PSet and log files) can be found here:
```
/afs/cern.ch/user/c/cmst0/public/tarballs/Run2022C/vocms013.cern.ch-391090-3-log.tar.gz
```
The full description of the issue can be found in [CMS Talk](https://cms-talk.web.cern.ch/t/paused-job-for-promptreco-ephemeralhltphysics-due-to-segfault/13318).

@mmusich , could you please have a look?

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Resolves  https://github.com/cms-sw/cmssw/issues/38869 by moving the protection of nan-s earlier in the code.

#### PR validation:

The job in https://github.com/cms-sw/cmssw/issues/38869#issue-1319496872 run successfully. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Needs to go back to 12_4_X

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix,trk

**Comment by tvami** [comment]
test parameters:
  - enable_tests = profiling

**Comment by tvami** [comment]
I assume we'd like to see the performance change, right? https://github.com/cms-sw/cmssw/pull/38881#issuecomment-1198085743

File: CondFormats/SiPixelTransient/src/SiPixelTemplate.cc [hunk 1]
```diff
@@ -1328,6 +1328,12 @@ void SiPixelTemplate::postInit(std::vector<SiPixelTemplateStore>& thePixelTemp_)
 bool SiPixelTemplate::interpolate(int id, float cotalpha, float cotbeta, float locBz, float locBx) {
   // Interpolate for a new set of track angles
 
+  //check for nan's
+  if (!edm::isFinite(cotalpha) || !edm::isFinite(cotbeta)) {
```
Comment (mmusich) [inline CondFormats/SiPixelTransient/src/SiPixelTemplate.cc:1332]: I think you want to maintain in the clause `#ifndef SI_PIXEL_TEMPLATE_STANDALONE` here, right?

File: CondFormats/SiPixelTransient/src/SiPixelTemplate2D.cc [hunk 2]
```diff
@@ -626,6 +626,12 @@ bool SiPixelTemplate2D::getid(int id) {
 bool SiPixelTemplate2D::interpolate(int id, float cotalpha, float cotbeta, float locBz, float locBx) {
   // Interpolate for a new set of track angles
 
+  //check for nan's
+  if (!edm::isFinite(cotalpha) || !edm::isFinite(cotbeta)) {
```
Comment (mmusich) [inline CondFormats/SiPixelTransient/src/SiPixelTemplate2D.cc:630]: I think you want to maintain in the clause `#ifndef SI_PIXEL_TEMPLATE_STANDALONE` here, right?

**Comment by mmusich** [comment]
> I assume we'd like to see the performance change, right? https://github.com/cms-sw/cmssw/pull/38881#issuecomment-1198085743

I initially misunderstood the code and interpreted that the check was done only in the standalone case, but it's actually the other way around (it is checked in the cmssw job but not in the standalone pixelAV simulation), so performance should not be a concern (if anything few more instructions should be skipped).

**Comment by tvami** [comment]
@cmsbuild , please test

File: CondFormats/SiPixelTransient/src/SiPixelTemplate.cc (hunk 1 above)
Comment (mmusich) [reply CondFormats/SiPixelTransient/src/SiPixelTemplate.cc:1332]: That's how the check was done before, and it is therefore the minimal fix.

Comment (tvami) [reply CondFormats/SiPixelTransient/src/SiPixelTemplate.cc:1332]: I spoke to Morris, he says I can add it for the standalone too.

Comment (mmusich) [reply CondFormats/SiPixelTransient/src/SiPixelTemplate.cc:1332]: Why was not done like that at https://github.com/cms-sw/cmssw/pull/34846 ?
Please clarify

Comment (tvami) [reply CondFormats/SiPixelTransient/src/SiPixelTemplate.cc:1332]: Oz didnt ask Morris, I did... That's just it :)

**Comment by tvami** [comment]
urgent
 * needed for data-taking

**Comment by clacaputo** [comment]
+reconstruction

- fix #38869 
- successfully tested

**Comment by tvami** [comment]
+db
 * signing for myself just because of the urgency
 * anyway tests pass, PR is in line with the description
