### PR TITLE
disable ubsan checks for some global summary functions

### LINKED ISSUE #1610: Address UBSAN runtime errors in doBeginRunSummary_
### Description

UBSAN jobs are dying in global `doBeginRun` run summary, including the framework unit test TestFWCoreFrameworkGlobalStreamOne:
```
runtime error: execution reached an unreachable program point
    #0 0x147bd39c8fce in virtual thunk to edm::global::impl::RunSummaryCacheHolder<edm::global::EDProducerBase, edmtest::global::(anonymous namespace)::UnsafeCache>::doBeginRunSummary_(edm::Run const&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02910/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_UBSAN_X_2025-10-10-2300/lib/el8_amd64_gcc13/pluginTestGlobalModules.so+0x3c8fce) (BuildId: 5dbad5970ce592e300ee447a4812d9c46dd299b3)
    #1 0x147c07f56ff2 in edm::global::EDProducerBase::doBeginRun(edm::RunTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/global/EDProducerBase.cc:162
    #2 0x147c07eb11ff in edm::WorkerT<edm::global::EDProducerBase>::implDoBegin(edm::RunTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/WorkerT.cc:464
```

See https://github.com/cms-sw/cmssw/issues/49151

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

UBSAN jobs are failing in recent IBs with the runtime error `unreachable program point`. This is mostly seen in NANOAOD production jobs that read run products at BeginRun, but also appears in the framework `TestFWCoreFrameworkGlobalStreamOne` unit test.  See #49151 for details.

This PR disables UBSAN checks for the problematic routines.  While `unreachable program point` usually means some undefined behavior that the optimizer is trying to take advantage of, no UB has been found.  Selective disabling of the UBSAN checks also failed to work around the problem, so this PR completely disables UBSAN for the routines in question.

Resolves #49151
Resolves https://github.com/cms-sw/framework-team/issues/1610

#### PR validation:

Compiles, verified to fix the `TestFWCoreFrameworkGlobalStreamOne` unit test.  Purely technical fix.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test for CMSSW_16_0_UBSAN_X

**Comment by makortel** [comment]
Visually looks ok to me. @smuzaffar What do you think?

**Comment by makortel** [comment]
>```
> ---> test TestFWCoreFrameworkGlobalStreamOne had ERRORS
>```

The test failed with
```
���H�:1082210368:5331: runtime error: execution reached an unreachable program point
    #0 0x14d33fcbd03e in virtual thunk to edm::limited::impl::RunCacheHolder<edm::limited::EDFilterBase, edmtest::limited::(anonymous namespace)::Cache>::doBeginRun_(edm::Run const&, edm::EventSetup const&) (/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_16_0_UBSAN_X_2025-11-03-2300/lib/el8_amd64_gcc13/pluginTestLimitedModules.so+0x2bd03e) (BuildId: 0720788e68a71a3f67da93fa0ee69f8347df9dcc)
    #1 0x14d375c35242 in edm::limited::EDFilterBase::doBeginRun(edm::RunTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/limited/EDFilterBase.cc:139
    #2 0x14d375b674cf in edm::WorkerT<edm::limited::EDFilterBase>::implDoBegin(edm::RunTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/WorkerT.cc:464
    #3 0x14d3751e020e in edm::workerhelper::CallImpl<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::call(edm::Worker*, edm::StreamID, edm::RunTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*, edm::GlobalContext const*) src/FWCore/Framework/interface/maker/Worker.h:638
    #4 0x14d3751e020e in edm::Worker::runModule<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}::operator()() const src/FWCore/Framework/interface/maker/Worker.h:1183
    #5 0x14d3751f30d1 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}) /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_UBSAN_X_2025-11-03-2300/src/FWCore/Utilities/interface/ConvertException.h:21
    #6 0x14d3751f354b in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*) src/FWCore/Framework/interface/maker/Worker.h:1182
    #7 0x14d3751f354b in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*) src/FWCore/Framework/interface/maker/Worker.h:1096
    #8 0x14d3751f425a in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}::operator()() const src/FWCore/Framework/interface/maker/Worker.h:444
    #9 0x14d3751f425a in edm::LimitedTaskQueue::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(tbb::detail::d2::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&)::{lambda()#1}::operator()() /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_UBSAN_X_2025-11-03-2300/src/FWCore/Concurrency/interface/LimitedTaskQueue.h:121
    #10 0x14d3751f425a in edm::SerialTaskQueue::QueuedTask<edm::LimitedTaskQueue::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(tbb::detail::d2::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_UBSAN_X_2025-11-03-2300/src/FWCore/Concurrency/interface/SerialTaskQueue.h:177
    #11 0x14d373957b3b in operator() src/FWCore/Concurrency/src/SerialTaskQueue.cc:46
    #12 0x14d373957b3b in task_ptr_or_nullptr_impl<const edm::SerialTaskQueue::spawn(TaskBase&)::<lambda()>&> /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/task_group.h:149
    #13 0x14d373957b3b in task_ptr_or_nullptr<const edm::SerialTaskQueue::spawn(TaskBase&)::<lambda()>&> /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/task_group.h:159
    #14 0x14d373957b3b in execute /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/task_group.h:101
    #15 0x14d3774b62f2 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter>(tbb::detail::d1::task*, tbb::detail::r1::external_waiter&) src/tbb/task_dispatcher.h:344
    #16 0x14d3774b62f2 in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter>(tbb::detail::d1::task*, tbb::detail::r1::external_waiter&) src/tbb/task_dispatcher.h:487
    #17 0x14d3774b62f2 in tbb::detail::r1::task_dispatcher::execute_and_wait(tbb::detail::d1::task*, tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&) src/tbb/task_dispatcher.cpp:169
    #18 0x14d375111655 in tbb::detail::d1::wait(tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&) /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/detail/_task.h:242
    #19 0x14d375111655 in tbb::detail::d2::task_group_base::wait()::{lambda()#1}::operator()() const /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/task_group.h:599
    #20 0x14d375111655 in void tbb::detail::d0::try_call_proxy<tbb::detail::d2::task_group_base::wait()::{lambda()#1}>::on_completion<tbb::detail::d2::task_group_base::wait()::{lambda()#2}>(tbb::detail::d2::task_group_base::wait()::{lambda()#2}) /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/detail/_template_helpers.h:234
    #21 0x14d375111655 in tbb::detail::d2::task_group_base::wait() /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/task_group.h:600
    #22 0x14d375111655 in edm::FinalWaitingTask::wait() /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_UBSAN_X_2025-11-03-2300/src/FWCore/Concurrency/interface/FinalWaitingTask.h:42
    #23 0x14d37505942c in edm::EventProcessor::processRuns() src/FWCore/Framework/src/EventProcessor.cc:1195
    #24 0x14d3750a4596 in processRuns src/FWCore/Framework/src/TransitionProcessors.icc:84
    #25 0x14d3750a4596 in processFiles src/FWCore/Framework/src/TransitionProcessors.icc:115
    #26 0x14d3750a4596 in operator() src/FWCore/Framework/src/EventProcessor.cc:949
    #27 0x14d3750a4596 in wrap<edm::EventProcessor::runToCompletion()::<lambda()> > /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_UBSAN_X_2025-11-03-2300/src/FWCore/Utilities/interface/ConvertException.h:21
    #28 0x14d3750a4596 in edm::EventProcessor::runToCompletion() src/FWCore/Framework/src/EventProcessor.cc:938
    #29 0x40a009 in operator() src/FWCore/Framework/bin/cmsRun.cpp:281
    #30 0x40a009 in operator() /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/task_arena.h:71
    #31 0x14d3774a58c1 in tbb::detail::r1::task_arena_impl::execute(tbb::detail::d1::task_arena_base&, tbb::detail::d1::delegate_base&) src/tbb/arena.cpp:860
    #32 0x40d463 in execute_impl<void, main(int, char const**)::<lambda()>::<lambda()> > /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/task_arena.h:304
    #33 0x40d463 in execute<main(int, char const**)::<lambda()>::<lambda()> > /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/external/tbb/v2022.3.0-be320b1b82e025fbed5ae22f47d43c2d/include/oneapi/tbb/task_arena.h:527
    #34 0x40d463 in operator() src/FWCore/Framework/bin/cmsRun.cpp:264
    #35 0x407f84 in wrap<main(int, char const**)::<lambda()> > /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02914/el8_amd64_gcc13/cms/cmssw/CMSSW_16_0_UBSAN_X_2025-11-03-2300/src/FWCore/Utilities/interface/ConvertException.h:21
    #36 0x407f84 in main src/FWCore/Framework/bin/cmsRun.cpp:104
    #37 0x14d3708637e4 in __libc_start_main (/lib64/libc.so.6+0x3a7e4) (BuildId: 9846edf82646848f2857c47c5a2eb71c288059ec)
    #38 0x40805d in _start (/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_16_0_UBSAN_X_2025-11-03-2300/bin/el8_amd64_gcc13/cmsRun+0x40805d) (BuildId: f6112ffdc7c6766143da9e5135fb873567327930)
```

**Comment by dan131riley** [comment]
Interesting.  I only did the global versions, not limited (or any others).  It doesn't replicate on my development system, but does on lxplus.  It does seem to be somewhat probabilistic, I think it depends on the alignment of the `this` pointer after it has been offset in the thunk for the virtual inheritance.

**Comment by makortel** [comment]
@cmsbuild, please test for CMSSW_16_0_UBSAN_X

File: FWCore/Utilities/interface/disable_ubsan.h [hunk 1]
```diff
@@ -0,0 +1,13 @@
+#ifndef FWCore_Utilites_disable_ubsan_h
+#define FWCore_Utilites_disable_ubsan_h
+// With gcc 13.4.0, some summary routines are failing with unreachable program point
+// UBSAN errors.  No UB has been identified, so for now this workaround suppresses
+// UBSAN checking for the routines that are failing.
+//
+// details at https://github.com/cms-sw/cmssw/issues/49151
```
Comment (makortel) [inline FWCore/Utilities/interface/disable_ubsan.h]: I wonder if it would be better to move this comment to the places where the `DISABLE_UBSAN` is being used?

I see the `DISABLE_UBSAN` might end up being used for other problems as well.

Comment (dan131riley) [reply FWCore/Utilities/interface/disable_ubsan.h]: I moved the detailed comments to the places it is used, and made the comment in the new header file more generic.  Seems better, and should address this comment.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test for CMSSW_16_0_UBSAN_X

**Comment by makortel** [comment]
@cmsbuild, please test

Looks like the default tests got lost

**Comment by makortel** [comment]
+core

**Comment by ftenchini** [comment]
+1
