### PR TITLE
Deleted non-consumed modules do not keep early-deleted data products alive

### LINKED ISSUE #36863: Data products eligible for early deletion kept alive by modules that are not run
Investigation on unexpected behavior of early deletion in https://github.com/cms-sw/cmssw/pull/36793 pointed out that if a data product is marked by being potentially consumed by an EDModule that is never run because nothing consumes its products. This behavior appears to be independent of whether such "non-consumed unscheduled modules" are being deleted or not.

Some more details of the exact use case can be found from https://github.com/cms-sw/cmssw/pull/36793#issuecomment-1028039423

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/36863. The effect is achieved by moving the call to `initializeEarlyDelete()` from the constructor of `StreamSchedule` to right after the non-consumed unscheduled have been deleted.

#### PR validation:

Framework unit tests pass

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
The unit test error is
```
%MSG-s ExternalProcess:  ExternalGeneratorFilter:gen2@beginStream  04-Feb-2022 16:10:38 CET BeforeEvents
1 starting external process 

%MSG
26331_1 process: initializing 
----- Begin Fatal Exception 04-Feb-2022 16:10:42 CET-----------------------
An exception of category 'StdException' occurred while
   [0] Calling beginStream for module ExternalGeneratorFilter/'gen2'
Exception Message:
A std::exception was thrown.
boost::interprocess_exception::library_error
----- End Fatal Exception -------------------------------------------------
```
I'm not really sure what to make of it...

**Comment by makortel** [comment]
(updated the test as I realized that it wasn't actually testing the intended behavior)

**Comment by makortel** [comment]
@Dr15Jones Could you review this?

File: FWCore/Framework/src/StreamSchedule.cc [hunk 1]
```diff
@@ -236,28 +231,17 @@ namespace edm {
     }
     number_of_unscheduled_modules_ = unscheduledLabels.size();
 
-    initializeEarlyDelete(*modReg, opts, preg, allowEarlyDelete);
+    //initializeEarlyDelete(*modReg, opts, preg, allowEarlyDelete);
```
Comment (Dr15Jones) [inline FWCore/Framework/src/StreamSchedule.cc:234]: please remove

File: FWCore/Framework/interface/Schedule.h [hunk 2]
```diff
@@ -277,6 +277,8 @@ namespace edm {
     /// Deletes module with label iLabel
     void deleteModule(std::string const& iLabel, ActivityRegistry* areg);
 
+    void initializeEarlyDelete(std::vector<std::string> branchesToDeleteEarly, edm::ProductRegistry const& preg);
```
Comment (Dr15Jones) [inline FWCore/Framework/interface/Schedule.h:280]: I do not like the use of passing by value here. The internals of the code do not care about it. I understand that when called, the variable is supposed to be cleared, but that is more a matter of the call sight understanding the lifetime of the variable and NOT a property of this function.

File: FWCore/Framework/src/EventProcessor.cc [hunk 3]
```diff
@@ -638,6 +643,12 @@ namespace edm {
         }
       }
     }
+    // Initialize after the deletion of non-consumed unscheduled
+    // modules to avoid non-consumed non-run modules to keep the
+    // products unnecessarily alive
+    if (not branchesToDeleteEarly_.empty()) {
+      schedule_->initializeEarlyDelete(std::move(branchesToDeleteEarly_), *preg_);
```
Comment (Dr15Jones) [inline FWCore/Framework/src/EventProcessor.cc:650]: I'd prefer an explicit line to clear the memory as it makes it easier to understand the intent.

File: FWCore/Framework/src/StreamSchedule.cc [hunk 4]
```diff
@@ -81,51 +81,48 @@ namespace edm {
       return ptr;
     }
 
-    void initializeBranchToReadingWorker(ParameterSet const& opts,
+    void initializeBranchToReadingWorker(std::vector<std::string> vBranchesToDeleteEarly,
                                          ProductRegistry const& preg,
                                          std::multimap<std::string, Worker*>& branchToReadingWorker) {
-      // See if any data has been marked to be deleted early (removing any duplicates)
-      auto vBranchesToDeleteEarly = opts.getUntrackedParameter<std::vector<std::string>>("canDeleteEarly");
-      if (not vBranchesToDeleteEarly.empty()) {
```
Comment (Dr15Jones) [inline FWCore/Framework/src/StreamSchedule.cc:89]: Decided not to keep the optimization?

**Review by Dr15Jones — CHANGES_REQUESTED** [review]

File: FWCore/Framework/src/StreamSchedule.cc (hunk 1 above)
Comment (makortel) [reply FWCore/Framework/src/StreamSchedule.cc:234]: Thanks

File: FWCore/Framework/src/StreamSchedule.cc (hunk 4 above)
Comment (makortel) [reply FWCore/Framework/src/StreamSchedule.cc:89]: This is now handled in `EventProcessor` by calling the `initializeEarlyDelete()` (that ends up calling this function) only if the `canDeleteEarly` is not empty
https://github.com/cms-sw/cmssw/blob/70829468cc89bee72d6c5205ed931ca1609bb2bd/FWCore/Framework/src/EventProcessor.cc#L649-L650

File: FWCore/Framework/interface/Schedule.h (hunk 2 above)
Comment (makortel) [reply FWCore/Framework/interface/Schedule.h:280]: Yeah, that's probably better way. I was originally hoping to avoid making copies of the vector (that gets modified in `initializeBranchToReadingWorker()`), but since the vector (currently) needs to be copied for each `StreamSchedule`, it wouldn't change anything for the copies to pass the `vector` here by reference-to-`const` and make the copy in `initializeBranchToReadingWorker()`.

File: FWCore/Framework/src/EventProcessor.cc (hunk 3 above)
Comment (makortel) [reply FWCore/Framework/src/EventProcessor.cc:650]: Thanks, I'll add.

**Comment by makortel** [comment]
Addressed review comments (thanks Chris!).

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
@makortel also the reference profiling in the IB has changed, unfortunately, as you observed, the issue looks still unresolved

**Comment by makortel** [comment]
Given https://github.com/cms-sw/cmssw/pull/36793#issuecomment-1034358194 the residual issue with early deletion in https://github.com/cms-sw/cmssw/pull/36793 was not caused by the framework.

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1
