### PR TITLE
Escape special characters in most JobReport XML elements

### LINKED ISSUE #1874: Fix job report XML parsing failure in Tier0 replay
### Description

See https://github.com/cms-sw/cmssw/issues/50020

### LINKED ISSUE #50020: Failure to parse FrameworkJobReport.xml in Tier-0 replay
Hello all,

Tier-0 recently deployed a replay for `CMSSW_16_0_0_patch1` to test on cosmics data ([cmstalk](https://cms-talk.web.cern.ch/t/replay-for-cmssw-16-0-0-patch1/141665) ).

After merge jobs finish successfully, the WMAgent parses the `FrameworkJobReport.xml` and fails due to a `invalid token` in the `<PFN>` line:

```
Error reading XML job report file, possibly corrupt XML File:
Details: <@========== WMException Start ==========@>
Exception Class: FwkJobReportException
Message: Error reading XML job report file, possibly corrupt XML File:
Details: not well-formed (invalid token): line 12, column 213
	ClassName : None
	ModuleName : WMCore.FwkJobReport.Report
	MethodName : parse
	ClassInstance : None
	FileName : /srv/job/WMCore.zip/WMCore/FwkJobReport/Report.py
	LineNumber : 157
	ErrorNr : 0

Traceback: 
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/Report.py", line 145, in parse
    xmlToJobReport(self, xmlfile)

  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/XMLParser.py", line 566, in xmlToJobReport
    node = xmlFileToNode(xmlFile)

  File "/srv/job/WMCore.zip/WMCore/Algorithms/ParseXMLFile.py", line 64, in xmlFileToNode
    expat_parse(open(reportFile, 'rb'),

  File "/srv/job/WMCore.zip/WMCore/Algorithms/ParseXMLFile.py", line 88, in expat_parse
    parser.ParseFile(f)

<@---------- WMException End ----------@>
```

From which line 12 is:
```
<PFN>root://eoscms.cern.ch//eos/cms/tier0/store/unmerged/express/Tier0_REPLAY_2026/ExpressCosmics/FEVT/Express-v3152115/000/390/094/00000/b4738d4f-e3e7-4ff7-9a22-df9c053fc23f.root?eos.app=cmst0&scitag.flow=196664</PFN>
```

The issue points to the `&` in `eos.app=cmst0&scitag.flow=196664`.

I placed a tarball in 
```
/eos/home-c/cmst0/public/PausedJobs/Commissioning2026/Replay_CMSSW_16_0_0_patch1/FrameworkJobReport/vocms0500.cern.ch-2202-3-log.tar.gz
```

For further context, I commented this in https://github.com/cms-sw/cmssw/issues/47517#issuecomment-3842699629

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

https://github.com/cms-sw/cmssw/issues/50020 reports a parsing problem of framework job report XML in Tier0 when `&` is added to the PFN (this can happen with https://github.com/cms-sw/cmssw/pull/49740). Following suggestion https://github.com/cms-sw/cmssw/issues/47555#issuecomment-2718867578 this PR adds `addElement()` function that uses tinyxml2 to properly escape special characters.

The string concatenation could be reduced further (as suggested in https://github.com/cms-sw/cmssw/issues/47555#issuecomment-2718867578), but because the main purpose of this PR is to be a hot fix (and it is already quite large for one), I'd leave those to later time.

Resolves https://github.com/cms-sw/cmssw/issues/50020
Resolves https://github.com/cms-sw/framework-team/issues/1874

#### PR validation:

`FWCore/MessageService` and `FWCore/MessageLogger` unit tests pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 16_0_X

### CODE REVIEW

**Comment by makortel** [comment]
urgent

**Comment by makortel** [comment]
test parameters:
  - full_cmssw = true

**Comment by makortel** [comment]
@cmsbuild, please test

I want to catch all possible tests using the job report

**Comment by makortel** [comment]
type bugfix

**Comment by makortel** [comment]
@Dr15Jones Please review

File: FWCore/MessageLogger/interface/xmlUtils.h [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+#include <ostream>
+#include <string_view>
+
+/**
+ * These are really an implementation detail of JobReport, but are in interface because of tests
+ */
+namespace edm::xml {
+  template <typename T>
+  void addElement(char const* elementName, T&& elementValue, std::string_view suffix, std::ostream& os) {
+    tinyxml2::XMLDocument doc;
```
Comment (Dr15Jones) [inline FWCore/MessageLogger/interface/xmlUtils.h:16]: Is there any overhead in creating a doc each time?

File: FWCore/MessageLogger/src/JobReport.cc [hunk 2]
```diff
@@ -64,23 +65,22 @@ namespace edm {
...
   S& print(S& os, JobReport::OutputFile const& f) {
-    tinyxml2::XMLDocument doc;
     formatFile(f, os);
-    os << "\n<OutputModuleClass>" << doc.NewText(f.outputModuleClassName.c_str())->Value() << "</OutputModuleClass>";
-    os << "\n<TotalEvents>" << f.numEventsWritten << "</TotalEvents>\n";
-    os << "\n<DataType>" << doc.NewText(f.dataType.c_str())->Value() << "</DataType>\n";
-    os << "\n<BranchHash>" << doc.NewText(f.branchHash.c_str())->Value() << "</BranchHash>\n";
+    os << "\n";
+    xml::addElement("OutputModuleLabel", f.moduleLabel, "\n", os);
+    xml::addElement("TotalEvens", f.numEventsWritten, "\n\n", os);
```
Comment (Dr15Jones) [inline FWCore/MessageLogger/src/JobReport.cc]: TotalEvents

File: FWCore/MessageLogger/src/JobReport.cc [hunk 3]
```diff
@@ -64,23 +65,22 @@ namespace edm {
    */
   template <typename S>
   S& print(S& os, JobReport::InputFile const& f) {
-    tinyxml2::XMLDocument doc;
-    os << "\n<InputFile>";
+    os << "\n<InputFile>\n";
```
Comment (Dr15Jones) [inline FWCore/MessageLogger/src/JobReport.cc]: Where is the close for this element?

File: FWCore/MessageService/test/makeJobReport.cpp [hunk 4]
```diff
@@ -4,11 +4,12 @@
 #include <string>
 #include <vector>
 
+#include "tinyxml2.h"
```
Comment (Dr15Jones) [inline FWCore/MessageService/test/makeJobReport.cpp]: Why is this needed?

File: FWCore/MessageService/test/testJobReportXMLUtils.cpp [hunk 5]
```diff
@@ -0,0 +1,32 @@
+#define CATCH_CONFIG_MAIN
```
Comment (Dr15Jones) [inline FWCore/MessageService/test/testJobReportXMLUtils.cpp]: I do t think that is needed anymore

Comment (makortel) [reply FWCore/MessageService/test/testJobReportXMLUtils.cpp]: Ok, so it seems (it is still specified in many places including FWCore)

File: FWCore/MessageService/test/makeJobReport.cpp (hunk 4 above)
Comment (makortel) [reply FWCore/MessageService/test/makeJobReport.cpp]: Leftover from an attempt to use tinyxml2 to verify the XML correctness (it turned out to be to lenient, at least it allows literal `&` in the XML document). Will remove.

File: FWCore/MessageLogger/src/JobReport.cc (hunk 3 above)
Comment (makortel) [reply FWCore/MessageLogger/src/JobReport.cc]: Apparently here
https://github.com/cms-sw/cmssw/blob/4e8ab14728a1d213c2ebe671addf4e7538a204fa/FWCore/MessageLogger/src/JobReport.cc#L168-L176

File: FWCore/MessageLogger/src/JobReport.cc (hunk 2 above)
Comment (makortel) [reply FWCore/MessageLogger/src/JobReport.cc]: Thanks

File: FWCore/MessageLogger/src/JobReport.cc (hunk 3 above)
Comment (Dr15Jones) [reply FWCore/MessageLogger/src/JobReport.cc]: Maybe we should consider moving the opening to the same function in the future.

File: FWCore/MessageLogger/interface/xmlUtils.h (hunk 1 above)
Comment (makortel) [reply FWCore/MessageLogger/interface/xmlUtils.h:16]: I wondered the same. Running the `makeJobReport` test program after the first commit through MaxMemoryPreload shows
```
Memory Report: total memory requested: 38808
Memory Report:  max memory used: 11800
Memory Report:  presently used: 952
Memory Report:  # allocations calls:   132
Memory Report:  # deallocations calls: 133
```
and with the second commit
```
Memory Report: total memory requested: 382165
Memory Report:  max memory used: 16312
Memory Report:  presently used: 952
Memory Report:  # allocations calls:   359
Memory Report:  # deallocations calls: 360
```
so there indeed seems to be a cost with it (or with the `XMLPrinter` on the previous line).

**Comment by makortel** [comment]
Updated with the straightforward fixes.

**Comment by makortel** [comment]
@cmsbuild, please test

File: FWCore/MessageLogger/src/JobReport.cc (hunk 3 above)
Comment (makortel) [reply FWCore/MessageLogger/src/JobReport.cc]: Ideally I agree. It is far from clear to me though where this `print()` is called from (well, it is called from `operator<<()`, but I couldn't quickly find where that `operator<<()` is called from).

Comment (makortel) [reply FWCore/MessageLogger/src/JobReport.cc]: > but I couldn't quickly find where that `operator<<()` is called from).

Ah, it is actually
https://github.com/cms-sw/cmssw/blob/4e8ab14728a1d213c2ebe671addf4e7538a204fa/FWCore/MessageLogger/src/JobReport.cc#L170
Then moving the `</InputFile>` to the same function would be easy.

File: FWCore/MessageLogger/interface/xmlUtils.h (hunk 1 above)
Comment (makortel) [reply FWCore/MessageLogger/interface/xmlUtils.h:16]: Reusing the `XMLDocument` and `XMLPrinter` across the `addElement()` calls in a similar fashion as the `XMLDocument` was reused before this PR results in
```
Memory Report: total memory requested: 60023
Memory Report:  max memory used: 16152
Memory Report:  presently used: 952
Memory Report:  # allocations calls:   190
Memory Report:  # deallocations calls: 191
```
I guess the `XMLPrinter` adds more (I could test that tomorrow), but if that is the case, it seems unavoidable since the use of the `XMLPrinter` is the main point.

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/47071

**Comment by mandrenguyen** [comment]
+1
