### PR TITLE
fixes for vector size handling and spurious wakeups in TimeStudyModules

### LINKED ISSUE #1321: Investigate TestFWCoreModules failure
### Description

TestFWCoreModules in CMSSW_15_1_UBSAN_X_2025-03-26-2300 crashed with binding to a null pointer followed by a segmentation fault.  Review the timestudy module for possible vector handling errors.

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_iterator.h:1096:17: runtime error: reference binding to null pointer of type 'int'
    #0 0x14b729a4d6ca in __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator*() const /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_iterator.h:1096
    #1 0x14b729a4d6ca in timestudy::SleepingServer::threadWork() src/FWCore/Modules/src/TimeStudyModules.cc:246
    #2 0x14b7386d8a72 in execute_native_thread_routine ../../../../../libstdc++-v3/src/c++11/thread.cc:82
    #3 0x14b737c061c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #4 0x14b7382638d2 in __GI___clone (/lib64/libc.so.6+0x398d2)

src/FWCore/Modules/src/TimeStudyModules.cc:246:23: runtime error: load of null pointer of type 'int'
    #0 0x14b729a4d742 in timestudy::SleepingServer::threadWork() src/FWCore/Modules/src/TimeStudyModules.cc:246
    #1 0x14b7386d8a72 in execute_native_thread_routine ../../../../../libstdc++-v3/src/c++11/thread.cc:82
    #2 0x14b737c061c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #3 0x14b7382638d2 in __GI___clone (/lib64/libc.so.6+0x398d2)
```

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

TestFWCoreModules in FWCore/Modules has a rare failure mode, most recently seen in CMSSW_15_1_UBSAN_X_2025-03-26-2300, with UBSAN warnings
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_iterator.h:1096:17: runtime error: reference binding to null pointer of type 'int'
    #0 0x14b729a4d6ca in __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >::operator*() const /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_iterator.h:1096
    #1 0x14b729a4d6ca in timestudy::SleepingServer::threadWork() src/FWCore/Modules/src/TimeStudyModules.cc:246
    #2 0x14b7386d8a72 in execute_native_thread_routine ../../../../../libstdc++-v3/src/c++11/thread.cc:82
    #3 0x14b737c061c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #4 0x14b7382638d2 in __GI___clone (/lib64/libc.so.6+0x398d2)

src/FWCore/Modules/src/TimeStudyModules.cc:246:23: runtime error: load of null pointer of type 'int'
    #0 0x14b729a4d742 in timestudy::SleepingServer::threadWork() src/FWCore/Modules/src/TimeStudyModules.cc:246
    #1 0x14b7386d8a72 in execute_native_thread_routine ../../../../../libstdc++-v3/src/c++11/thread.cc:82
    #2 0x14b737c061c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #3 0x14b7382638d2 in __GI___clone (/lib64/libc.so.6+0x398d2)
```
followed by a segmentation violation.  This PR corrects two issues (found by code inspection) where the vector size or capacity wasn't being correctly maintained, and one issue (found through additional debugging) where spurious wakeups could be triggered when there were no waiting streams to process.

Resolves https://github.com/cms-sw/framework-team/issues/1321

#### PR validation:

Technical fix.  Without the change, the crash was moderately reproducible.  With these modifications, no test failures have been observed.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

File: FWCore/Modules/src/TimeStudyModules.cc [hunk 1]
```diff
@@ -261,6 +262,7 @@ namespace timestudy {
         }
       }
       waitingTaskPerStream_.clear();
+      waitingTaskPerStream_.resize(waitingTaskPerStream_.capacity());
```
Comment (makortel) [inline FWCore/Modules/src/TimeStudyModules.cc:265]: At this stage the thread is about to end, so it is not clear to me why the resizing the `waitingTaskPerStream_` would help. Nothing should access the `waitingTaskPerStream_` at this point.

Or is the idea to make the `asyncWork()` to not write to invalid memory? In that case, how about changing the `[]` to `at()` there?

**Review by makortel — COMMENTED** [review]
Thanks @dan131riley! I have a few questions, mostly for me to understand the situation better.

File: FWCore/Modules/src/TimeStudyModules.cc [hunk 2]
```diff
@@ -227,12 +227,13 @@ namespace timestudy {
...
       }
       //every running stream is now waiting
-      return waitingStreams_.size() == activeStreams_;
+      return !waitingStreams_.empty() and waitingStreams_.size() == activeStreams_;
     }
 
     void threadWork() {
       while (not stopProcessing_.load()) {
         std::vector<int> streamsToProcess;
+        streamsToProcess.reserve(waitingStreams_.capacity());
```
Comment (Dr15Jones) [inline FWCore/Modules/src/TimeStudyModules.cc:236]: This is a race condition. In order to interact with `waitingStreams_` the `mutex_` must be taken.

[the remark this answers is not in the document]
Comment (Dr15Jones) [reply FWCore/Modules/src/TimeStudyModules.cc:236]: It would be safe to do
```suggestion
        streamsToProcess.reserve(waitTimesPerStreams_.size());
```
As the size is the number of streams and that vector never changes its size once it is made.

**Comment by Dr15Jones** [comment]
@dan131riley thought on the outstanding comments?

**Comment by makortel** [comment]
@dan131riley ping

File: FWCore/Modules/src/TimeStudyModules.cc [hunk 3]
```diff
@@ -227,12 +227,13 @@ namespace timestudy {
         return true;
       }
       //every running stream is now waiting
-      return waitingStreams_.size() == activeStreams_;
+      return !waitingStreams_.empty() and waitingStreams_.size() == activeStreams_;
```
[the remark this answers is not in the document]
Comment (dan131riley) [reply FWCore/Modules/src/TimeStudyModules.cc:235]: Protection against spurious wakeups is the only fix that I'm sure is necessary, but I don't actually know that it is sufficient.

File: FWCore/Modules/src/TimeStudyModules.cc (hunk 1 above)
Comment (dan131riley) [reply FWCore/Modules/src/TimeStudyModules.cc:271]: The way I think about it, the vector capacities should be an invariant, and the size to where possible.  Multi-thread access is easier to reason about if you don't have to worry about iterator invalidation, though it's true this one doesn't really matter.

File: FWCore/Modules/src/TimeStudyModules.cc (hunk 2 above)
[the remark this answers is not in the document]
Comment (dan131riley) [reply FWCore/Modules/src/TimeStudyModules.cc]: It's not just memory allocation optimization, it's primarily so the vector never resizes after it is swapped into waitingStreams_.  Size to reserve changed as suggested.

Comment (dan131riley) [reply FWCore/Modules/src/TimeStudyModules.cc]: waitingStreams_.capacity() ought to be invariant with these changes, but waitTimesPerStream_.size() is a better choice.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1
