### PR TITLE
Triton test fixes

### LINKED ISSUE #34547: SonicTriton test failures in GPU IBs
The SonicTriton tests have been failing in GPU IBs at least since CMSSW_12_0_GPU_X_2021-07-12-2300 with
```
%MSG-i TritonService:  AfterModConstruction 19-Jul-2021 01:07:23 UTC pre-events
cmsTriton -P -1 -p 6853 -v -n triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b -m /cvmfs/cms-ib.cern.ch/nweek-02690/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_GPU_X_2021-07-18-2300/external/slc7_amd64_gcc900/data/HeterogeneousCore/SonicTriton/data/models/gat_test/config.pbtxt -t /pool/condor/dir_17213/1c95b347-fce9-487f-a68b-dc9f5a9f4ae9 start
%MSG
%MSG-i TritonService:  AfterModConstruction 19-Jul-2021 01:07:26 UTC pre-events
CMS_TRITON_GRPC_PORT: 8001
ERROR:   container cleanup failed: no instance found with name triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b
FATAL:   container creation failed: unable to add /pool/condor/dir_17213/1c95b347-fce9-487f-a68b-dc9f5a9f4ae9/-B to mount list: destination must be an absolute path

FATAL:   failed to start instance: while running /usr/libexec/singularity/bin/starter: exit status 255
Error for command "stop": no instance found

Usage:
  singularity [global options...] instance stop [stop options...] [instance]

Run 'singularity --help' for more detailed usage information.
mv: cannot stat 'log_triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b.log': No such file or directory
Retrying after container issue...
ERROR:   container cleanup failed: no instance found with name triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b
FATAL:   container creation failed: unable to add /pool/condor/dir_17213/1c95b347-fce9-487f-a68b-dc9f5a9f4ae9/-B to mount list: destination must be an absolute path

FATAL:   failed to start instance: while running /usr/libexec/singularity/bin/starter: exit status 255
Error for command "stop": no instance found

Usage:
  singularity [global options...] instance stop [stop options...] [instance]

Run 'singularity --help' for more detailed usage information.
mv: cannot stat 'log_triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b.log': No such file or directory
Retrying after container issue...
ERROR:   container cleanup failed: no instance found with name triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b
FATAL:   container creation failed: unable to add /pool/condor/dir_17213/1c95b347-fce9-487f-a68b-dc9f5a9f4ae9/-B to mount list: destination must be an absolute path

FATAL:   failed to start instance: while running /usr/libexec/singularity/bin/starter: exit status 255
Error for command "stop": no instance found

Usage:
  singularity [global options...] instance stop [stop options...] [instance]

Run 'singularity --help' for more detailed usage information.
mv: cannot stat 'log_triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b.log': No such file or directory
Retrying after container issue...
Error from Singularity

%MSG
----- Begin Fatal Exception 19-Jul-2021 01:07:26 UTC-----------------------
An exception of category 'FallbackFailed' occurred while
   [0] Calling beginJob
Exception Message:
Starting the fallback server failed with exit code 65280
----- End Fatal Exception -------------------------------------------------

---> test TestHeterogeneousCoreSonicTritonProducerCPU had ERRORS
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_GPU_X_2021-07-18-2300/unitTestLogs/HeterogeneousCore/SonicTriton#/

### LINKED ISSUE #35206: HeterogeneousCore/SonicTriton unit test failing for PPC IBs
The test TestHeterogeneousCoreSonicTritonProducerGPU
is failing for PPC.
From inside the job script it doesn't look like it's only for x86 archs:
https://github.com/cms-sw/cmssw/blob/master/HeterogeneousCore/SonicTriton/test/unittest.sh
The test also runs for aarch64:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_aarch64_gcc9/CMSSW_12_1_X_2021-09-06-2300/unitTestLogs/HeterogeneousCore/SonicTriton#/

When running manually, the test runs:

```

Package HeterogeneousCore/SonicTriton: Running test TestHeterogeneousCoreSonicTritonProducerCPU
 
===== Test "TestHeterogeneousCoreSonicTritonProducerCPU" ====
missing avx

---> test TestHeterogeneousCoreSonicTritonProducerCPU succeeded
TestTime:0
^^^^ End Test TestHeterogeneousCoreSonicTritonProducerCPU ^^^^
Package HeterogeneousCore/SonicTriton: Running test TestHeterogeneousCoreSonicTritonProducerGPU
 
===== Test "TestHeterogeneousCoreSonicTritonProducerGPU" ====
/scratch/mrodozov/triton/CMSSW_12_1_X_2021-09-08-2300/src/HeterogeneousCore/SonicTriton/test/unittest.sh: line 13: nvidia-smi: command not found
missing GPU

---> test TestHeterogeneousCoreSonicTritonProducerGPU succeeded
TestTime:0

```

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Resolves #34547 (GPU IB tests)
Resolves #35206 (PPC IB tests)

#### PR validation:

Ran tests on machines with appropriate architectures/hardware.

### CODE REVIEW

**Comment by makortel** [comment]
test parameters:
  - enable tests = gpu
  - release = slc7_ppc64le_gcc9

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
@makortel the bot gave your test settings a thumbs down... I think that means there's a syntax error

**Comment by makortel** [comment]
test parameters:
  - enable_tests = gpu
  - release = slc7_ppc64le_gcc9

**Comment by makortel** [comment]
@kpedro Thanks, let's see if I was more successful now...

**Comment by makortel** [comment]
@cmsbuild, please test

File: HeterogeneousCore/SonicTriton/test/unittest.sh [hunk 1]
```diff
@@ -16,6 +18,18 @@ if [ "$DEVICE" = "GPU" ]; then
...
+	SANDBOX=$(cmsTriton info)
+	# get sandbox env vars in subshell
+	CUDA_DRIVER_VERSION=$(source ${SANDBOX}/.singularity.d/env/10-docker2singularity.sh && echo $CUDA_DRIVER_VERSION)
+	# copied from https://github.com/triton-inference-server/server/blob/v2.11.0/nvidia_entrypoint.sh
+	DRIVER_VERSION=$(sed -n 's/^NVRM.*Kernel Module *\([0-9.]*\).*$/\1/p' /proc/driver/nvidia/version 2>/dev/null || true)
+	if [[ "${DRIVER_VERSION%%.*}" -ge "${CUDA_DRIVER_VERSION%%.*}" ]]; then
+		echo "has NVIDIA driver"
+	else
+		echo "missing (or too old) NVIDIA driver"
+		exit 0
```
Comment (fwyzard) [inline HeterogeneousCore/SonicTriton/test/unittest.sh:31]: Rather than simply bailing out, you could try using the CUDA compatibility drivers that are shipped with CMSSW.

You can see how it is implemented for the CMSSW environment set up by SCRAM in https://github.com/cms-sw/cmssw-config/blob/scramv3/SCRAM/hooks/runtime/00-nvidia-drivers .

For more (somewhat confusing) information, see https://docs.nvidia.com/deploy/cuda-compatibility/ .

Comment (kpedro88) [reply HeterogeneousCore/SonicTriton/test/unittest.sh:26]: Thanks, this is a definite improvement. The PR is updated with this now. I have a few questions and comments that I'll post in the main PR thread.

**Comment by kpedro88** [comment]
Compatibility drivers are now working.

This actually led to a bug report for Triton, https://github.com/triton-inference-server/server/issues/3382, though it's possible the actual bug should be fixed in nvidia-docker or something lower-level. For now, I've implemented a workaround in `cmsTriton`.

A few questions (for @fwyzard or anyone else who knows):

1. When I run `cuda-compatible-runtime -v` on a (datacenter) GPU with older drivers, it reports:
    ```
    CUDA driver version 11.2
    CUDA runtime version 11.4
    ```
    and succeeds even without putting the compatibility drivers in `LD_LIBRARY_PATH` (as [00-nvidia-drivers](https://github.com/cms-sw/cmssw-config/blob/scramv3/SCRAM/hooks/runtime/00-nvidia-drivers) does if the test fails without the compatibility drivers). Is this expected?
2. What is the right way to test for non-datacenter GPUs, for which the compatibility drivers won't work (if I understand correctly)?

**Comment by kpedro88** [comment]
I also find the documentation rather confusing.

From what I can tell with the Triton server, it's a bit pickier than CMSSW: it cares about driver-driver compatibility, not driver-runtime compatibility. I think the check I've implemented handles this properly.

As far as non-datacenter GPUs, I guess it's fine if the test just fails on those machines for now, since it's unlikely we'll be running IB tests on them frequently. (I actually have such a GPU, but I keep its drivers up to date in order to continue Triton-related development.)

**Comment by kpedro88** [comment]
please test

**Comment by fwyzard** [comment]
> From what I can tell with the Triton server, it's a bit pickier than CMSSW: it cares about driver-driver compatibility, not driver-runtime compatibility. I think the check I've implemented handles this properly.

Ah... then maybe Triton (or, possibly, the TensorRT backend) is implemented using the CUDA driver API, rather than the runtime API.

**Comment by kpedro88** [comment]
@fwyzard @makortel any further comments or tests?

**Comment by makortel** [comment]
Looks ok to me

**Comment by fwyzard** [comment]
The changes to the main part look good.

Skipping the unit test on non-`amd64` architectures doesn't seem like the intended behaviour for the unit tests - but I can see the point, since we don't have an "expected to fail" category for the tests.

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1
- Technical
- Tested by the experts
