### PR TITLE
Extend an exception message to mention fillDescriptions() function

### LINKED ISSUE #1723: Extend an exception message to mention fillDescriptions() function
### Description

See https://github.com/cms-sw/cmssw/issues/49642

### LINKED ISSUE #49642: Improve fillDescriptions error message
Currently having a parameter in a python configuration file which is not added to the `fillDescriptions` method throws `Illegal parameter found in configuration.`, even if the parameter is declared and defined as a member of the class/module using the configuration. For instance:

```
----- Begin Fatal Exception 16-Dec-2025 16:00:23 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of module: class=EcalGeometryAnalyzer label='ecalGeometryAnalyzer'
Exception Message:
Illegal parameter found in configuration.  The parameter is named:
 'ClusterSimClusterAssociator'
You could be trying to use a parameter name that is not
allowed for this plugin or it could be misspelled.
----- End Fatal Exception -------------------------------------------------
```

Would it be possible to make this error clearer, mentioning for instance that the default configuration provided by `fillDescriptions(...)` does not match the one provided by the configuration?

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/49642
Resolves https://github.com/cms-sw/framework-team/issues/1723

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
looks good to me.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/47071

**Comment by mandrenguyen** [comment]
+1

File: FWCore/ParameterSet/src/ParameterSetDescription.cc [hunk 1]
```diff
@@ -226,12 +226,14 @@ namespace edm {
...
-          << "allowed for this plugin or it could be misspelled.\n";
+          << "allowed for this plugin, or it could be misspelled, or this parameter\n"
+          << "needs to be defined in the fillDescription() method of the plugin.\n";
     } else {
       throw edm::Exception(errors::Configuration)
           << "Illegal parameters found in configuration.  The parameters are named:\n"
           << ss.str() << "You could be trying to use parameter names that are not\n"
-          << "allowed for this plugin or they could be misspelled.\n";
+          << "allowed for this plugin, or they could be misspelled, or these parameters\n"
+          << "need to be defined in the fillDescription() method of the plugin.\n";
```
Comment (Martin-Grunewald) [inline FWCore/ParameterSet/src/ParameterSetDescription.cc:236]: Picky: spelling ```fillDescriptions()``` (trailing ```s```)

Comment (makortel) [reply FWCore/ParameterSet/src/ParameterSetDescription.cc:236]: Thanks for catching, fixed in https://github.com/cms-sw/cmssw/pull/49657
